var NAVTREEINDEX1 =
{
"index.html#bso_ssecaggregated_gen_ops":[0,3,3],
"index.html#bso_sseccirc_seg":[0,3,1],
"index.html#bso_ssecgeneral_polygon_concept":[0,3,2],
"index.html#bso_ssecinsert_ni":[0,2,6],
"index.html#bso_ssecmain_component":[0,2,4],
"index.html#bso_ssecpolygon_validation":[0,1,0],
"index.html#bso_ssecpolygon_with_holes_validation":[0,1,1],
"index.html#bso_ssecpolygons_with_holes":[0,2,1],
"index.html#bso_ssectraits_concepts":[0,3,0],
"index.html#bso_ssectraits_sel":[0,2,8],
"index.html#bso_sssecex_simple_bops":[0,2,2],
"index.html#bso_sssecpwh_bops":[0,2,3],
"index.html#bso_sssecsequence":[0,2,5],
"models.html":[4],
"modules.html":[1],
"namespaceArrDirectionalTraits.html":[8,0],
"namespaceCGAL.html":[8,1],
"pages.html":[],
"refines.html":[3],
"todo.html":[2]
};
