var searchData=
[
  ['3_0',['3',['../../Polyhedron/group__PkgDrawPolyhedron.html',1,'Draw a Polyhedron 3'],['../../Triangulation_3/group__PkgDrawTriangulation3.html',1,'Draw a Triangulation 3'],['../../Triangulation_3/group__PkgIOTriangulation3.html',1,'I/O for a Triangulation 3']]],
  ['3_20manual_1',['CGAL 6.1.3 - Manual',['../index.html',1,'']]],
  ['3d_20alpha_20shapes_2',['3D Alpha Shapes',['../packages.html#PkgAlphaShapes3',1,'']]],
  ['3d_20alpha_20wrapping_3',['3D Alpha Wrapping',['../packages.html#PkgAlphaWrap3',1,'']]],
  ['3d_20boolean_20operations_20on_20nef_20polyhedra_4',['3D Boolean Operations on Nef Polyhedra',['../packages.html#PkgNef3',1,'']]],
  ['3d_20constrained_20triangulation_5',['Draw a 3D Constrained Triangulation',['../../Constrained_triangulation_3/group__PkgDrawCDT__3.html',1,'']]],
  ['3d_20constrained_20triangulations_6',['3D Constrained Triangulations',['../packages.html#PkgConstrainedTriangulation3',1,'']]],
  ['3d_20convex_20hulls_7',['3D Convex Hulls',['../packages.html#PkgConvexHull3',1,'']]],
  ['3d_20envelopes_8',['3D Envelopes',['../packages.html#PkgEnvelope3',1,'']]],
  ['3d_20fast_20intersection_20and_20distance_20computation_9',['2D and 3D Fast Intersection and Distance Computation',['../packages.html#PkgAABBTree',1,'']]],
  ['3d_20isosurfacing_10',['3D Isosurfacing',['../packages.html#PkgIsosurfacing3',1,'']]],
  ['3d_20kernel_20objects_11',['3D Kernel Objects',['../../Kernel_23/group__kernel__classes3.html',1,'']]],
  ['3d_20linear_20geometry_20kernel_12',['2D and 3D Linear Geometry Kernel',['../packages.html#PkgKernel23',1,'']]],
  ['3d_20linear_20kernel_13',['3D Linear Kernel',['../../Kernel_23/group__compare__x__linear__grp.html',1,'CGAL::compare_x() (2D/3D Linear Kernel)'],['../../Kernel_23/group__compare__xy__linear__grp.html',1,'CGAL::compare_xy() (2D/3D Linear Kernel)'],['../../Kernel_23/group__compare__xyz__linear__grp.html',1,'CGAL::compare_xyz() (2D/3D Linear Kernel)'],['../../Kernel_23/group__compary__y__linear__grp.html',1,'CGAL::compare_y() (2D/3D Linear Kernel)'],['../../Kernel_23/group__compare__z__linear__grp.html',1,'CGAL::compare_z() (2D/3D Linear Kernel)'],['../../Kernel_23/group__do__intersect__linear__grp.html',1,'CGAL::do_intersect() (2D/3D Linear Kernel)'],['../../Kernel_23/group__intersection__linear__grp.html',1,'CGAL::intersection() (2D/3D Linear Kernel)']]],
  ['3d_20mesh_20generation_14',['3D Mesh Generation',['../packages.html#PkgMesh3',1,'']]],
  ['3d_20minkowski_20sum_20of_20polyhedra_15',['3D Minkowski Sum of Polyhedra',['../packages.html#PkgMinkowskiSum3',1,'']]],
  ['3d_20periodic_20mesh_20generation_16',['3D Periodic Mesh Generation',['../packages.html#PkgPeriodic3Mesh3',1,'']]],
  ['3d_20periodic_20triangulations_17',['3D Periodic Triangulations',['../packages.html#PkgPeriodic3Triangulation3',1,'']]],
  ['3d_20point_20set_18',['3D Point Set',['../packages.html#PkgPointSet3',1,'3D Point Set'],['../../Point_set_3/group__PkgDrawPointSet3D.html',1,'Draw a 3D Point Set']]],
  ['3d_20polyhedral_20surface_19',['3D Polyhedral Surface',['../packages.html#PkgPolyhedron',1,'']]],
  ['3d_20simplicial_20mesh_20data_20structure_20',['3D Simplicial Mesh Data Structure',['../packages.html#PkgSMDS3',1,'']]],
  ['3d_20skin_20surface_20meshing_21',['3D Skin Surface Meshing',['../packages.html#PkgSkinSurface3',1,'']]],
  ['3d_20spherical_20geometry_20kernel_22',['3D Spherical Geometry Kernel',['../packages.html#PkgCircularKernel3',1,'']]],
  ['3d_20spherical_20kernel_23',['3D Spherical Kernel',['../../Kernel_23/group__compare__x__spherical__grp.html',1,'CGAL::compare_x() (3D Spherical Kernel)'],['../../Kernel_23/group__compare__xy__spherical__grp.html',1,'CGAL::compare_xy() (3D Spherical Kernel)'],['../../Kernel_23/group__compare__xyz__spherical__grp.html',1,'CGAL::compare_xyz() (3D Spherical Kernel)'],['../../Kernel_23/group__compare__y__spherical__grp.html',1,'CGAL::compare_y() (3D Spherical Kernel)'],['../../Kernel_23/group__compare__z__spherical__grp.html',1,'CGAL::compare_z() (3D Spherical Kernel)'],['../../Kernel_23/group__do__intersect__spherical__grp.html',1,'CGAL::do_intersect() (3D Spherical Kernel)'],['../../Kernel_23/group__intersection__spherical__grp.html',1,'CGAL::intersection() (3D Spherical Kernel)']]],
  ['3d_20surface_20mesh_20generation_24',['3D Surface Mesh Generation',['../packages.html#PkgSurfaceMesher3',1,'']]],
  ['3d_20surface_20neighbor_20coordinates_20functions_25',['3D Surface Neighbor Coordinates Functions',['../../Interpolation/group__PkgInterpolationSurfaceNeighborCoordinates3.html',1,'']]],
  ['3d_20surface_20neighbors_20functions_26',['3D Surface Neighbors Functions',['../../Interpolation/group__PkgInterpolationSurfaceNeighbors3.html',1,'']]],
  ['3d_20surface_20subdivision_20methods_27',['3D Surface Subdivision Methods',['../packages.html#PkgSurfaceSubdivisionMethod3',1,'']]],
  ['3d_20triangulation_20data_20structure_28',['3D Triangulation Data Structure',['../packages.html#PkgTDS3',1,'']]],
  ['3d_20triangulations_29',['3D Triangulations',['../packages.html#PkgTriangulation3',1,'']]],
  ['3mf_30',['I/O Functions (3MF)',['../../Surface_mesh/group__PkgSurfaceMeshIOFunc3MF.html',1,'']]],
  ['3mf_20i_20o_20functions_31',['3MF I O Functions',['../../BGL/group__PkgBGLIoFuncs3MF.html',1,'3MF I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncs3MF.html',1,'3MF I/O Functions']]],
  ['3rd_20party_20libraries_32',['Variables Providing Information About 3rd-Party Libraries',['../configurationvariables.html#installation_variables_third_party',1,'']]]
];
