var searchData=
[
  ['2_0',['2',['../../Triangulation_2/group__PkgDrawConstrainedTriangulation2.html',1,'Draw a Constrained Triangulation 2'],['../../Triangulation_2/group__PkgDrawTriangulation2.html',1,'Draw a Triangulation 2']]],
  ['2020_20or_20before_1',['TBB 2020 or before',['../configurationvariables.html#installation_old_tbb',1,'']]],
  ['2d_203d_20linear_20kernel_2',['2D 3D Linear Kernel',['../../Kernel_23/group__compare__x__linear__grp.html',1,'CGAL::compare_x() (2D/3D Linear Kernel)'],['../../Kernel_23/group__compare__xy__linear__grp.html',1,'CGAL::compare_xy() (2D/3D Linear Kernel)'],['../../Kernel_23/group__compare__xyz__linear__grp.html',1,'CGAL::compare_xyz() (2D/3D Linear Kernel)'],['../../Kernel_23/group__compary__y__linear__grp.html',1,'CGAL::compare_y() (2D/3D Linear Kernel)'],['../../Kernel_23/group__compare__z__linear__grp.html',1,'CGAL::compare_z() (2D/3D Linear Kernel)'],['../../Kernel_23/group__do__intersect__linear__grp.html',1,'CGAL::do_intersect() (2D/3D Linear Kernel)'],['../../Kernel_23/group__intersection__linear__grp.html',1,'CGAL::intersection() (2D/3D Linear Kernel)']]],
  ['2d_20alpha_20shapes_3',['2D Alpha Shapes',['../packages.html#PkgAlphaShapes2',1,'']]],
  ['2d_20and_203d_20fast_20intersection_20and_20distance_20computation_4',['2D and 3D Fast Intersection and Distance Computation',['../packages.html#PkgAABBTree',1,'']]],
  ['2d_20and_203d_20linear_20geometry_20kernel_5',['2D and 3D Linear Geometry Kernel',['../packages.html#PkgKernel23',1,'']]],
  ['2d_20and_20surface_20function_20interpolation_6',['2D and Surface Function Interpolation',['../packages.html#PkgInterpolation2',1,'']]],
  ['2d_20apollonius_20graphs_20delaunay_20graphs_20of_20disks_7',['2D Apollonius Graphs (Delaunay Graphs of Disks)',['../packages.html#PkgApolloniusGraph2',1,'']]],
  ['2d_20arrangements_8',['2D Arrangements',['../packages.html#PkgArrangementOnSurface2',1,'']]],
  ['2d_20boolean_20operations_20on_20nef_20polygons_9',['2D Boolean Operations on Nef Polygons',['../packages.html#PkgNef2',1,'']]],
  ['2d_20boolean_20operations_20on_20nef_20polygons_20embedded_20on_20the_20sphere_10',['2D Boolean Operations on Nef Polygons Embedded on the Sphere',['../packages.html#PkgNefS2',1,'']]],
  ['2d_20circular_20geometry_20kernel_11',['2D Circular Geometry Kernel',['../packages.html#PkgCircularKernel2',1,'']]],
  ['2d_20circular_20kernel_12',['2D Circular Kernel',['../../Kernel_23/group__compare__x__circular__grp.html',1,'CGAL::compare_x() (2D Circular Kernel)'],['../../Kernel_23/group__compare__xy__circular__grp.html',1,'CGAL::compare_xy() (2D Circular Kernel)'],['../../Kernel_23/group__compare__y__circular__grp.html',1,'CGAL::compare_y() (2D Circular Kernel)'],['../../Kernel_23/group__do__intersect__circular__grp.html',1,'CGAL::do_intersect() (2D Circular Kernel)'],['../../Kernel_23/group__intersection__circular__grp.html',1,'CGAL::intersection() (2D Circular Kernel)']]],
  ['2d_20conforming_20triangulations_20and_20meshes_13',['2D Conforming Triangulations and Meshes',['../packages.html#PkgMesh2',1,'']]],
  ['2d_20convex_20hulls_20and_20extreme_20points_14',['2D Convex Hulls and Extreme Points',['../packages.html#PkgConvexHull2',1,'']]],
  ['2d_20envelopes_15',['2D Envelopes',['../packages.html#PkgEnvelope2',1,'']]],
  ['2d_20generalized_20barycentric_20coordinates_16',['2D Generalized Barycentric Coordinates',['../packages.html#PkgBarycentricCoordinates2',1,'']]],
  ['2d_20hyperbolic_20delaunay_20triangulations_17',['2D Hyperbolic Delaunay Triangulations',['../packages.html#PkgHyperbolicTriangulation2',1,'']]],
  ['2d_20intersection_20of_20curves_18',['2D Intersection of Curves',['../packages.html#PkgSurfaceSweep2',1,'']]],
  ['2d_20kernel_20objects_19',['2D Kernel Objects',['../../Kernel_23/group__kernel__classes2.html',1,'']]],
  ['2d_20minkowski_20sums_20',['2D Minkowski Sums',['../packages.html#PkgMinkowskiSum2',1,'']]],
  ['2d_20movable_20separability_20of_20sets_21',['2D Movable Separability of Sets',['../packages.html#PkgSetMovableSeparability2',1,'']]],
  ['2d_20multipolygon_20with_20holes_22',['Draw a 2D Multipolygon with Holes',['../../Polygon/group__PkgDrawMultipolygonWithHoles2.html',1,'']]],
  ['2d_20periodic_20hyperbolic_20triangulations_23',['2D Periodic Hyperbolic Triangulations',['../packages.html#PkgPeriodic4HyperbolicTriangulation2',1,'']]],
  ['2d_20periodic_20triangulation_24',['Draw a 2D Periodic Triangulation',['../../Periodic_2_triangulation_2/group__PkgDrawPeriodic2Triangulation2.html',1,'']]],
  ['2d_20periodic_20triangulations_25',['2D Periodic Triangulations',['../packages.html#PkgPeriodic2Triangulation2',1,'']]],
  ['2d_20placement_20of_20streamlines_26',['2D Placement of Streamlines',['../packages.html#PkgStreamLines2',1,'']]],
  ['2d_20polygon_27',['Draw a 2D Polygon',['../../Polygon/group__PkgDrawPolygon2.html',1,'']]],
  ['2d_20polygon_20partitioning_28',['2D Polygon Partitioning',['../packages.html#PkgPartition2',1,'']]],
  ['2d_20polygon_20repair_29',['2D Polygon Repair',['../packages.html#PkgPolygonRepair',1,'']]],
  ['2d_20polygon_20set_30',['Draw a 2D Polygon Set',['../../Boolean_set_operations_2/group__PkgDrawPolygonSet2.html',1,'']]],
  ['2d_20polygon_20with_20holes_31',['Draw a 2D Polygon with Holes',['../../Polygon/group__PkgDrawPolygonWithHoles2.html',1,'']]],
  ['2d_20polygons_32',['2D Polygons',['../packages.html#PkgPolygon2',1,'']]],
  ['2d_20polyline_20simplification_33',['2D Polyline Simplification',['../packages.html#PkgPolylineSimplification2',1,'']]],
  ['2d_20range_20and_20neighbor_20search_34',['2D Range and Neighbor Search',['../packages.html#PkgPointSet2',1,'']]],
  ['2d_20regularized_20boolean_20set_20operations_35',['2D Regularized Boolean Set-Operations',['../packages.html#PkgBooleanSetOperations2',1,'']]],
  ['2d_20segment_20delaunay_20graphs_36',['2D Segment Delaunay Graphs',['../packages.html#PkgSegmentDelaunayGraph2',1,'']]],
  ['2d_20snap_20rounding_37',['2D Snap Rounding',['../packages.html#PkgSnapRounding2',1,'']]],
  ['2d_20straight_20skeleton_20and_20polygon_20offsetting_38',['2D Straight Skeleton and Polygon Offsetting',['../packages.html#PkgStraightSkeleton2',1,'']]],
  ['2d_20triangulation_20data_20structure_39',['2D Triangulation Data Structure',['../packages.html#PkgTDS2',1,'']]],
  ['2d_20triangulations_40',['2D Triangulations',['../packages.html#PkgTriangulation2',1,'']]],
  ['2d_20triangulations_20on_20hyperbolic_20surfaces_41',['2D Triangulations on Hyperbolic Surfaces',['../packages.html#PkgHyperbolicSurfaceTriangulation2',1,'']]],
  ['2d_20triangulations_20on_20the_20sphere_42',['2D Triangulations on the Sphere',['../packages.html#PkgTriangulationOnSphere2',1,'']]],
  ['2d_20visibility_20computation_43',['2D Visibility Computation',['../packages.html#PkgVisibility2',1,'']]],
  ['2d_20voronoi_20diagram_44',['Draw a 2D Voronoi Diagram',['../../Voronoi_diagram_2/group__PkgDrawVoronoiDiagram2.html',1,'']]],
  ['2d_20voronoi_20diagram_20adaptor_45',['2D Voronoi Diagram Adaptor',['../packages.html#PkgVoronoiDiagram2',1,'']]]
];
