var searchData=
[
  ['3_0',['3',['../../Polyhedron/group__PkgDrawPolyhedron.html',1,'Draw a Polyhedron 3'],['../../Triangulation_3/group__PkgDrawTriangulation3.html',1,'Draw a Triangulation 3'],['../../Triangulation_3/group__PkgIOTriangulation3.html',1,'I/O for a Triangulation 3']]],
  ['3d_20constrained_20triangulation_1',['Draw a 3D Constrained Triangulation',['../../Constrained_triangulation_3/group__PkgDrawCDT__3.html',1,'']]],
  ['3d_20kernel_20objects_2',['3D Kernel Objects',['../../Kernel_23/group__kernel__classes3.html',1,'']]],
  ['3d_20linear_20kernel_3',['3D Linear Kernel',['../../Kernel_23/group__compare__x__linear__grp.html',1,'CGAL::compare_x() (2D/3D Linear Kernel)'],['../../Kernel_23/group__compare__xy__linear__grp.html',1,'CGAL::compare_xy() (2D/3D Linear Kernel)'],['../../Kernel_23/group__compare__xyz__linear__grp.html',1,'CGAL::compare_xyz() (2D/3D Linear Kernel)'],['../../Kernel_23/group__compary__y__linear__grp.html',1,'CGAL::compare_y() (2D/3D Linear Kernel)'],['../../Kernel_23/group__compare__z__linear__grp.html',1,'CGAL::compare_z() (2D/3D Linear Kernel)'],['../../Kernel_23/group__do__intersect__linear__grp.html',1,'CGAL::do_intersect() (2D/3D Linear Kernel)'],['../../Kernel_23/group__intersection__linear__grp.html',1,'CGAL::intersection() (2D/3D Linear Kernel)']]],
  ['3d_20point_20set_4',['Draw a 3D Point Set',['../../Point_set_3/group__PkgDrawPointSet3D.html',1,'']]],
  ['3d_20spherical_20kernel_5',['3D Spherical Kernel',['../../Kernel_23/group__compare__x__spherical__grp.html',1,'CGAL::compare_x() (3D Spherical Kernel)'],['../../Kernel_23/group__compare__xy__spherical__grp.html',1,'CGAL::compare_xy() (3D Spherical Kernel)'],['../../Kernel_23/group__compare__xyz__spherical__grp.html',1,'CGAL::compare_xyz() (3D Spherical Kernel)'],['../../Kernel_23/group__compare__y__spherical__grp.html',1,'CGAL::compare_y() (3D Spherical Kernel)'],['../../Kernel_23/group__compare__z__spherical__grp.html',1,'CGAL::compare_z() (3D Spherical Kernel)'],['../../Kernel_23/group__do__intersect__spherical__grp.html',1,'CGAL::do_intersect() (3D Spherical Kernel)'],['../../Kernel_23/group__intersection__spherical__grp.html',1,'CGAL::intersection() (3D Spherical Kernel)']]],
  ['3d_20surface_20neighbor_20coordinates_20functions_6',['3D Surface Neighbor Coordinates Functions',['../../Interpolation/group__PkgInterpolationSurfaceNeighborCoordinates3.html',1,'']]],
  ['3d_20surface_20neighbors_20functions_7',['3D Surface Neighbors Functions',['../../Interpolation/group__PkgInterpolationSurfaceNeighbors3.html',1,'']]],
  ['3mf_8',['I/O Functions (3MF)',['../../Surface_mesh/group__PkgSurfaceMeshIOFunc3MF.html',1,'']]],
  ['3mf_20i_20o_20functions_9',['3MF I O Functions',['../../BGL/group__PkgBGLIoFuncs3MF.html',1,'3MF I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncs3MF.html',1,'3MF I/O Functions']]]
];
