var searchData=
[
  ['o_0',['O',['../../Arrangement_on_surface_2/group__PkgArrangementOnSurface2IO.html',1,'I/O'],['../../Surface_mesher/group__PkgSurfaceMesher3FunctionsIO.html',1,'I/O']]],
  ['o_20enums_1',['I/O Enums',['../../Stream_support/group__PkgStreamSupportEnumRef.html',1,'']]],
  ['o_20for_20a_20triangulation_203_2',['I/O for a Triangulation 3',['../../Triangulation_3/group__PkgIOTriangulation3.html',1,'']]],
  ['o_20for_20a_20triangulation_5fdata_5fstructure_5f3_3',['I/O for a Triangulation_data_structure_3',['../../TDS_3/group__PkgIOTDS3.html',1,'']]],
  ['o_20functions_4',['O Functions',['../../BGL/group__PkgBGLIoFuncs3MF.html',1,'3MF I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncs3MF.html',1,'3MF I/O Functions'],['../../BGL/group__PkgBGLIoFuncsGOCAD.html',1,'GOCAD I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncsGOCAD.html',1,'GOCAD I/O Functions'],['../../Polyhedron/group__PkgPolyhedronIOFunc.html',1,'I/O Functions'],['../../Surface_mesh/group__PkgSurfaceMeshIOFunc.html',1,'I/O Functions'],['../../Nef_3/group__PkgNef3IOFunctions.html',1,'I/O Functions'],['../../Mesh_2/group__PkgMesh2IO.html',1,'I/O Functions'],['../../Isosurfacing_3/group__IS__IO__functions__grp.html',1,'I/O Functions'],['../../Polygon_mesh_processing/group__PMP__IO__grp.html',1,'I/O Functions'],['../../Point_set_processing_3/group__PkgPointSetProcessing3IO.html',1,'I/O Functions'],['../../BGL/group__PkgBGLIOFct.html',1,'I/O Functions'],['../../Stream_support/group__IOstreamFunctions.html',1,'I/O Functions'],['../../BGL/group__PkgBGLIoFuncsOBJ.html',1,'OBJ I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncsOBJ.html',1,'OBJ I/O Functions'],['../../BGL/group__PkgBGLIoFuncsOFF.html',1,'OFF I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncsOFF.html',1,'OFF I/O Functions'],['../../BGL/group__PkgBGLIoFuncsOM.html',1,'OM I/O Functions'],['../../BGL/group__PkgBGLIoFuncsPLY.html',1,'PLY I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncsPLY.html',1,'PLY I/O Functions'],['../../BGL/group__PkgBGLIoFuncsSTL.html',1,'STL I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncsSTL.html',1,'STL I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncsVTK.html',1,'VTK I/O Functions'],['../../BGL/group__PkgBGLIoFuncsVTP.html',1,'VTP I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncsWKT.html',1,'WKT I/O Functions'],['../../BGL/group__PkgBGLIoFuncsWRL.html',1,'WRL I/O Functions']]],
  ['o_20functions_203mf_5',['I/O Functions (3MF)',['../../Surface_mesh/group__PkgSurfaceMeshIOFunc3MF.html',1,'']]],
  ['o_20functions_20deprecated_6',['O Functions Deprecated',['../../Surface_mesh/group__PkgSurfaceMeshIOFuncDeprecated.html',1,'I/O Functions (Deprecated)'],['../../BGL/group__PkgBGLIOFctDeprecated.html',1,'I/O Functions (Deprecated)']]],
  ['o_20functions_20off_7',['I/O Functions (OFF)',['../../Surface_mesh/group__PkgSurfaceMeshIOFuncOFF.html',1,'']]],
  ['o_20functions_20ply_8',['I/O Functions (PLY)',['../../Surface_mesh/group__PkgSurfaceMeshIOFuncPLY.html',1,'']]],
  ['o_20las_20format_9',['I/O (LAS Format)',['../../Point_set_processing_3/group__PkgPointSetProcessing3IOLas.html',1,'']]],
  ['o_20off_20formats_10',['I/O (OFF Formats)',['../../Point_set_processing_3/group__PkgPointSetProcessing3IOOff.html',1,'']]],
  ['o_20ply_20format_11',['I/O (PLY Format)',['../../Point_set_processing_3/group__PkgPointSetProcessing3IOPly.html',1,'']]],
  ['o_20xyz_20formats_12',['I/O (XYZ Formats)',['../../Point_set_processing_3/group__PkgPointSetProcessing3IOXyz.html',1,'']]],
  ['obj_20i_20o_20functions_13',['OBJ I O Functions',['../../BGL/group__PkgBGLIoFuncsOBJ.html',1,'OBJ I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncsOBJ.html',1,'OBJ I/O Functions']]],
  ['object_20classes_14',['Function Object Classes',['../../Partition_2/group__PkgPartition2FunctionObjectClasses.html',1,'']]],
  ['object_20concepts_15',['Object Concepts',['../../Partition_2/group__PkgPartition2FunctionObjectConcepts.html',1,'Function Object Concepts'],['../../Arrangement_on_surface_2/group__PkgArrangementOnSurface2ConceptsFunctionObjects.html',1,'Function Object Concepts'],['../../Arrangement_on_surface_2/group__PkgArrangementOnSurface2ConceptsGeometricObjects.html',1,'Geometric Object Concepts'],['../../Kernel_23/group__PkgKernel23ConceptsFunctionObjects.html',1,'Kernel Function Object Concepts'],['../../Kernel_23/group__PkgKernel23ConceptsGeomObject.html',1,'Kernel Geometric Object Concepts']]],
  ['objects_16',['Objects',['../../Kernel_23/group__kernel__classes2.html',1,'2D Kernel Objects'],['../../Kernel_23/group__kernel__classes3.html',1,'3D Kernel Objects'],['../../STL_Extension/group__STLCreators.html',1,'Creator Function Objects'],['../../Spatial_sorting/group__PkgSpatialSortingFunctionObjects.html',1,'Function Objects'],['../../Kernel_d/group__PkgKernelDKernelObjs.html',1,'Kernel Objects'],['../../STL_Extension/group__projectionobjects.html',1,'Projection Function Objects']]],
  ['of_20boost_3a_3agraph_5ftraits_17',['Specializations of boost::graph_traits',['../../BGL/group__PkgBGLTraits.html',1,'']]],
  ['of_20disks_18',['Voronoi Diagram of Disks',['../../Voronoi_diagram_2/group__PkgVoronoiDiagram2Disks.html',1,'']]],
  ['of_20points_19',['Voronoi Diagram of Points',['../../Voronoi_diagram_2/group__PkgVoronoiDiagram2Points.html',1,'']]],
  ['of_20segments_20',['Voronoi Diagram of Segments',['../../Voronoi_diagram_2/group__PkgVoronoiDiagram2Segments.html',1,'']]],
  ['off_21',['OFF',['../../Surface_mesh/group__PkgSurfaceMeshIOFuncOFF.html',1,'I/O Functions (OFF)'],['../../Point_set_3/group__PkgPointSet3IOOFF.html',1,'Input/Output (OFF)']]],
  ['off_20formats_22',['I/O (OFF Formats)',['../../Point_set_processing_3/group__PkgPointSetProcessing3IOOff.html',1,'']]],
  ['off_20i_20o_20functions_23',['OFF I O Functions',['../../BGL/group__PkgBGLIoFuncsOFF.html',1,'OFF I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncsOFF.html',1,'OFF I/O Functions']]],
  ['offset_20construction_20functions_24',['Offset Construction Functions',['../../Straight_skeleton_2/group__PkgStraightSkeleton2OffsetFunctions.html',1,'Offset Construction Functions'],['../../Straight_skeleton_2/group__PkgStraightSkeleton2WeightedOffsetFunctions.html',1,'Weighted Offset Construction Functions']]],
  ['om_20i_20o_20functions_25',['OM I/O Functions',['../../BGL/group__PkgBGLIoFuncsOM.html',1,'']]],
  ['on_20polygon_20with_20holes_26',['Functions on Polygon with Holes',['../../Boolean_set_operations_2/group__boolean__connect__holes.html',1,'']]],
  ['opencv_27',['OpenCV',['../../Classification/group__PkgClassificationClassifiersOpenCV.html',1,'']]],
  ['operations_28',['Operations',['../../Polygon_mesh_processing/group__PMP__corefinement__grp.html',1,'Corefinement and Boolean Operations'],['../../BGL/group__PkgBGLEulerOperations.html',1,'Euler Operations'],['../../BGL/group__PkgBGLPartition.html',1,'Partitioning Operations']]],
  ['operations_20for_20linear_20cell_20complex_29',['Operations for Linear Cell Complex',['../../Linear_cell_complex/group__PkgLinearCellComplexOperations.html',1,'']]],
  ['operator_30',['operator',['../../Arrangement_on_surface_2/group__PkgArrangementOnSurface2op__right__shift.html',1,'operator&gt;&gt;'],['../../Arrangement_on_surface_2/group__PkgArrangementOnSurface2op__left__shift.html',1,'operator&lt;&lt;']]],
  ['operators_31',['Stream Operators',['../../Stream_support/group__IOstreamOperators.html',1,'']]],
  ['optimal_20bounding_20box_20classes_32',['Optimal Bounding Box Classes',['../../Optimal_bounding_box/group__PkgOptimalBoundingBoxClasses.html',1,'']]],
  ['optimal_20bounding_20box_20functions_33',['Optimal Bounding Box Functions',['../../Optimal_bounding_box/group__PkgOptimalBoundingBoxFunctions.html',1,'']]],
  ['orbifold_20helper_20functions_34',['Orbifold Helper Functions',['../../Surface_mesh_parameterization/group__PkgSurfaceMeshParameterizationOrbifoldHelperFunctions.html',1,'']]],
  ['orientation_20functions_35',['Orientation Functions',['../../Polygon_mesh_processing/group__PMP__orientation__grp.html',1,'']]],
  ['oriented_20bounding_20box_20functions_36',['Oriented Bounding Box Functions',['../../Optimal_bounding_box/group__PkgOptimalBoundingBox__Oriented__bounding__box.html',1,'']]],
  ['oriented_20side_20functions_37',['Oriented Side Functions',['../../Boolean_set_operations_2/group__boolean__oriented__side.html',1,'']]],
  ['other_20functions_38',['Other Functions',['../../Constrained_triangulation_3/group__PkgConstrainedTriangulation3Functions.html',1,'']]],
  ['output_39',['Input/Output',['../../Point_set_3/group__PkgPointSet3IO.html',1,'']]],
  ['output_20deprecated_40',['Input/Output (Deprecated)',['../../Point_set_3/group__PkgPointSet3IODeprecated.html',1,'']]],
  ['output_20functions_41',['Output Functions',['../../Triangulation_on_hyperbolic_surface_2/group__PkgHyperbolicSurfaceTriangulation2InputOutput.html',1,'Input/Output Functions'],['../../SMDS_3/group__PkgSMDS3IOFunctions.html',1,'Input/Output Functions'],['../../Mesh_3/group__PkgMesh3IOFunctions.html',1,'Input/Output Functions'],['../../Periodic_3_mesh_3/group__PkgPeriodic3Mesh3IOFunctions.html',1,'Input/Output Functions'],['../../Constrained_triangulation_3/group__PkgCDT3IOFunctions.html',1,'Output Functions']]],
  ['output_20las_42',['Input/Output (LAS)',['../../Point_set_3/group__PkgPointSet3IOLAS.html',1,'']]],
  ['output_20off_43',['Input/Output (OFF)',['../../Point_set_3/group__PkgPointSet3IOOFF.html',1,'']]],
  ['output_20ply_44',['Input/Output (PLY)',['../../Point_set_3/group__PkgPointSet3IOPLY.html',1,'']]],
  ['output_20xyz_45',['Input/Output (XYZ)',['../../Point_set_3/group__PkgPointSet3IOXYZ.html',1,'']]],
  ['overlay_46',['Overlay',['../../Arrangement_on_surface_2/group__PkgArrangementOnSurface2Overlay.html',1,'']]]
];
