var searchData=
[
  ['parameter_20functions_0',['Parameter Functions',['../../Mesh_3/group__PkgMesh3Parameters.html',1,'']]],
  ['parameterization_20methods_1',['Parameterization Methods',['../../Surface_mesh_parameterization/group__PkgSurfaceMeshParameterizationBorderParameterizationMethods.html',1,'Border Parameterization Methods'],['../../Surface_mesh_parameterization/group__PkgSurfaceMeshParameterizationMethods.html',1,'Surface Parameterization Methods']]],
  ['parameters_2',['Named Parameters',['../../BGL/group__bgl__namedparameters.html',1,'']]],
  ['partitioning_20data_20structures_3',['Space Partitioning Data Structures',['../../Isosurfacing_3/group__IS__Partitions__grp.html',1,'']]],
  ['partitioning_20data_20structures_20helpers_4',['Space Partitioning Data Structures Helpers',['../../Isosurfacing_3/group__IS__Partitions__helpers__grp.html',1,'']]],
  ['partitioning_20operations_5',['Partitioning Operations',['../../BGL/group__PkgBGLPartition.html',1,'']]],
  ['paths_6',['Draw a Mesh with Paths',['../../Surface_mesh_topology/group__PkgDrawFaceGraphWithPaths.html',1,'']]],
  ['periodic_20triangulation_7',['Draw a 2D Periodic Triangulation',['../../Periodic_2_triangulation_2/group__PkgDrawPeriodic2Triangulation2.html',1,'']]],
  ['pkgbglgeneratorrfct_8',['PkgBGLGeneratorrFct',['../../BGL/group__PkgBGLGeneratorrFct.html',1,'']]],
  ['place_9',['Doubly-Connected List Managing Items in Place',['../../STL_Extension/group__inplacelist.html',1,'']]],
  ['planes_10',['Planes',['../../Shape_regularization/group__PkgShapeRegularizationRefPlanes.html',1,'']]],
  ['ply_11',['PLY',['../../Surface_mesh/group__PkgSurfaceMeshIOFuncPLY.html',1,'I/O Functions (PLY)'],['../../Point_set_3/group__PkgPointSet3IOPLY.html',1,'Input/Output (PLY)']]],
  ['ply_20format_12',['I/O (PLY Format)',['../../Point_set_processing_3/group__PkgPointSetProcessing3IOPly.html',1,'']]],
  ['ply_20i_20o_20functions_13',['PLY I O Functions',['../../BGL/group__PkgBGLIoFuncsPLY.html',1,'PLY I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncsPLY.html',1,'PLY I/O Functions']]],
  ['point_20family_20weight_14',['Three Point Family Weight',['../../Weights/group__PkgWeightsRefThreePointFamilyWeights.html',1,'']]],
  ['point_20functions_15',['Extreme Point Functions',['../../Convex_hull_2/group__PkgConvexHull2Extreme.html',1,'']]],
  ['point_20location_16',['Point Location',['../../Arrangement_on_surface_2/group__PkgArrangementOnSurface2PointLocation.html',1,'']]],
  ['point_20set_17',['Point Set',['../../Point_set_3/group__PkgDrawPointSet3D.html',1,'Draw a 3D Point Set'],['../../Shape_detection/group__PkgShapeDetectionRGOnPoints.html',1,'Point Set']]],
  ['point_20set_20classification_18',['Point Set Classification',['../../Classification/group__PkgClassificationPointSet.html',1,'']]],
  ['point_5fset_5f3_19',['Convenience Aliases and Functions for Point_set_3',['../../Shape_detection/group__PkgShapeDetectionRGOnPointSet3.html',1,'']]],
  ['points_20',['Voronoi Diagram of Points',['../../Voronoi_diagram_2/group__PkgVoronoiDiagram2Points.html',1,'']]],
  ['polygon_21',['Draw a 2D Polygon',['../../Polygon/group__PkgDrawPolygon2.html',1,'']]],
  ['polygon_20intersection_20functions_22',['Polygon Intersection Functions',['../../Boolean_set_operations_2/group__boolean__intersection.html',1,'']]],
  ['polygon_20intersection_20testing_20functions_23',['Polygon Intersection Testing Functions',['../../Boolean_set_operations_2/group__boolean__do__intersect.html',1,'']]],
  ['polygon_20mesh_24',['Polygon Mesh',['../../Shape_detection/group__PkgShapeDetectionRGOnMesh.html',1,'']]],
  ['polygon_20set_25',['Draw a 2D Polygon Set',['../../Boolean_set_operations_2/group__PkgDrawPolygonSet2.html',1,'']]],
  ['polygon_20with_20holes_26',['Polygon with Holes',['../../Polygon/group__PkgDrawPolygonWithHoles2.html',1,'Draw a 2D Polygon with Holes'],['../../Boolean_set_operations_2/group__boolean__connect__holes.html',1,'Functions on Polygon with Holes']]],
  ['polyhedron_27',['Draw a Nef Polyhedron',['../../Nef_3/group__PkgDrawNef3.html',1,'']]],
  ['polyhedron_203_28',['Draw a Polyhedron 3',['../../Polyhedron/group__PkgDrawPolyhedron.html',1,'']]],
  ['polyline_20simplification_20classes_29',['Polyline Simplification Classes',['../../Polyline_simplification_2/group__PkgPolylineSimplification2Classes.html',1,'']]],
  ['predefined_20features_30',['Predefined Features',['../../Classification/group__PkgClassificationFeatures.html',1,'']]],
  ['predefined_20kernels_31',['Predefined Kernels',['../../Kernel_23/group__kernel__predef.html',1,'']]],
  ['predicates_32',['Predicates',['../../Polygon_mesh_processing/group__PMP__predicates__grp.html',1,'Predicates'],['../../Orthtree/group__PkgOrthtreeSplitPredicates.html',1,'Split Predicates']]],
  ['programming_33',['Programming',['../../Solver_interface/group__PkgSolverInterfaceMIP.html',1,'Mixed Integer Programming'],['../../Solver_interface/group__PkgSolverInterfaceNLP.html',1,'Nonlinear Programming']]],
  ['projection_20function_20objects_34',['Projection Function Objects',['../../STL_Extension/group__projectionobjects.html',1,'']]],
  ['properties_35',['Properties',['../../BGL/group__PkgBGLPropertiesDynamic.html',1,'Dynamic Properties'],['../../BGL/group__PkgBGLProperties.html',1,'Properties']]],
  ['property_20maps_36',['Property Maps',['../../Shape_detection/group__PkgShapeDetectionRANSACPropertyMaps.html',1,'']]],
  ['pullout_20direction_37',['Is Pullout Direction',['../../Set_movable_separability_2/group__is__pullout__direction__grp.html',1,'']]],
  ['pullout_20directions_38',['Pullout Directions',['../../Set_movable_separability_2/group__pullout__directions__grp.html',1,'']]]
];
