var searchData=
[
  ['macos_0',['Using CGAL on Unix (Linux, macOS, ...)',['../usage.html',1,'general_intro']]],
  ['macro_1',['The allocator macro',['../devman_memory_management.html#secallocator_macro',1,'']]],
  ['macros_20and_20flags_2',['Using the version-number and configuration macros and flags',['../devman_portability.html#secusing_version_macros',1,'']]],
  ['macros_20connected_20to_20workarounds_20compilers_3',['Macros connected to workarounds/compilers',['../devman_portability.html#secworkaround_macros',1,'']]],
  ['management_4',['Memory Management',['../devman_memory_management.html',1,'dev_manual']]],
  ['manager_5',['Manager',['../windows.html#sec-installing-with-vcpkg',1,'Installing CGAL with the Vcpkg Library Manager'],['../usage.html#secusingpkgman',1,'Using a Package Manager']]],
  ['manual_6',['Manual',['../index.html',1,'CGAL 6.1.3 - Manual'],['../dev_manual.html',1,'Developer Manual'],['../manual.html',1,'Organization of the Manual'],['../manual.html#secorganization',1,'Organization of the Manual'],['../manual.html#secorganizationref',1,'Organization of the Reference Manual']]],
  ['map_20union_20find_20modifiers_7',['Profiling tools, Hash Map, Union-find, Modifiers',['../packages.html#Miscellany',1,'']]],
  ['maps_8',['Maps',['../packages.html#PkgPropertyMap',1,'CGAL and Boost Property Maps'],['../packages.html#PkgCombinatorialMaps',1,'Combinatorial Maps'],['../packages.html#PkgGeneralizedMaps',1,'Generalized Maps']]],
  ['marking_20of_20special_20functionality_9',['Marking of Special Functionality',['../manual.html#markingSpecialFunctionality',1,'']]],
  ['matrix_20search_10',['Monotone and Sorted Matrix Search',['../packages.html#PkgMatrixSearch',1,'']]],
  ['memory_20management_11',['Memory Management',['../devman_memory_management.html',1,'dev_manual']]],
  ['mesh_12',['Surface Mesh',['../packages.html#PkgSurfaceMesh',1,'']]],
  ['mesh_20approximation_13',['Triangulated Surface Mesh Approximation',['../packages.html#PkgTSMA',1,'']]],
  ['mesh_20data_20structure_14',['3D Simplicial Mesh Data Structure',['../packages.html#PkgSMDS3',1,'']]],
  ['mesh_20deformation_15',['Triangulated Surface Mesh Deformation',['../packages.html#PkgSurfaceMeshDeformation',1,'']]],
  ['mesh_20generation_16',['Mesh Generation',['../packages.html#PkgMesh3',1,'3D Mesh Generation'],['../packages.html#PkgPeriodic3Mesh3',1,'3D Periodic Mesh Generation'],['../packages.html#PkgSurfaceMesher3',1,'3D Surface Mesh Generation'],['../packages.html#PartMeshing',1,'Mesh Generation']]],
  ['mesh_20parameterization_17',['Triangulated Surface Mesh Parameterization',['../packages.html#PkgSurfaceMeshParameterization',1,'']]],
  ['mesh_20processing_18',['Polygon Mesh Processing',['../packages.html#PkgPolygonMeshProcessing',1,'']]],
  ['mesh_20segmentation_19',['Triangulated Surface Mesh Segmentation',['../packages.html#PkgSurfaceMeshSegmentation',1,'']]],
  ['mesh_20shortest_20paths_20',['Triangulated Surface Mesh Shortest Paths',['../packages.html#PkgSurfaceMeshShortestPath',1,'']]],
  ['mesh_20simplification_21',['Triangulated Surface Mesh Simplification',['../packages.html#PkgSurfaceMeshSimplification',1,'']]],
  ['mesh_20skeletonization_22',['Triangulated Surface Mesh Skeletonization',['../packages.html#PkgSurfaceMeshSkeletonization',1,'']]],
  ['mesh_20topology_23',['Surface Mesh Topology',['../packages.html#PkgSurfaceMeshTopology',1,'']]],
  ['meshes_24',['Meshes',['../packages.html#PkgMesh2',1,'2D Conforming Triangulations and Meshes'],['../packages.html#PkgRidges3',1,'Approximation of Ridges and Umbilics on Triangulated Surface Meshes']]],
  ['meshing_25',['3D Skin Surface Meshing',['../packages.html#PkgSkinSurface3',1,'']]],
  ['method_26',['The Heat Method',['../packages.html#PkgHeatMethod',1,'']]],
  ['methods_27',['3D Surface Subdivision Methods',['../packages.html#PkgSurfaceSubdivisionMethod3',1,'']]],
  ['metis_28',['METIS',['../thirdparty.html#thirdpartyMETIS',1,'']]],
  ['metis_20library_29',['METIS Library',['../configurationvariables.html#installation_metis',1,'']]],
  ['minimal_20example_20using_20qt6_30',['Minimal Example Using Qt6',['../devman_create_and_use_a_cmakelist.html#secexample',1,'']]],
  ['minkowski_20sum_20of_20polyhedra_31',['3D Minkowski Sum of Polyhedra',['../packages.html#PkgMinkowskiSum3',1,'']]],
  ['minkowski_20sums_32',['2D Minkowski Sums',['../packages.html#PkgMinkowskiSum2',1,'']]],
  ['miscellaneous_20variables_33',['Miscellaneous Variables',['../configurationvariables.html#installation_misc',1,'']]],
  ['missing_20dependencies_34',['Specifying Missing Dependencies',['../usage.html#usage_configuring_cmake_gui',1,'']]],
  ['missing_20functionality_35',['Missing functionality',['../devman_kernels.html#secNewKernelTraits',1,'']]],
  ['model_20dsm_36',['Digital Surface Model (DSM)',['../tuto_gis.html#TutorialGIS_DSM',1,'']]],
  ['model_20dtm_37',['Digital Terrain Model (DTM)',['../tuto_gis.html#TutorialGIS_DTM',1,'']]],
  ['models_38',['Concepts and Models',['../tutorial_hello_world.html#intro_concept',1,'']]],
  ['modifiers_39',['Profiling tools, Hash Map, Union-find, Modifiers',['../packages.html#Miscellany',1,'']]],
  ['modular_20arithmetic_40',['Modular Arithmetic',['../packages.html#PkgModularArithmetic',1,'']]],
  ['monotone_20and_20sorted_20matrix_20search_41',['Monotone and Sorted Matrix Search',['../packages.html#PkgMatrixSearch',1,'']]],
  ['movable_20separability_20of_20sets_42',['2D Movable Separability of Sets',['../packages.html#PkgSetMovableSeparability2',1,'']]],
  ['mpfi_43',['Multiple Precision Floating-point Interval (MPFI)',['../thirdparty.html#thirdpartyMPFI',1,'']]],
  ['mpfi_20library_44',['MPFI Library',['../configurationvariables.html#installation_mpfi',1,'']]],
  ['mpfr_45',['Installing GMP and MPFR',['../windows.html#ssect-installer-gmp-mpfr',1,'']]],
  ['mpfr_20libraries_46',['GMP and MPFR Libraries',['../configurationvariables.html#installation_gmp',1,'']]],
  ['multi_20precision_20number_20type_20library_47',['Multi Precision Number Type Library',['../thirdparty.html#thirdpartyMP',1,'']]],
  ['multiple_20builds_48',['Multiple Builds',['../installation.html#seccmakeoutofsource',1,'']]],
  ['multiple_20precision_20floating_20point_20interval_20mpfi_49',['Multiple Precision Floating-point Interval (MPFI)',['../thirdparty.html#thirdpartyMPFI',1,'']]],
  ['multithreading_50',['Multithreading',['../devman_multithreading.html',1,'dev_manual']]],
  ['mutex_51',['Mutex',['../devman_multithreading.html#Developer_manualMutex',1,'']]],
  ['my_20code_20using_20cgal_52',['Configuring and Compiling My Code Using CGAL',['../windows.html#subsect-installer-my-code',1,'']]]
];
