var searchData=
[
  ['o_20streams_0',['I/O Streams',['../packages.html#PkgStreamSupport',1,'']]],
  ['object_20generators_1',['Geometric Object Generators',['../packages.html#PkgGenerators',1,'']]],
  ['objects_2',['Geometric objects',['../devman_code_format.html#Developer_manualGeometricobjects',1,'']]],
  ['objects_20to_20the_20kernel_3',['Adding Function Objects to the Kernel',['../devman_kernels.html#secAddingFunctionObject',1,'']]],
  ['octrees_20and_20orthtrees_4',['Quadtrees, Octrees, and Orthtrees',['../packages.html#PkgOrthtree',1,'']]],
  ['of_20a_20cgal_20file_5',['Determining the license of a CGAL file',['../license.html#licensesWhere',1,'']]],
  ['of_20a_20sequence_20of_20points_6',['The Convex Hull of a Sequence of Points',['../tutorial_hello_world.html#intro_convex_hull',1,'']]],
  ['of_20a_20single_20package_7',['Running the Testsuite Locally of a Single Package',['../devman_testing.html#pkgTestsuite',1,'']]],
  ['of_20an_20example_8',['of an Example',['../windows.html#sssect-vcpkg-compilation',1,'Compilation of an Example'],['../windows.html#sssect-installer-compilation',1,'Compilation of an Example'],['../windows.html#sssec-vcpkg-configuration-example',1,'Configuring of an Example']]],
  ['of_20available_20tutorials_9',['List of Available Tutorials',['../tutorials.html#tuto_list',1,'']]],
  ['of_20cgal_10',['Identifying the Version of CGAL',['../preliminaries.html#seccgal_version',1,'']]],
  ['of_20cgal_20s_20configuration_20variables_11',['of CGAL s Configuration Variables',['../configurationvariables.html',1,'Summary of CGAL&apos;s Configuration Variables'],['../configurationvariables.html#installation_summary',1,'Summary of CGAL&apos;s Configuration Variables']]],
  ['of_20checks_12',['Categories of checks',['../devman_checks.html#secchecks_categories',1,'']]],
  ['of_20curves_13',['2D Intersection of Curves',['../packages.html#PkgSurfaceSweep2',1,'']]],
  ['of_20dd_20iso_20oriented_20boxes_14',['Intersecting Sequences of dD Iso-oriented Boxes',['../packages.html#PkgBoxIntersectionD',1,'']]],
  ['of_20disks_15',['2D Apollonius Graphs (Delaunay Graphs of Disks)',['../packages.html#PkgApolloniusGraph2',1,'']]],
  ['of_20local_20differential_20properties_20of_20point_20sampled_20surfaces_16',['Estimation of Local Differential Properties of Point-Sampled Surfaces',['../packages.html#PkgJetFitting3',1,'']]],
  ['of_20point_20sampled_20surfaces_17',['Estimation of Local Differential Properties of Point-Sampled Surfaces',['../packages.html#PkgJetFitting3',1,'']]],
  ['of_20points_18',['The Convex Hull of a Sequence of Points',['../tutorial_hello_world.html#intro_convex_hull',1,'']]],
  ['of_20points_20in_20a_20built_20in_20array_19',['The Convex Hull of Points in a Built-in Array',['../tutorial_hello_world.html#intro_array',1,'']]],
  ['of_20points_20in_20a_20vector_20',['The Convex Hull of Points in a Vector',['../tutorial_hello_world.html#intro_vector',1,'']]],
  ['of_20polyhedra_21',['of Polyhedra',['../packages.html#PkgMinkowskiSum3',1,'3D Minkowski Sum of Polyhedra'],['../packages.html#PkgConvexDecomposition3',1,'Convex Decomposition of Polyhedra']]],
  ['of_20predicates_20and_20constructions_22',['The role of predicates and constructions',['../devman_robustness.html#Developer_manualTheroleofpredicatesandconstructions',1,'']]],
  ['of_20ridges_20and_20umbilics_20on_20triangulated_20surface_20meshes_23',['Approximation of Ridges and Umbilics on Triangulated Surface Meshes',['../packages.html#PkgRidges3',1,'']]],
  ['of_20sets_24',['2D Movable Separability of Sets',['../packages.html#PkgSetMovableSeparability2',1,'']]],
  ['of_20special_20functionality_25',['Marking of Special Functionality',['../manual.html#markingSpecialFunctionality',1,'']]],
  ['of_20streamlines_26',['2D Placement of Streamlines',['../packages.html#PkgStreamLines2',1,'']]],
  ['of_20the_20license_20choice_27',['Rationale of the License Choice',['../license.html#licensesRationale',1,'']]],
  ['of_20the_20manual_28',['of the Manual',['../manual.html',1,'Organization of the Manual'],['../manual.html#secorganization',1,'Organization of the Manual']]],
  ['of_20the_20reference_20manual_29',['Organization of the Reference Manual',['../manual.html#secorganizationref',1,'']]],
  ['of_20use_30',['Ease of Use',['../devman_intro.html#Developer_manualEaseofUse',1,'']]],
  ['of_20variables_31',['Examining the values of variables',['../devman_debugging.html#secdebugging_handles_and_it',1,'']]],
  ['offsetting_32',['2D Straight Skeleton and Polygon Offsetting',['../packages.html#PkgStraightSkeleton2',1,'']]],
  ['on_20global_20template_20functions_33',['Note on global template functions',['../devman_namespaces.html#Developer_manualNoteonglobaltemplatefunctions',1,'']]],
  ['on_20hyperbolic_20surfaces_34',['2D Triangulations on Hyperbolic Surfaces',['../packages.html#PkgHyperbolicSurfaceTriangulation2',1,'']]],
  ['on_20nef_20polygons_35',['2D Boolean Operations on Nef Polygons',['../packages.html#PkgNef2',1,'']]],
  ['on_20nef_20polygons_20embedded_20on_20the_20sphere_36',['2D Boolean Operations on Nef Polygons Embedded on the Sphere',['../packages.html#PkgNefS2',1,'']]],
  ['on_20nef_20polyhedra_37',['3D Boolean Operations on Nef Polyhedra',['../packages.html#PkgNef3',1,'']]],
  ['on_20the_20sphere_38',['on the Sphere',['../packages.html#PkgNefS2',1,'2D Boolean Operations on Nef Polygons Embedded on the Sphere'],['../packages.html#PkgTriangulationOnSphere2',1,'2D Triangulations on the Sphere']]],
  ['on_20triangulated_20surface_20meshes_39',['Approximation of Ridges and Umbilics on Triangulated Surface Meshes',['../packages.html#PkgRidges3',1,'']]],
  ['on_20unix_20linux_20macos_40',['Using CGAL on Unix (Linux, macOS, ...)',['../usage.html',1,'general_intro']]],
  ['on_20windows_20with_20visual_20c_41',['Using CGAL on Windows (with Visual C++)',['../windows.html',1,'general_intro']]],
  ['one_20segment_42',['Three Points and One Segment',['../tutorial_hello_world.html#intro_Three',1,'']]],
  ['onetbb_43',['OneTBB',['../configurationvariables.html#installation_new_tbb',1,'']]],
  ['only_20usage_44',['Header-only Usage',['../usage.html#section_headeronly',1,'']]],
  ['only_20when_20building_20programs_20such_20as_20demos_20or_20examples_45',['Variables Used Only When Building Programs (Such as Demos or Examples)',['../configurationvariables.html#installation_variables_building',1,'']]],
  ['opencv_46',['OpenCV',['../thirdparty.html#thirdpartyOpenCV',1,'']]],
  ['opencv_20library_47',['OpenCV library',['../configurationvariables.html#installation_OpenCV',1,'']]],
  ['opengr_48',['OpenGR',['../thirdparty.html#thirdpartyOpenGR',1,'']]],
  ['operations_49',['2D Regularized Boolean Set-Operations',['../packages.html#PkgBooleanSetOperations2',1,'']]],
  ['operations_20on_20nef_20polygons_50',['2D Boolean Operations on Nef Polygons',['../packages.html#PkgNef2',1,'']]],
  ['operations_20on_20nef_20polygons_20embedded_20on_20the_20sphere_51',['2D Boolean Operations on Nef Polygons Embedded on the Sphere',['../packages.html#PkgNefS2',1,'']]],
  ['operations_20on_20nef_20polyhedra_52',['3D Boolean Operations on Nef Polyhedra',['../packages.html#PkgNef3',1,'']]],
  ['optimal_20bounding_20box_53',['Optimal Bounding Box',['../packages.html#PkgOptimalBoundingBox',1,'']]],
  ['optimal_20distances_54',['Optimal Distances',['../packages.html#PkgPolytopeDistanceD',1,'']]],
  ['optimal_20transportation_20curve_20reconstruction_55',['Optimal Transportation Curve Reconstruction',['../packages.html#PkgOptimalTransportationReconstruction2',1,'']]],
  ['optimization_56',['Geometric Optimization',['../packages.html#PartGeometricOptimization',1,'']]],
  ['optional_20third_20party_20libraries_57',['Optional Third Party Libraries',['../thirdparty.html#secoptional3rdpartysoftware',1,'']]],
  ['options_58',['Advanced Configuration Options',['../usage.html#usage_configuring_advanced_cmake',1,'']]],
  ['or_20before_59',['TBB 2020 or before',['../configurationvariables.html#installation_old_tbb',1,'']]],
  ['or_20circulator_60',['Handle, iterator, or circulator?',['../devman_iterators_and_circulators.html#sechandle_vs_it_vs_circ',1,'']]],
  ['or_20examples_61',['Variables Used Only When Building Programs (Such as Demos or Examples)',['../configurationvariables.html#installation_variables_building',1,'']]],
  ['or_20gmp_20support_62',['Checking for LEDA or GMP support',['../devman_portability.html#secleda_gmp_support',1,'']]],
  ['organization_20of_20the_20manual_63',['Organization of the Manual',['../manual.html',1,'Organization of the Manual'],['../manual.html#secorganization',1,'Organization of the Manual']]],
  ['organization_20of_20the_20reference_20manual_64',['Organization of the Reference Manual',['../manual.html#secorganizationref',1,'']]],
  ['orientation_65',['Normal Estimation and Orientation',['../tuto_reconstruction.html#TutorialsReconstruction_preprocessing_normal',1,'']]],
  ['oriented_20boxes_66',['Intersecting Sequences of dD Iso-oriented Boxes',['../packages.html#PkgBoxIntersectionD',1,'']]],
  ['orthtrees_67',['Quadtrees, Octrees, and Orthtrees',['../packages.html#PkgOrthtree',1,'']]],
  ['osqp_68',['OSQP',['../thirdparty.html#thirdpartyOSQP',1,'']]],
  ['other_20cmake_20variables_69',['Other CMake Variables',['../installation.html#installation_miscvariables',1,'']]],
  ['other_20problems_20and_20solutions_70',['Various other problems and solutions',['../devman_portability.html#secvarious_problems',1,'']]],
  ['outlier_20removal_71',['Outlier removal',['../tuto_reconstruction.html#TutorialsReconstruction_preprocessing_outliers',1,'']]],
  ['output_20and_20postprocessing_72',['Output and Postprocessing',['../tuto_reconstruction.html#TutorialsReconstruction_postprocessing',1,'']]],
  ['output_20iterators_73',['Input and output iterators',['../devman_iterators_and_circulators.html#secinput_and_output_iterators',1,'']]],
  ['overall_20design_74',['The overall design',['../devman_intro.html#secoverall_design',1,'']]],
  ['overview_75',['Overview',['../packages.html',1,'Package Overview'],['../tuto_reconstruction.html#TutorialsReconstruction_overview',1,'Pipeline Overview']]]
];
