var searchData=
[
  ['c_0',['Using CGAL on Windows (with Visual C++)',['../windows.html',1,'general_intro']]],
  ['c_2017_20support_1',['C++17 Support',['../preliminaries.html#Preliminaries_cc0x',1,'']]],
  ['cartesian_20versus_20homogeneous_20computation_2',['Cartesian versus homogeneous computation',['../devman_kernels.html#secCartesianHomogeneousComputation',1,'']]],
  ['categories_20of_20checks_3',['Categories of checks',['../devman_checks.html#secchecks_categories',1,'']]],
  ['cell_20complex_4',['Linear Cell Complex',['../packages.html#PkgLinearCellComplex',1,'']]],
  ['cell_20complexes_20and_20polyhedra_5',['Cell Complexes and Polyhedra',['../packages.html#PartPolyhedra',1,'']]],
  ['ceres_20solver_6',['Ceres Solver',['../thirdparty.html#thirdpartyCeres',1,'']]],
  ['cgal_7',['CGAL',['../how_to_cite_cgal.html',1,'Acknowledging CGAL'],['../installation.html#installation_buildprogram',1,'Building a Program using CGAL'],['../windows.html#subsect-installer-my-code',1,'Configuring and Compiling My Code Using CGAL'],['../windows.html#subsect-vpckg-my-code',1,'Configuring and Compiling Your Code Using CGAL'],['../devman_create_cgal_CMakeLists.html',1,'Creating a CMake Script for a Program Using CGAL'],['../usage.html#secgettingcgal',1,'Downloading CGAL'],['../Doxygen_for_CGAL.html',1,'Doxygen for CGAL'],['../general_intro.html',1,'Getting Started with CGAL'],['../preliminaries.html#seccgal_version',1,'Identifying the Version of CGAL'],['../installation.html#secinstalling',1,'Installing CGAL'],['../devman_create_and_use_a_cmakelist.html#seclink',1,'Linking with CGAL'],['../devman_namespaces.html#Developer_manualNamespaceCGAL',1,'Namespace CGAL'],['../preliminaries.html#Preliminaries_namespace',1,'Namespace CGAL'],['../usage.html#usage_introduction',1,'Quick Start: Compiling a Program using CGAL'],['../packages.html#PkgSTLExtension',1,'STL Extensions for CGAL'],['../devman_traits_classes.html#secwhat_is_a_traits_class',1,'What are traits classes in CGAL?'],['../devman_traits_classes.html#secwhy_traits_classes',1,'Why are traits classes in CGAL?']]],
  ['cgal_206_201_203_20manual_8',['CGAL 6.1.3 - Manual',['../index.html',1,'']]],
  ['cgal_20algorithms_20using_20a_20precompiled_20demo_9',['Trying CGAL algorithms using a Precompiled Demo',['../windows.html#sec-win-demo',1,'']]],
  ['cgal_20and_20boost_20property_20maps_10',['CGAL and Boost Property Maps',['../packages.html#PkgPropertyMap',1,'']]],
  ['cgal_20and_20solvers_11',['CGAL and Solvers',['../packages.html#PkgSolverInterface',1,'']]],
  ['cgal_20and_20the_20boost_20graph_20library_12',['CGAL and the Boost Graph Library',['../packages.html#PkgBGL',1,'']]],
  ['cgal_20and_20the_20qt_20graphics_20view_20framework_13',['CGAL and the Qt Graphics View Framework',['../packages.html#PkgGraphicsView',1,'']]],
  ['cgal_20examples_20and_20demos_14',['CGAL Examples and Demos',['../installation.html#installation_examples',1,'']]],
  ['cgal_20file_15',['Determining the license of a CGAL file',['../license.html#licensesWhere',1,'']]],
  ['cgal_20ipelets_16',['CGAL Ipelets',['../packages.html#PkgCGALIpelets',1,'']]],
  ['cgal_20libraries_17',['CGAL Libraries',['../installation.html#seclibraries',1,'']]],
  ['cgal_20libraries_18',['Installing CGAL libraries',['../installation.html',1,'general_intro']]],
  ['cgal_20named_20function_20parameters_19',['Upgrading Code using Boost Parameters to CGAL Named Function Parameters',['../../STL_Extension/FromBoostNPtoCGALNP.html',1,'']]],
  ['cgal_20on_20unix_20linux_20macos_20',['Using CGAL on Unix (Linux, macOS, ...)',['../usage.html',1,'general_intro']]],
  ['cgal_20on_20windows_20with_20visual_20c_21',['Using CGAL on Windows (with Visual C++)',['../windows.html',1,'general_intro']]],
  ['cgal_20provided_20traits_20classes_22',['CGAL-provided traits classes',['../devman_traits_classes.html#subseccgal_traits_classes',1,'']]],
  ['cgal_20s_20configuration_20variables_23',['CGAL s Configuration Variables',['../configurationvariables.html',1,'Summary of CGAL&apos;s Configuration Variables'],['../configurationvariables.html#installation_summary',1,'Summary of CGAL&apos;s Configuration Variables']]],
  ['cgal_20source_20archive_24',['Using CGAL Source Archive',['../usage.html#secusingwebsite',1,'']]],
  ['cgal_20with_20cmake_25',['CGAL with CMake',['../installation.html#installation_configwithcmake',1,'Configuring CGAL with CMake'],['../devman_create_and_use_a_cmakelist.html',1,'How to use CGAL with CMake']]],
  ['cgal_20with_20the_20cmake_20command_20line_20tool_26',['Configuring CGAL with the cmake Command-Line Tool',['../installation.html#installation_configuring_cmd',1,'']]],
  ['cgal_20with_20the_20cmake_20gui_27',['Configuring CGAL with the CMake GUI',['../installation.html#installation_configuring_gui',1,'']]],
  ['cgal_20with_20the_20vcpkg_20library_20manager_28',['Installing CGAL with the Vcpkg Library Manager',['../windows.html#sec-installing-with-vcpkg',1,'']]],
  ['cgal_20with_20vcpkg_29',['Installing CGAL with Vcpkg',['../windows.html#ssec-vcpk-install-cgal',1,'']]],
  ['cgal_5fassume_30',['Suppress warnings using CGAL_assume.',['../devman_checks.html#secchecks_cgal_assume',1,'']]],
  ['cgalconfig_20cmake_31',['CGALConfig.cmake',['../installation.html#installation_cgalconfig',1,'']]],
  ['checker_32',['An example: Traits class binary cross-checker',['../devman_debugging.html#Developer_manualAnexampleTraitsclassbinary',1,'']]],
  ['checkers_33',['Cross-checkers',['../devman_debugging.html#secdebugging_cross_checker',1,'']]],
  ['checking_34',['License Checking',['../license.html#licenseCheck',1,'']]],
  ['checking_20for_20leda_20or_20gmp_20support_35',['Checking for LEDA or GMP support',['../devman_portability.html#secleda_gmp_support',1,'']]],
  ['checks_36',['Checks',['../preliminaries.html#preliminaries_secchecks',1,'']]],
  ['checks_37',['checks',['../devman_checks.html#secchecks_categories',1,'Categories of checks'],['../devman_checks.html#secchecks_using',1,'Using checks']]],
  ['checks_20at_20a_20finer_20granularity_38',['Controlling checks at a finer granularity',['../devman_checks.html#secchecks_controlling',1,'']]],
  ['checks_3a_20pre_20and_20postconditions_20assertions_20and_20warnings_39',['Checks: Pre- and Postconditions, Assertions, and Warnings',['../devman_checks.html',1,'dev_manual']]],
  ['choice_40',['Rationale of the License Choice',['../license.html#licensesRationale',1,'']]],
  ['circular_20geometry_20kernel_41',['2D Circular Geometry Kernel',['../packages.html#PkgCircularKernel2',1,'']]],
  ['circulator_42',['Handle, iterator, or circulator?',['../devman_iterators_and_circulators.html#sechandle_vs_it_vs_circ',1,'']]],
  ['circulator_20for_20your_20container_43',['Writing a circulator for your container',['../devman_iterators_and_circulators.html#secclass_circulator',1,'']]],
  ['circulator_20traits_44',['Iterator and circulator traits',['../devman_iterators_and_circulators.html#seciterator_traits',1,'']]],
  ['circulators_45',['Handles and Circulators',['../packages.html#PkgHandlesAndCirculators',1,'']]],
  ['circulators_46',['Writing functions for iterators AND circulators',['../devman_iterators_and_circulators.html#secit_and_circ_code',1,'']]],
  ['circulators_20and_20handles_47',['Iterators, Circulators and Handles',['../devman_iterators_and_circulators.html',1,'dev_manual']]],
  ['circulators_20and_20handles_48',['Writing code with and for iterators, circulators, and handles',['../devman_iterators_and_circulators.html#Developer_manualWritingcodewithandforiterators',1,'']]],
  ['class_20binary_20cross_20checker_49',['An example: Traits class binary cross-checker',['../devman_debugging.html#Developer_manualAnexampleTraitsclassbinary',1,'']]],
  ['class_20requirements_50',['Traits class requirements',['../devman_traits_classes.html#subsectraits_class_requirements',1,'']]],
  ['classes_51',['Classes',['../tutorial_hello_world.html#intro_traits',1,'About Kernels and Traits Classes'],['../devman_traits_classes.html',1,'Traits Classes']]],
  ['classes_52',['CGAL-provided traits classes',['../devman_traits_classes.html#subseccgal_traits_classes',1,'']]],
  ['classes_20in_20cgal_53',['classes in CGAL',['../devman_traits_classes.html#secwhat_is_a_traits_class',1,'What are traits classes in CGAL?'],['../devman_traits_classes.html#secwhy_traits_classes',1,'Why are traits classes in CGAL?']]],
  ['classification_54',['Classification',['../packages.html#PkgClassification',1,'']]],
  ['classified_20reference_20pages_55',['Classified Reference Pages',['../../Algebraic_foundations/AlgebraicFoundationsClassified.html',1,'']]],
  ['classifying_56',['Classifying',['../tuto_gis.html#TutorialGIS_Classify',1,'']]],
  ['clouds_57',['Surface Reconstruction from Point Clouds',['../tuto_reconstruction.html',1,'tutorials']]],
  ['cmake_58',['CMake',['../thirdparty.html#seccmake',1,'CMake'],['../installation.html#installation_configwithcmake',1,'Configuring CGAL with CMake'],['../devman_create_and_use_a_cmakelist.html',1,'How to use CGAL with CMake']]],
  ['cmake_59',['CGALConfig.cmake',['../installation.html#installation_cgalconfig',1,'']]],
  ['cmake_20command_20line_20tool_60',['Configuring CGAL with the cmake Command-Line Tool',['../installation.html#installation_configuring_cmd',1,'']]],
  ['cmake_20gui_61',['Configuring CGAL with the CMake GUI',['../installation.html#installation_configuring_gui',1,'']]],
  ['cmake_20script_20for_20a_20program_20using_20cgal_62',['Creating a CMake Script for a Program Using CGAL',['../devman_create_cgal_CMakeLists.html',1,'dev_manual']]],
  ['cmake_20variables_63',['Other CMake Variables',['../installation.html#installation_miscvariables',1,'']]],
  ['cmakelists_20txt_64',['CMakeLists.txt',['../devman_create_and_use_a_cmakelist.html#subcmake',1,'']]],
  ['code_65',['Code',['../manual.html#deprecated_code',1,'Deprecated Code'],['../deprecated.html#_deprecated000001',1,'Deprecated Code']]],
  ['code_20example_66',['Code Example',['../tuto_gis.html#TutorialGIS_Code',1,'Full Code Example'],['../tuto_reconstruction.html#TutorialsReconstruction_recap',1,'Full Code Example']]],
  ['code_20format_67',['Code format',['../devman_code_format.html#seccode_format',1,'']]],
  ['code_20using_20boost_20parameters_20to_20cgal_20named_20function_20parameters_68',['Upgrading Code using Boost Parameters to CGAL Named Function Parameters',['../../STL_Extension/FromBoostNPtoCGALNP.html',1,'']]],
  ['code_20using_20cgal_69',['Code Using CGAL',['../windows.html#subsect-installer-my-code',1,'Configuring and Compiling My Code Using CGAL'],['../windows.html#subsect-vpckg-my-code',1,'Configuring and Compiling Your Code Using CGAL']]],
  ['code_20with_20and_20for_20iterators_20circulators_20and_20handles_70',['Writing code with and for iterators, circulators, and handles',['../devman_iterators_and_circulators.html#Developer_manualWritingcodewithandforiterators',1,'']]],
  ['coding_20conventions_71',['Coding Conventions',['../devman_code_format.html',1,'dev_manual']]],
  ['combinatorial_20algorithms_72',['Combinatorial Algorithms',['../packages.html#PartCombinatorialAlgorithms',1,'']]],
  ['combinatorial_20maps_73',['Combinatorial Maps',['../packages.html#PkgCombinatorialMaps',1,'']]],
  ['command_20line_20tool_74',['Configuring CGAL with the cmake Command-Line Tool',['../installation.html#installation_configuring_cmd',1,'']]],
  ['commercial_20licenses_75',['Commercial Licenses',['../license.html#licensesCommercial',1,'']]],
  ['compilation_20of_20an_20example_76',['Compilation of an Example',['../windows.html#sssect-vcpkg-compilation',1,'Compilation of an Example'],['../windows.html#sssect-installer-compilation',1,'Compilation of an Example']]],
  ['compile_20time_20flags_20to_20control_20inlining_77',['Compile-time Flags to Control Inlining',['../preliminaries.html#Preliminaries_flags',1,'']]],
  ['compiler_20and_20linker_20flags_78',['Compiler and Linker Flags',['../configurationvariables.html#installation_additional_flags',1,'Additional Compiler and Linker Flags'],['../configurationvariables.html#installation_flags',1,'Compiler and Linker Flags']]],
  ['compiler_20workarounds_79',['Compiler Workarounds',['../configurationvariables.html#installation_compiler_workarounds',1,'']]],
  ['compilers_80',['Supported Compilers',['../thirdparty.html#seccompilers',1,'']]],
  ['compilers_81',['Macros connected to workarounds/compilers',['../devman_portability.html#secworkaround_macros',1,'']]],
  ['compilers_20and_20architectures_82',['Identifying compilers and architectures',['../devman_portability.html#secwhich_compiler',1,'']]],
  ['compilers_20and_20third_20party_20dependencies_83',['Compilers and Third Party Dependencies',['../thirdparty.html',1,'general_intro']]],
  ['compiling_20a_20program_20using_20cgal_84',['Quick Start: Compiling a Program using CGAL',['../usage.html#usage_introduction',1,'']]],
  ['compiling_20an_20example_85',['Compiling an Example',['../windows.html#ssec-vcpkg-compile-example',1,'Compiling an Example'],['../windows.html#ssect-installer-compile-example',1,'Compiling an Example']]],
  ['compiling_20my_20code_20using_20cgal_86',['Configuring and Compiling My Code Using CGAL',['../windows.html#subsect-installer-my-code',1,'']]],
  ['compiling_20your_20code_20using_20cgal_87',['Configuring and Compiling Your Code Using CGAL',['../windows.html#subsect-vpckg-my-code',1,'']]],
  ['complex_88',['Linear Cell Complex',['../packages.html#PkgLinearCellComplex',1,'']]],
  ['complexes_20and_20polyhedra_89',['Cell Complexes and Polyhedra',['../packages.html#PartPolyhedra',1,'']]],
  ['component_20analysis_90',['Principal Component Analysis',['../packages.html#PkgPrincipalComponentAnalysisD',1,'']]],
  ['component_20selection_91',['Component Selection',['../configurationvariables.html#installation_component_selection',1,'']]],
  ['components_92',['Identifying Connected Components',['../tuto_gis.html#TutorialGIS_DTM_components',1,'']]],
  ['computation_93',['Computation',['../packages.html#PkgAABBTree',1,'2D and 3D Fast Intersection and Distance Computation'],['../packages.html#PkgVisibility2',1,'2D Visibility Computation']]],
  ['computation_94',['Cartesian versus homogeneous computation',['../devman_kernels.html#secCartesianHomogeneousComputation',1,'']]],
  ['concepts_20and_20models_95',['Concepts and Models',['../tutorial_hello_world.html#intro_concept',1,'']]],
  ['cone_20based_20spanners_96',['Cone-Based Spanners',['../packages.html#PkgConeSpanners2',1,'']]],
  ['configuration_20macros_20and_20flags_97',['Using the version-number and configuration macros and flags',['../devman_portability.html#secusing_version_macros',1,'']]],
  ['configuration_20options_98',['Advanced Configuration Options',['../usage.html#usage_configuring_advanced_cmake',1,'']]],
  ['configuration_20variables_99',['Configuration Variables',['../configurationvariables.html',1,'Summary of CGAL&apos;s Configuration Variables'],['../configurationvariables.html#installation_summary',1,'Summary of CGAL&apos;s Configuration Variables']]],
  ['configuring_20an_20external_20program_100',['Configuring an External Program',['../usage.html#usage_configuring_external',1,'']]],
  ['configuring_20and_20compiling_20my_20code_20using_20cgal_101',['Configuring and Compiling My Code Using CGAL',['../windows.html#subsect-installer-my-code',1,'']]],
  ['configuring_20and_20compiling_20your_20code_20using_20cgal_102',['Configuring and Compiling Your Code Using CGAL',['../windows.html#subsect-vpckg-my-code',1,'']]],
  ['configuring_20cgal_20with_20cmake_103',['Configuring CGAL with CMake',['../installation.html#installation_configwithcmake',1,'']]],
  ['configuring_20cgal_20with_20the_20cmake_20command_20line_20tool_104',['Configuring CGAL with the cmake Command-Line Tool',['../installation.html#installation_configuring_cmd',1,'']]],
  ['configuring_20cgal_20with_20the_20cmake_20gui_105',['Configuring CGAL with the CMake GUI',['../installation.html#installation_configuring_gui',1,'']]],
  ['configuring_20of_20an_20example_106',['Configuring of an Example',['../windows.html#sssec-vcpkg-configuration-example',1,'']]],
  ['configuring_20your_20program_107',['Configuring your Program',['../usage.html#usage_configuring',1,'']]],
  ['conforming_20triangulations_20and_20meshes_108',['2D Conforming Triangulations and Meshes',['../packages.html#PkgMesh2',1,'']]],
  ['connected_20components_109',['Identifying Connected Components',['../tuto_gis.html#TutorialGIS_DTM_components',1,'']]],
  ['connected_20to_20workarounds_20compilers_110',['Macros connected to workarounds/compilers',['../devman_portability.html#secworkaround_macros',1,'']]],
  ['constrained_20triangulations_111',['3D Constrained Triangulations',['../packages.html#PkgConstrainedTriangulation3',1,'']]],
  ['constructions_112',['The role of predicates and constructions',['../devman_robustness.html#Developer_manualTheroleofpredicatesandconstructions',1,'']]],
  ['container_113',['container',['../devman_iterators_and_circulators.html#secclass_circulator',1,'Writing a circulator for your container'],['../devman_iterators_and_circulators.html#secclass_iterator',1,'Writing an iterator for your container']]],
  ['contour_20graph_114',['Building a Contour Graph',['../tuto_gis.html#TutorialGIS_Contour_Extraction',1,'']]],
  ['contouring_115',['Contouring',['../tuto_gis.html#TutorialGIS_Contour',1,'']]],
  ['control_20inlining_116',['Compile-time Flags to Control Inlining',['../preliminaries.html#Preliminaries_flags',1,'']]],
  ['controlling_20checks_20at_20a_20finer_20granularity_117',['Controlling checks at a finer granularity',['../devman_checks.html#secchecks_controlling',1,'']]],
  ['conventions_118',['Coding Conventions',['../devman_code_format.html',1,'dev_manual']]],
  ['conventions_119',['conventions',['../devman_kernels.html#Developer_manualKerneldesignandconventions',1,'Kernel design and conventions'],['../devman_code_format.html#secprogramming_conventions',1,'Programming conventions']]],
  ['convex_20decomposition_20of_20polyhedra_120',['Convex Decomposition of Polyhedra',['../packages.html#PkgConvexDecomposition3',1,'']]],
  ['convex_20hull_20algorithms_121',['Convex Hull Algorithms',['../packages.html#PartConvexHullAlgorithms',1,'']]],
  ['convex_20hull_20of_20a_20sequence_20of_20points_122',['The Convex Hull of a Sequence of Points',['../tutorial_hello_world.html#intro_convex_hull',1,'']]],
  ['convex_20hull_20of_20points_20in_20a_20built_20in_20array_123',['The Convex Hull of Points in a Built-in Array',['../tutorial_hello_world.html#intro_array',1,'']]],
  ['convex_20hull_20of_20points_20in_20a_20vector_124',['The Convex Hull of Points in a Vector',['../tutorial_hello_world.html#intro_vector',1,'']]],
  ['convex_20hulls_125',['3D Convex Hulls',['../packages.html#PkgConvexHull3',1,'']]],
  ['convex_20hulls_126',['An example - planar convex hulls',['../devman_traits_classes.html#sectraits_class_example',1,'']]],
  ['convex_20hulls_20and_20delaunay_20triangulations_127',['dD Convex Hulls and Delaunay Triangulations',['../packages.html#PkgConvexHullD',1,'']]],
  ['convex_20hulls_20and_20extreme_20points_128',['2D Convex Hulls and Extreme Points',['../packages.html#PkgConvexHull2',1,'']]],
  ['coordinates_129',['2D Generalized Barycentric Coordinates',['../packages.html#PkgBarycentricCoordinates2',1,'']]],
  ['correctness_130',['Correctness',['../devman_intro.html#Developer_manualCorrectness',1,'']]],
  ['counting_131',['Reference counting',['../devman_reference_counting.html#Developer_manualReferencecounting',1,'']]],
  ['counting_20and_20handle_20types_132',['Reference Counting and Handle Types',['../devman_reference_counting.html',1,'dev_manual']]],
  ['cpp_133',['draw_surface_mesh.cpp',['../devman_create_and_use_a_cmakelist.html#subexcpp',1,'']]],
  ['creating_20a_20cmake_20script_20for_20a_20program_20using_20cgal_134',['Creating a CMake Script for a Program Using CGAL',['../devman_create_cgal_CMakeLists.html',1,'dev_manual']]],
  ['cross_20checker_135',['An example: Traits class binary cross-checker',['../devman_debugging.html#Developer_manualAnexampleTraitsclassbinary',1,'']]],
  ['cross_20checkers_136',['Cross-checkers',['../devman_debugging.html#secdebugging_cross_checker',1,'']]],
  ['curve_20reconstruction_137',['Optimal Transportation Curve Reconstruction',['../packages.html#PkgOptimalTransportationReconstruction2',1,'']]],
  ['curves_138',['2D Intersection of Curves',['../packages.html#PkgSurfaceSweep2',1,'']]]
];
