var searchData=
[
  ['s_20configuration_20variables_0',['s Configuration Variables',['../configurationvariables.html',1,'Summary of CGAL&apos;s Configuration Variables'],['../configurationvariables.html#installation_summary',1,'Summary of CGAL&apos;s Configuration Variables']]],
  ['safety_1',['Thread Safety',['../preliminaries.html#Preliminaries_thread_safety',1,'']]],
  ['sampled_20surfaces_2',['Estimation of Local Differential Properties of Point-Sampled Surfaces',['../packages.html#PkgJetFitting3',1,'']]],
  ['scale_20space_3',['Scale Space',['../tuto_reconstruction.html#TutorialsReconstruction_reconstruction_scale_space',1,'']]],
  ['scale_20space_20surface_20reconstruction_4',['Scale-Space Surface Reconstruction',['../packages.html#PkgScaleSpaceReconstruction3',1,'']]],
  ['scheme_5',['Naming scheme',['../devman_code_format.html#secnaming_scheme',1,'']]],
  ['scip_6',['SCIP',['../thirdparty.html#thirdpartySCIP',1,'']]],
  ['scip_20library_7',['SCIP library',['../configurationvariables.html#installation_SCIP',1,'']]],
  ['script_20for_20a_20program_20using_20cgal_8',['Creating a CMake Script for a Program Using CGAL',['../devman_create_cgal_CMakeLists.html',1,'dev_manual']]],
  ['search_9',['Search',['../packages.html#PkgPointSet2',1,'2D Range and Neighbor Search'],['../packages.html#PkgMatrixSearch',1,'Monotone and Sorted Matrix Search']]],
  ['searching_10',['dD Spatial Searching',['../packages.html#PkgSpatialSearchingD',1,'']]],
  ['searching_20and_20sorting_11',['Spatial Searching and Sorting',['../packages.html#PartSearchStructures',1,'']]],
  ['segment_12',['Three Points and One Segment',['../tutorial_hello_world.html#intro_Three',1,'']]],
  ['segment_20delaunay_20graphs_13',['Segment Delaunay Graphs',['../packages.html#PkgSegmentDelaunayGraph2',1,'2D Segment Delaunay Graphs'],['../packages.html#PkgSegmentDelaunayGraphLinf2',1,'L Infinity Segment Delaunay Graphs']]],
  ['segment_20trees_14',['dD Range and Segment Trees',['../packages.html#PkgSearchStructures',1,'']]],
  ['segmentation_15',['Triangulated Surface Mesh Segmentation',['../packages.html#PkgSurfaceMeshSegmentation',1,'']]],
  ['selection_16',['Component Selection',['../configurationvariables.html#installation_component_selection',1,'']]],
  ['separability_20of_20sets_17',['2D Movable Separability of Sets',['../packages.html#PkgSetMovableSeparability2',1,'']]],
  ['sequence_20of_20points_18',['The Convex Hull of a Sequence of Points',['../tutorial_hello_world.html#intro_convex_hull',1,'']]],
  ['sequences_20of_20dd_20iso_20oriented_20boxes_19',['Intersecting Sequences of dD Iso-oriented Boxes',['../packages.html#PkgBoxIntersectionD',1,'']]],
  ['set_20',['3D Point Set',['../packages.html#PkgPointSet3',1,'']]],
  ['set_20operations_21',['2D Regularized Boolean Set-Operations',['../packages.html#PkgBooleanSetOperations2',1,'']]],
  ['set_20processing_22',['Point Set Processing',['../packages.html#PkgPointSetProcessing3',1,'']]],
  ['sets_23',['2D Movable Separability of Sets',['../packages.html#PkgSetMovableSeparability2',1,'']]],
  ['shape_20detection_24',['Shape Detection',['../packages.html#PkgShapeDetection',1,'']]],
  ['shape_20reconstruction_25',['Shape Reconstruction',['../packages.html#PartReconstruction',1,'']]],
  ['shape_20regularization_26',['Shape Regularization',['../packages.html#PkgShapeRegularization',1,'']]],
  ['shapes_27',['Shapes',['../packages.html#PkgAlphaShapes2',1,'2D Alpha Shapes'],['../packages.html#PkgAlphaShapes3',1,'3D Alpha Shapes']]],
  ['shortest_20paths_28',['Triangulated Surface Mesh Shortest Paths',['../packages.html#PkgSurfaceMeshShortestPath',1,'']]],
  ['should_20i_20use_29',['Which algorithm should I use?',['../tuto_reconstruction.html#TutorialsReconstruction_algorithms',1,'']]],
  ['simplicial_20mesh_20data_20structure_30',['3D Simplicial Mesh Data Structure',['../packages.html#PkgSMDS3',1,'']]],
  ['simplification_31',['Simplification',['../packages.html#PkgPolylineSimplification2',1,'2D Polyline Simplification'],['../tuto_reconstruction.html#TutorialsReconstruction_preprocessing_simplification',1,'Simplification'],['../packages.html#PkgSurfaceMeshSimplification',1,'Triangulated Surface Mesh Simplification']]],
  ['simplifying_32',['Simplifying',['../tuto_gis.html#TutorialGIS_Contour_Simplifying',1,'']]],
  ['single_20package_33',['Running the Testsuite Locally of a Single Package',['../devman_testing.html#pkgTestsuite',1,'']]],
  ['skeleton_20and_20polygon_20offsetting_34',['2D Straight Skeleton and Polygon Offsetting',['../packages.html#PkgStraightSkeleton2',1,'']]],
  ['skeletonization_35',['Triangulated Surface Mesh Skeletonization',['../packages.html#PkgSurfaceMeshSkeletonization',1,'']]],
  ['skin_20surface_20meshing_36',['3D Skin Surface Meshing',['../packages.html#PkgSkinSurface3',1,'']]],
  ['skip_20list_37',['Interval Skip List',['../packages.html#PkgIntervalSkipList',1,'']]],
  ['smoothing_38',['Smoothing',['../tuto_reconstruction.html#TutorialsReconstruction_preprocessing_smoothing',1,'']]],
  ['snap_20rounding_39',['2D Snap Rounding',['../packages.html#PkgSnapRounding2',1,'']]],
  ['solutions_40',['Various other problems and solutions',['../devman_portability.html#secvarious_problems',1,'']]],
  ['solver_41',['Solver',['../thirdparty.html#thirdpartyCeres',1,'Ceres Solver'],['../packages.html#PkgQPSolver',1,'Linear and Quadratic Programming Solver']]],
  ['solvers_42',['CGAL and Solvers',['../packages.html#PkgSolverInterface',1,'']]],
  ['sorted_20matrix_20search_43',['Monotone and Sorted Matrix Search',['../packages.html#PkgMatrixSearch',1,'']]],
  ['sorting_44',['Sorting',['../packages.html#PartSearchStructures',1,'Spatial Searching and Sorting'],['../packages.html#PkgSpatialSorting',1,'Spatial Sorting']]],
  ['source_20archive_45',['Source Archive',['../windows.html#install-from-source',1,'Installing from the Source Archive'],['../usage.html#secusingwebsite',1,'Using CGAL Source Archive']]],
  ['space_46',['Scale Space',['../tuto_reconstruction.html#TutorialsReconstruction_reconstruction_scale_space',1,'']]],
  ['space_20partition_47',['Kinetic Space Partition',['../packages.html#PkgKineticSpacePartition',1,'']]],
  ['space_20surface_20reconstruction_48',['Scale-Space Surface Reconstruction',['../packages.html#PkgScaleSpaceReconstruction3',1,'']]],
  ['spanners_49',['Cone-Based Spanners',['../packages.html#PkgConeSpanners2',1,'']]],
  ['spatial_20searching_50',['dD Spatial Searching',['../packages.html#PkgSpatialSearchingD',1,'']]],
  ['spatial_20searching_20and_20sorting_51',['Spatial Searching and Sorting',['../packages.html#PartSearchStructures',1,'']]],
  ['spatial_20sorting_52',['Spatial Sorting',['../packages.html#PkgSpatialSorting',1,'']]],
  ['special_20functionality_53',['Marking of Special Functionality',['../manual.html#markingSpecialFunctionality',1,'']]],
  ['specifying_20missing_20dependencies_54',['Specifying Missing Dependencies',['../usage.html#usage_configuring_cmake_gui',1,'']]],
  ['sphere_55',['Sphere',['../packages.html#PkgNefS2',1,'2D Boolean Operations on Nef Polygons Embedded on the Sphere'],['../packages.html#PkgTriangulationOnSphere2',1,'2D Triangulations on the Sphere']]],
  ['spherical_20geometry_20kernel_56',['3D Spherical Geometry Kernel',['../packages.html#PkgCircularKernel3',1,'']]],
  ['splitting_20into_20polylines_57',['Splitting Into Polylines',['../tuto_gis.html#TutorialGIS_Contour_Splitting',1,'']]],
  ['standard_20template_20library_20stl_58',['Standard Template Library (STL)',['../thirdparty.html#thirdpartystl',1,'']]],
  ['start_3a_20compiling_20a_20program_20using_20cgal_59',['Quick Start: Compiling a Program using CGAL',['../usage.html#usage_introduction',1,'']]],
  ['started_20with_20cgal_60',['Getting Started with CGAL',['../general_intro.html',1,'index']]],
  ['stl_61',['Standard Template Library (STL)',['../thirdparty.html#thirdpartystl',1,'']]],
  ['stl_20extensions_20for_20cgal_62',['STL Extensions for CGAL',['../packages.html#PkgSTLExtension',1,'']]],
  ['storage_63',['Thread Local Storage',['../devman_multithreading.html#Developer_manualThreadlocal',1,'']]],
  ['straight_20skeleton_20and_20polygon_20offsetting_64',['2D Straight Skeleton and Polygon Offsetting',['../packages.html#PkgStraightSkeleton2',1,'']]],
  ['streamlines_65',['2D Placement of Streamlines',['../packages.html#PkgStreamLines2',1,'']]],
  ['streams_66',['I/O Streams',['../packages.html#PkgStreamSupport',1,'']]],
  ['structure_67',['Structure',['../packages.html#PkgTDS2',1,'2D Triangulation Data Structure'],['../packages.html#PkgSMDS3',1,'3D Simplicial Mesh Data Structure'],['../packages.html#PkgTDS3',1,'3D Triangulation Data Structure']]],
  ['structures_68',['Halfedge Data Structures',['../packages.html#PkgHalfedgeDS',1,'']]],
  ['structures_20and_20algorithms_69',['Geometric data structures and algorithms',['../devman_code_format.html#Developer_manualGeometricdatastructuresand',1,'']]],
  ['subdivision_20methods_70',['3D Surface Subdivision Methods',['../packages.html#PkgSurfaceSubdivisionMethod3',1,'']]],
  ['such_20as_20demos_20or_20examples_71',['Variables Used Only When Building Programs (Such as Demos or Examples)',['../configurationvariables.html#installation_variables_building',1,'']]],
  ['suitesparse_72',['SuiteSparse',['../thirdparty.html#thirdpartySuiteSparse',1,'']]],
  ['sum_20of_20polyhedra_73',['3D Minkowski Sum of Polyhedra',['../packages.html#PkgMinkowskiSum3',1,'']]],
  ['summary_20of_20cgal_20s_20configuration_20variables_74',['Summary of CGAL s Configuration Variables',['../configurationvariables.html',1,'Summary of CGAL&apos;s Configuration Variables'],['../configurationvariables.html#installation_summary',1,'Summary of CGAL&apos;s Configuration Variables']]],
  ['sums_75',['2D Minkowski Sums',['../packages.html#PkgMinkowskiSum2',1,'']]],
  ['support_76',['C++17 Support',['../preliminaries.html#Preliminaries_cc0x',1,'']]],
  ['support_77',['Checking for LEDA or GMP support',['../devman_portability.html#secleda_gmp_support',1,'']]],
  ['support_20features_78',['Debugging Support Features',['../manual.html#debugging_support',1,'']]],
  ['support_20library_79',['Support Library',['../packages.html#PartSupportLibrary',1,'']]],
  ['supported_20compilers_80',['Supported Compilers',['../thirdparty.html#seccompilers',1,'']]],
  ['supported_20file_20formats_81',['Supported File Formats',['../../Stream_support/IOStreamSupportedFileFormats.html',1,'']]],
  ['suppress_20warnings_20using_20cgal_5fassume_82',['Suppress warnings using CGAL_assume.',['../devman_checks.html#secchecks_cgal_assume',1,'']]],
  ['surface_83',['3D Polyhedral Surface',['../packages.html#PkgPolyhedron',1,'']]],
  ['surface_20function_20interpolation_84',['2D and Surface Function Interpolation',['../packages.html#PkgInterpolation2',1,'']]],
  ['surface_20mesh_85',['Surface Mesh',['../packages.html#PkgSurfaceMesh',1,'']]],
  ['surface_20mesh_20approximation_86',['Triangulated Surface Mesh Approximation',['../packages.html#PkgTSMA',1,'']]],
  ['surface_20mesh_20deformation_87',['Triangulated Surface Mesh Deformation',['../packages.html#PkgSurfaceMeshDeformation',1,'']]],
  ['surface_20mesh_20generation_88',['3D Surface Mesh Generation',['../packages.html#PkgSurfaceMesher3',1,'']]],
  ['surface_20mesh_20parameterization_89',['Triangulated Surface Mesh Parameterization',['../packages.html#PkgSurfaceMeshParameterization',1,'']]],
  ['surface_20mesh_20segmentation_90',['Triangulated Surface Mesh Segmentation',['../packages.html#PkgSurfaceMeshSegmentation',1,'']]],
  ['surface_20mesh_20shortest_20paths_91',['Triangulated Surface Mesh Shortest Paths',['../packages.html#PkgSurfaceMeshShortestPath',1,'']]],
  ['surface_20mesh_20simplification_92',['Triangulated Surface Mesh Simplification',['../packages.html#PkgSurfaceMeshSimplification',1,'']]],
  ['surface_20mesh_20skeletonization_93',['Triangulated Surface Mesh Skeletonization',['../packages.html#PkgSurfaceMeshSkeletonization',1,'']]],
  ['surface_20mesh_20topology_94',['Surface Mesh Topology',['../packages.html#PkgSurfaceMeshTopology',1,'']]],
  ['surface_20meshes_95',['Approximation of Ridges and Umbilics on Triangulated Surface Meshes',['../packages.html#PkgRidges3',1,'']]],
  ['surface_20meshing_96',['3D Skin Surface Meshing',['../packages.html#PkgSkinSurface3',1,'']]],
  ['surface_20model_20dsm_97',['Digital Surface Model (DSM)',['../tuto_gis.html#TutorialGIS_DSM',1,'']]],
  ['surface_20reconstruction_98',['Surface Reconstruction',['../packages.html#PkgAdvancingFrontSurfaceReconstruction',1,'Advancing Front Surface Reconstruction'],['../packages.html#PkgKineticSurfaceReconstruction',1,'Kinetic Surface Reconstruction'],['../packages.html#PkgPoissonSurfaceReconstruction3',1,'Poisson Surface Reconstruction'],['../packages.html#PkgPolygonalSurfaceReconstruction',1,'Polygonal Surface Reconstruction'],['../packages.html#PkgScaleSpaceReconstruction3',1,'Scale-Space Surface Reconstruction']]],
  ['surface_20reconstruction_20from_20point_20clouds_99',['Surface Reconstruction from Point Clouds',['../tuto_reconstruction.html',1,'tutorials']]],
  ['surface_20subdivision_20methods_100',['3D Surface Subdivision Methods',['../packages.html#PkgSurfaceSubdivisionMethod3',1,'']]],
  ['surfaces_101',['Surfaces',['../packages.html#PkgHyperbolicSurfaceTriangulation2',1,'2D Triangulations on Hyperbolic Surfaces'],['../packages.html#PkgJetFitting3',1,'Estimation of Local Differential Properties of Point-Sampled Surfaces']]],
  ['system_102',['GIS (Geographic Information System)',['../tuto_gis.html',1,'tutorials']]]
];
