var searchData=
[
  ['general_20information_0',['General Information',['../preliminaries.html',1,'general_intro']]],
  ['general_20rules_1',['General rules',['../devman_code_format.html#Developer_manualGeneralrules',1,'']]],
  ['generalized_20barycentric_20coordinates_2',['2D Generalized Barycentric Coordinates',['../packages.html#PkgBarycentricCoordinates2',1,'']]],
  ['generalized_20maps_3',['Generalized Maps',['../packages.html#PkgGeneralizedMaps',1,'']]],
  ['generation_4',['Generation',['../packages.html#PkgMesh3',1,'3D Mesh Generation'],['../packages.html#PkgPeriodic3Mesh3',1,'3D Periodic Mesh Generation'],['../packages.html#PkgSurfaceMesher3',1,'3D Surface Mesh Generation'],['../packages.html#PartMeshing',1,'Mesh Generation']]],
  ['generators_5',['Geometric Object Generators',['../packages.html#PkgGenerators',1,'']]],
  ['geographic_20information_20system_6',['GIS (Geographic Information System)',['../tuto_gis.html',1,'tutorials']]],
  ['geometric_20data_20structures_20and_20algorithms_7',['Geometric data structures and algorithms',['../devman_code_format.html#Developer_manualGeometricdatastructuresand',1,'']]],
  ['geometric_20object_20generators_8',['Geometric Object Generators',['../packages.html#PkgGenerators',1,'']]],
  ['geometric_20objects_9',['Geometric objects',['../devman_code_format.html#Developer_manualGeometricobjects',1,'']]],
  ['geometric_20optimization_10',['Geometric Optimization',['../packages.html#PartGeometricOptimization',1,'']]],
  ['geometry_20kernel_11',['Geometry Kernel',['../packages.html#PkgKernel23',1,'2D and 3D Linear Geometry Kernel'],['../packages.html#PkgCircularKernel2',1,'2D Circular Geometry Kernel'],['../packages.html#PkgCircularKernel3',1,'3D Spherical Geometry Kernel'],['../packages.html#PkgKernelD',1,'dD Geometry Kernel']]],
  ['geometry_20kernels_12',['Geometry Kernels',['../devman_kernels.html',1,'Geometry Kernels'],['../packages.html#PartKernels',1,'Geometry Kernels']]],
  ['geometry_20processing_13',['Geometry Processing',['../packages.html#PartGeometryProcessing',1,'']]],
  ['getting_20started_20with_20cgal_14',['Getting Started with CGAL',['../general_intro.html',1,'index']]],
  ['gis_20geographic_20information_20system_15',['GIS (Geographic Information System)',['../tuto_gis.html',1,'tutorials']]],
  ['global_20template_20functions_16',['Note on global template functions',['../devman_namespaces.html#Developer_manualNoteonglobaltemplatefunctions',1,'']]],
  ['glpk_17',['GLPK',['../thirdparty.html#thirdpartyGLPK',1,'']]],
  ['glpk_20library_18',['GLPK library',['../configurationvariables.html#installation_GLPK',1,'']]],
  ['gmp_20and_20mpfr_19',['Installing GMP and MPFR',['../windows.html#ssect-installer-gmp-mpfr',1,'']]],
  ['gmp_20and_20mpfr_20libraries_20',['GMP and MPFR Libraries',['../configurationvariables.html#installation_gmp',1,'']]],
  ['gmp_20support_21',['Checking for LEDA or GMP support',['../devman_portability.html#secleda_gmp_support',1,'']]],
  ['gnu_20gpl_22',['GNU GPL',['../license.html#licensesGPL',1,'']]],
  ['gnu_20lgpl_23',['GNU LGPL',['../license.html#licensesLGPL',1,'']]],
  ['goals_24',['Primary design goals',['../devman_intro.html#secdesign_goals',1,'']]],
  ['gpl_25',['GNU GPL',['../license.html#licensesGPL',1,'']]],
  ['gpl_20version_26',['GPL version',['../devman_code_format.html#Developer_manualGPLversion',1,'']]],
  ['granularity_27',['Controlling checks at a finer granularity',['../devman_checks.html#secchecks_controlling',1,'']]],
  ['graph_28',['Building a Contour Graph',['../tuto_gis.html#TutorialGIS_Contour_Extraction',1,'']]],
  ['graph_20library_29',['CGAL and the Boost Graph Library',['../packages.html#PkgBGL',1,'']]],
  ['graphical_20debugging_30',['Graphical debugging',['../devman_debugging.html#secgraphical_debugging',1,'']]],
  ['graphics_20view_20framework_31',['CGAL and the Qt Graphics View Framework',['../packages.html#PkgGraphicsView',1,'']]],
  ['graphs_32',['Graphs',['../packages.html#PkgSegmentDelaunayGraph2',1,'2D Segment Delaunay Graphs'],['../packages.html#PkgSegmentDelaunayGraphLinf2',1,'L Infinity Segment Delaunay Graphs']]],
  ['graphs_20delaunay_20graphs_20of_20disks_33',['2D Apollonius Graphs (Delaunay Graphs of Disks)',['../packages.html#PkgApolloniusGraph2',1,'']]],
  ['graphs_20of_20disks_34',['2D Apollonius Graphs (Delaunay Graphs of Disks)',['../packages.html#PkgApolloniusGraph2',1,'']]],
  ['gui_35',['Configuring CGAL with the CMake GUI',['../installation.html#installation_configuring_gui',1,'']]]
];
