var searchData=
[
  ['package_0',['Running the Testsuite Locally of a Single Package',['../devman_testing.html#pkgTestsuite',1,'']]],
  ['package_20examples_1',['Package Examples',['../tutorials.html#tuto_examples',1,'']]],
  ['package_20manager_2',['Using a Package Manager',['../usage.html#secusingpkgman',1,'']]],
  ['package_20overview_3',['Package Overview',['../packages.html',1,'index']]],
  ['pages_4',['Classified Reference Pages',['../../Algebraic_foundations/AlgebraicFoundationsClassified.html',1,'']]],
  ['parameterization_5',['Triangulated Surface Mesh Parameterization',['../packages.html#PkgSurfaceMeshParameterization',1,'']]],
  ['parameters_6',['Upgrading Code using Boost Parameters to CGAL Named Function Parameters',['../../STL_Extension/FromBoostNPtoCGALNP.html',1,'']]],
  ['parameters_20to_20cgal_20named_20function_20parameters_7',['Upgrading Code using Boost Parameters to CGAL Named Function Parameters',['../../STL_Extension/FromBoostNPtoCGALNP.html',1,'']]],
  ['partition_8',['Kinetic Space Partition',['../packages.html#PkgKineticSpacePartition',1,'']]],
  ['partitioning_9',['2D Polygon Partitioning',['../packages.html#PkgPartition2',1,'']]],
  ['party_20dependencies_10',['Compilers and Third Party Dependencies',['../thirdparty.html',1,'general_intro']]],
  ['party_20libraries_11',['Party Libraries',['../thirdparty.html#secessential3rdpartysoftware',1,'Essential Third Party Libraries'],['../thirdparty.html#secoptional3rdpartysoftware',1,'Optional Third Party Libraries'],['../configurationvariables.html#installation_variables_third_party',1,'Variables Providing Information About 3rd-Party Libraries']]],
  ['paths_12',['Triangulated Surface Mesh Shortest Paths',['../packages.html#PkgSurfaceMeshShortestPath',1,'']]],
  ['periodic_20hyperbolic_20triangulations_13',['2D Periodic Hyperbolic Triangulations',['../packages.html#PkgPeriodic4HyperbolicTriangulation2',1,'']]],
  ['periodic_20mesh_20generation_14',['3D Periodic Mesh Generation',['../packages.html#PkgPeriodic3Mesh3',1,'']]],
  ['periodic_20triangulations_15',['Periodic Triangulations',['../packages.html#PkgPeriodic2Triangulation2',1,'2D Periodic Triangulations'],['../packages.html#PkgPeriodic3Triangulation3',1,'3D Periodic Triangulations']]],
  ['pipeline_20images_16',['Full Pipeline Images',['../tuto_reconstruction.html#TutorialsReconstruction_pipeline',1,'']]],
  ['pipeline_20overview_17',['Pipeline Overview',['../tuto_reconstruction.html#TutorialsReconstruction_overview',1,'']]],
  ['placement_20of_20streamlines_18',['2D Placement of Streamlines',['../packages.html#PkgStreamLines2',1,'']]],
  ['planar_20convex_20hulls_19',['An example - planar convex hulls',['../devman_traits_classes.html#sectraits_class_example',1,'']]],
  ['point_20clouds_20',['Surface Reconstruction from Point Clouds',['../tuto_reconstruction.html',1,'tutorials']]],
  ['point_20interval_20mpfi_21',['Multiple Precision Floating-point Interval (MPFI)',['../thirdparty.html#thirdpartyMPFI',1,'']]],
  ['point_20sampled_20surfaces_22',['Estimation of Local Differential Properties of Point-Sampled Surfaces',['../packages.html#PkgJetFitting3',1,'']]],
  ['point_20set_23',['3D Point Set',['../packages.html#PkgPointSet3',1,'']]],
  ['point_20set_20processing_24',['Point Set Processing',['../packages.html#PkgPointSetProcessing3',1,'']]],
  ['pointmatcher_25',['PointMatcher',['../thirdparty.html#thirdpartylibpointmatcher',1,'']]],
  ['points_26',['Points',['../packages.html#PkgConvexHull2',1,'2D Convex Hulls and Extreme Points'],['../tutorial_hello_world.html#intro_convex_hull',1,'The Convex Hull of a Sequence of Points']]],
  ['points_20and_20one_20segment_27',['Three Points and One Segment',['../tutorial_hello_world.html#intro_Three',1,'']]],
  ['points_20in_20a_20built_20in_20array_28',['The Convex Hull of Points in a Built-in Array',['../tutorial_hello_world.html#intro_array',1,'']]],
  ['points_20in_20a_20vector_29',['The Convex Hull of Points in a Vector',['../tutorial_hello_world.html#intro_vector',1,'']]],
  ['poisson_30',['Poisson',['../tuto_reconstruction.html#TutorialsReconstruction_reconstruction_poisson',1,'']]],
  ['poisson_20surface_20reconstruction_31',['Poisson Surface Reconstruction',['../packages.html#PkgPoissonSurfaceReconstruction3',1,'']]],
  ['polygon_20mesh_20processing_32',['Polygon Mesh Processing',['../packages.html#PkgPolygonMeshProcessing',1,'']]],
  ['polygon_20offsetting_33',['2D Straight Skeleton and Polygon Offsetting',['../packages.html#PkgStraightSkeleton2',1,'']]],
  ['polygon_20partitioning_34',['2D Polygon Partitioning',['../packages.html#PkgPartition2',1,'']]],
  ['polygon_20repair_35',['2D Polygon Repair',['../packages.html#PkgPolygonRepair',1,'']]],
  ['polygonal_20surface_20reconstruction_36',['Polygonal Surface Reconstruction',['../packages.html#PkgPolygonalSurfaceReconstruction',1,'']]],
  ['polygons_37',['Polygons',['../packages.html#PkgNef2',1,'2D Boolean Operations on Nef Polygons'],['../packages.html#PkgPolygon2',1,'2D Polygons'],['../packages.html#PartPolygons',1,'Polygons']]],
  ['polygons_20embedded_20on_20the_20sphere_38',['2D Boolean Operations on Nef Polygons Embedded on the Sphere',['../packages.html#PkgNefS2',1,'']]],
  ['polyhedra_39',['Polyhedra',['../packages.html#PkgNef3',1,'3D Boolean Operations on Nef Polyhedra'],['../packages.html#PkgMinkowskiSum3',1,'3D Minkowski Sum of Polyhedra'],['../packages.html#PartPolyhedra',1,'Cell Complexes and Polyhedra'],['../packages.html#PkgConvexDecomposition3',1,'Convex Decomposition of Polyhedra']]],
  ['polyhedral_20surface_40',['3D Polyhedral Surface',['../packages.html#PkgPolyhedron',1,'']]],
  ['polyline_20simplification_41',['2D Polyline Simplification',['../packages.html#PkgPolylineSimplification2',1,'']]],
  ['polylines_42',['Splitting Into Polylines',['../tuto_gis.html#TutorialGIS_Contour_Splitting',1,'']]],
  ['polymorphic_20return_20types_43',['Polymorphic Return Types',['../devman_polyret.html',1,'dev_manual']]],
  ['polynomial_44',['Polynomial',['../packages.html#PkgPolynomial',1,'']]],
  ['portability_20issues_45',['Portability Issues',['../devman_portability.html',1,'dev_manual']]],
  ['postconditions_20assertions_20and_20warnings_46',['Checks: Pre- and Postconditions, Assertions, and Warnings',['../devman_checks.html',1,'dev_manual']]],
  ['postprocessing_47',['Output and Postprocessing',['../tuto_reconstruction.html#TutorialsReconstruction_postprocessing',1,'']]],
  ['pre_20and_20postconditions_20assertions_20and_20warnings_48',['Checks: Pre- and Postconditions, Assertions, and Warnings',['../devman_checks.html',1,'dev_manual']]],
  ['precision_20floating_20point_20interval_20mpfi_49',['Multiple Precision Floating-point Interval (MPFI)',['../thirdparty.html#thirdpartyMPFI',1,'']]],
  ['precision_20number_20type_20library_50',['Multi Precision Number Type Library',['../thirdparty.html#thirdpartyMP',1,'']]],
  ['precompiled_20demo_51',['Trying CGAL algorithms using a Precompiled Demo',['../windows.html#sec-win-demo',1,'']]],
  ['predicates_52',['Number-type based predicates',['../devman_kernels.html#Developer_manualNumber',1,'']]],
  ['predicates_20and_20constructions_53',['The role of predicates and constructions',['../devman_robustness.html#Developer_manualTheroleofpredicatesandconstructions',1,'']]],
  ['preprocessing_54',['Preprocessing',['../tuto_reconstruction.html#TutorialsReconstruction_preprocessing',1,'']]],
  ['prerequisites_55',['Prerequisites',['../usage.html#secprerequisites',1,'']]],
  ['primary_20design_20goals_56',['Primary design goals',['../devman_intro.html#secdesign_goals',1,'']]],
  ['principal_20component_20analysis_57',['Principal Component Analysis',['../packages.html#PkgPrincipalComponentAnalysisD',1,'']]],
  ['problems_20and_20solutions_58',['Various other problems and solutions',['../devman_portability.html#secvarious_problems',1,'']]],
  ['problems_20and_20workarounds_59',['Known problems and workarounds',['../devman_portability.html#secproblems_and_workarounds',1,'']]],
  ['processing_60',['Processing',['../packages.html#PartGeometryProcessing',1,'Geometry Processing'],['../packages.html#PkgPointSetProcessing3',1,'Point Set Processing'],['../packages.html#PkgPolygonMeshProcessing',1,'Polygon Mesh Processing']]],
  ['profiling_20tools_20hash_20map_20union_20find_20modifiers_61',['Profiling tools, Hash Map, Union-find, Modifiers',['../packages.html#Miscellany',1,'']]],
  ['program_62',['Program',['../usage.html#usage_building_program',1,'Building your Program'],['../usage.html#usage_configuring_external',1,'Configuring an External Program'],['../usage.html#usage_configuring',1,'Configuring your Program']]],
  ['program_20using_20cgal_63',['Creating a CMake Script for a Program Using CGAL',['../devman_create_cgal_CMakeLists.html',1,'dev_manual']]],
  ['program_20using_20cgal_64',['Program using CGAL',['../installation.html#installation_buildprogram',1,'Building a Program using CGAL'],['../usage.html#usage_introduction',1,'Quick Start: Compiling a Program using CGAL']]],
  ['programming_20conventions_65',['Programming conventions',['../devman_code_format.html#secprogramming_conventions',1,'']]],
  ['programming_20solver_66',['Linear and Quadratic Programming Solver',['../packages.html#PkgQPSolver',1,'']]],
  ['programs_20such_20as_20demos_20or_20examples_67',['Variables Used Only When Building Programs (Such as Demos or Examples)',['../configurationvariables.html#installation_variables_building',1,'']]],
  ['properties_20of_20point_20sampled_20surfaces_68',['Estimation of Local Differential Properties of Point-Sampled Surfaces',['../packages.html#PkgJetFitting3',1,'']]],
  ['property_20maps_69',['CGAL and Boost Property Maps',['../packages.html#PkgPropertyMap',1,'']]],
  ['provided_20traits_20classes_70',['CGAL-provided traits classes',['../devman_traits_classes.html#subseccgal_traits_classes',1,'']]],
  ['providing_20information_20about_203rd_20party_20libraries_71',['Variables Providing Information About 3rd-Party Libraries',['../configurationvariables.html#installation_variables_third_party',1,'']]]
];
