var NAVTREEINDEX0 =
{
"Convex_decomposition_3_2approximate_convex_decomposition_8cpp-example.html":[3,0],
"Convex_decomposition_3_2list_of_convex_parts_8cpp-example.html":[3,1],
"citelist.html":[2],
"examples.html":[3],
"group__PkgConvexDecomposition3Ref.html":[1,0],
"group__PkgConvexDecomposition3Ref.html#ga447cd9d77212a1306c1d91fc88edc6de":[1,0,1],
"group__PkgConvexDecomposition3Ref.html#ga98ed6393d56fc2eac2ad82a55af84b2f":[1,0,0],
"index.html":[0],
"index.html":[],
"index.html#Convex_decomposition_3ACD_Algorithm":[0,2,0],
"index.html#Convex_decomposition_3ACD_Example":[0,2,3],
"index.html#Convex_decomposition_3ACD_Intro":[0,2],
"index.html#Convex_decomposition_3ACD_Parameters":[0,2,1],
"index.html#Convex_decomposition_3ACD_Performance":[0,2,2],
"index.html#Convex_decomposition_3Example":[0,1,1],
"index.html#Convex_decomposition_3InterfaceandUsage":[0,1,0],
"index.html#Convex_decomposition_3Introduction":[0,0],
"index.html#Convex_decomposition_3Nef":[0,1],
"index.html#Convex_decomposition_3_history":[0,3],
"modules.html":[1],
"pages.html":[]
};
