var searchData=
[
  ['packing_20reference_0',['Sphere Packing Reference',['../../Sphere_packing/group__PkgSpherePackingRef.html',1,'']]],
  ['parameter_20functions_1',['Parameter Functions',['../../Mesh_3/group__PkgMesh3Parameters.html',1,'']]],
  ['parameterization_20methods_2',['Parameterization Methods',['../../Surface_mesh_parameterization/group__PkgSurfaceMeshParameterizationBorderParameterizationMethods.html',1,'Border Parameterization Methods'],['../../Surface_mesh_parameterization/group__PkgSurfaceMeshParameterizationMethods.html',1,'Surface Parameterization Methods']]],
  ['parameters_3',['Named Parameters',['../../BGL/group__bgl__namedparameters.html',1,'']]],
  ['partitioning_20data_20structures_4',['Space Partitioning Data Structures',['../../Isosurfacing_3/group__IS__Partitions__grp.html',1,'']]],
  ['partitioning_20data_20structures_20helpers_5',['Space Partitioning Data Structures Helpers',['../../Isosurfacing_3/group__IS__Partitions__helpers__grp.html',1,'']]],
  ['partitioning_20operations_6',['Partitioning Operations',['../../BGL/group__PkgBGLPartition.html',1,'']]],
  ['patch_20simplification_7',['Planar Patch Simplification',['../../PMP_Remeshing/group__PMP__planar__remeshing__grp.html',1,'']]],
  ['paths_8',['Draw a Mesh with Paths',['../../Surface_mesh_topology/group__PkgDrawFaceGraphWithPaths.html',1,'']]],
  ['periodic_20triangulation_9',['Draw a 2D Periodic Triangulation',['../../Periodic_2_triangulation_2/group__PkgDrawPeriodic2Triangulation2.html',1,'']]],
  ['pixel_20snap_20rounding_10',['Hot Pixel Snap Rounding',['../../Snap_rounding_2/group__Snap__rounding__hot__pixel__grp.html',1,'']]],
  ['pkgbglgeneratorrfct_11',['PkgBGLGeneratorrFct',['../../BGL/group__PkgBGLGeneratorrFct.html',1,'']]],
  ['place_12',['Doubly-Connected List Managing Items in Place',['../../STL_Extension/group__inplacelist.html',1,'']]],
  ['planar_20patch_20simplification_13',['Planar Patch Simplification',['../../PMP_Remeshing/group__PMP__planar__remeshing__grp.html',1,'']]],
  ['planes_14',['Planes',['../../Shape_regularization/group__PkgShapeRegularizationRefPlanes.html',1,'']]],
  ['ply_15',['PLY',['../../Surface_mesh/group__PkgSurfaceMeshIOFuncPLY.html',1,'I/O Functions (PLY)'],['../../Point_set_3/group__PkgPointSet3IOPLY.html',1,'Input/Output (PLY)']]],
  ['ply_20i_20o_20functions_16',['PLY I O Functions',['../../BGL/group__PkgBGLIoFuncsPLY.html',1,'PLY I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncsPLY.html',1,'PLY I/O Functions']]],
  ['point_20family_20weight_17',['Three Point Family Weight',['../../Weights/group__PkgWeightsRefThreePointFamilyWeights.html',1,'']]],
  ['point_20functions_18',['Extreme Point Functions',['../../Convex_hull_2/group__PkgConvexHull2Extreme.html',1,'']]],
  ['point_20location_19',['Point Location',['../../Arrangement_on_surface_2/group__PkgArrangementOnSurface2PointLocation.html',1,'']]],
  ['point_20set_20',['Point Set',['../../Point_set_3/group__PkgDrawPointSet3D.html',1,'Draw a 3D Point Set'],['../../Shape_detection/group__PkgShapeDetectionRGOnPoints.html',1,'Point Set']]],
  ['point_20set_20classification_21',['Point Set Classification',['../../Classification/group__PkgClassificationPointSet.html',1,'']]],
  ['point_5fset_5f3_22',['Convenience Aliases and Functions for Point_set_3',['../../Shape_detection/group__PkgShapeDetectionRGOnPointSet3.html',1,'']]],
  ['points_23',['Voronoi Diagram of Points',['../../Voronoi_diagram_2/group__PkgVoronoiDiagram2Points.html',1,'']]],
  ['polygon_24',['Draw a 2D Polygon',['../../Polygon/group__PkgDrawPolygon2.html',1,'']]],
  ['polygon_20intersection_20functions_25',['Polygon Intersection Functions',['../../Boolean_set_operations_2/group__boolean__intersection.html',1,'']]],
  ['polygon_20intersection_20testing_20functions_26',['Polygon Intersection Testing Functions',['../../Boolean_set_operations_2/group__boolean__do__intersect.html',1,'']]],
  ['polygon_20mesh_27',['Polygon Mesh',['../../Shape_detection/group__PkgShapeDetectionRGOnMesh.html',1,'']]],
  ['polygon_20set_28',['Draw a 2D Polygon Set',['../../Boolean_set_operations_2/group__PkgDrawPolygonSet2.html',1,'']]],
  ['polygon_20with_20holes_29',['Polygon with Holes',['../../Polygon/group__PkgDrawPolygonWithHoles2.html',1,'Draw a 2D Polygon with Holes'],['../../Boolean_set_operations_2/group__boolean__connect__holes.html',1,'Functions on Polygon with Holes']]],
  ['polyhedron_30',['Draw a Nef Polyhedron',['../../Nef_3/group__PkgDrawNef3.html',1,'']]],
  ['polyhedron_203_31',['Draw a Polyhedron 3',['../../Polyhedron/group__PkgDrawPolyhedron.html',1,'']]],
  ['polyline_20simplification_20classes_32',['Polyline Simplification Classes',['../../Polyline_simplification_2/group__PkgPolylineSimplification2Classes.html',1,'']]],
  ['predefined_20features_33',['Predefined Features',['../../Classification/group__PkgClassificationFeatures.html',1,'']]],
  ['predefined_20kernels_34',['Predefined Kernels',['../../Kernel_23/group__kernel__predef.html',1,'']]],
  ['predicates_35',['Predicates',['../../Polygon_mesh_processing/group__PMP__predicates__grp.html',1,'Predicates'],['../../Orthtree/group__PkgOrthtreeSplitPredicates.html',1,'Split Predicates']]],
  ['programming_36',['Programming',['../../Solver_interface/group__PkgSolverInterfaceMIP.html',1,'Mixed Integer Programming'],['../../Solver_interface/group__PkgSolverInterfaceNLP.html',1,'Nonlinear Programming']]],
  ['projection_20classes_37',['Projection classes',['../../Mesh_smoothing_3/group__pkgMeshSmoothing3Projection.html',1,'']]],
  ['projection_20function_20objects_38',['Projection Function Objects',['../../STL_Extension/group__projectionobjects.html',1,'']]],
  ['properties_39',['Properties',['../../BGL/group__PkgBGLPropertiesDynamic.html',1,'Dynamic Properties'],['../../BGL/group__PkgBGLProperties.html',1,'Properties']]],
  ['property_20maps_40',['Property Maps',['../../Shape_detection/group__PkgShapeDetectionRANSACPropertyMaps.html',1,'']]],
  ['pullout_20direction_41',['Is Pullout Direction',['../../Set_movable_separability_2/group__is__pullout__direction__grp.html',1,'']]],
  ['pullout_20directions_42',['Pullout Directions',['../../Set_movable_separability_2/group__pullout__directions__grp.html',1,'']]]
];
