var searchData=
[
  ['l_20infinity_20segment_20delaunay_20graphs_0',['L Infinity Segment Delaunay Graphs',['../packages.html#PkgSegmentDelaunayGraphLinf2',1,'']]],
  ['laslib_1',['LASlib',['../thirdparty.html#thirdpartyLASlib',1,'']]],
  ['laslib_20library_2',['LASlib library',['../configurationvariables.html#installation_laslib',1,'']]],
  ['leda_20library_3',['LEDA Library',['../configurationvariables.html#installation_leda',1,'']]],
  ['leda_20or_20gmp_20support_4',['Checking for LEDA or GMP support',['../devman_portability.html#secleda_gmp_support',1,'']]],
  ['lgpl_5',['GNU LGPL',['../license.html#licensesLGPL',1,'']]],
  ['lgpl_20version_6',['LGPL version',['../devman_code_format.html#Developer_manualLGPLversion',1,'']]],
  ['libraries_7',['Libraries',['../configurationvariables.html#installation_boost',1,'Boost Libraries'],['../installation.html#seclibraries',1,'CGAL Libraries'],['../thirdparty.html#secessential3rdpartysoftware',1,'Essential Third Party Libraries'],['../configurationvariables.html#installation_gmp',1,'GMP and MPFR Libraries'],['../thirdparty.html#secoptional3rdpartysoftware',1,'Optional Third Party Libraries'],['../configurationvariables.html#installation_variables_third_party',1,'Variables Providing Information About 3rd-Party Libraries']]],
  ['libraries_8',['Installing CGAL libraries',['../installation.html',1,'general_intro']]],
  ['library_9',['Library',['../packages.html#PkgBGL',1,'CGAL and the Boost Graph Library'],['../configurationvariables.html#installation_eigen',1,'Eigen Library'],['../configurationvariables.html#installation_esbtl',1,'ESBTL Library'],['../configurationvariables.html#installation_leda',1,'LEDA Library'],['../configurationvariables.html#installation_metis',1,'METIS Library'],['../configurationvariables.html#installation_mpfi',1,'MPFI Library'],['../thirdparty.html#thirdpartyMP',1,'Multi Precision Number Type Library'],['../configurationvariables.html#installation_qt6',1,'Qt6 Library'],['../configurationvariables.html#installation_rs',1,'RS and RS3 Library'],['../packages.html#PartSupportLibrary',1,'Support Library'],['../configurationvariables.html#installation_tbb',1,'TBB Library']]],
  ['library_10',['library',['../configurationvariables.html#installation_GLPK',1,'GLPK library'],['../configurationvariables.html#installation_laslib',1,'LASlib library'],['../configurationvariables.html#installation_OpenCV',1,'OpenCV library'],['../configurationvariables.html#installation_SCIP',1,'SCIP library']]],
  ['library_20manager_11',['Installing CGAL with the Vcpkg Library Manager',['../windows.html#sec-installing-with-vcpkg',1,'']]],
  ['library_20stl_12',['Standard Template Library (STL)',['../thirdparty.html#thirdpartystl',1,'']]],
  ['license_13',['License',['../license.html',1,'general_intro']]],
  ['license_20checking_14',['License Checking',['../license.html#licenseCheck',1,'']]],
  ['license_20choice_15',['Rationale of the License Choice',['../license.html#licensesRationale',1,'']]],
  ['license_20of_20a_20cgal_20file_16',['Determining the license of a CGAL file',['../license.html#licensesWhere',1,'']]],
  ['licenses_17',['Commercial Licenses',['../license.html#licensesCommercial',1,'']]],
  ['line_20tool_18',['Configuring CGAL with the cmake Command-Line Tool',['../installation.html#installation_configuring_cmd',1,'']]],
  ['linear_20and_20quadratic_20programming_20solver_19',['Linear and Quadratic Programming Solver',['../packages.html#PkgQPSolver',1,'']]],
  ['linear_20cell_20complex_20',['Linear Cell Complex',['../packages.html#PkgLinearCellComplex',1,'']]],
  ['linear_20geometry_20kernel_21',['2D and 3D Linear Geometry Kernel',['../packages.html#PkgKernel23',1,'']]],
  ['linker_20flags_22',['Linker Flags',['../configurationvariables.html#installation_additional_flags',1,'Additional Compiler and Linker Flags'],['../configurationvariables.html#installation_flags',1,'Compiler and Linker Flags']]],
  ['linking_20with_20cgal_23',['Linking with CGAL',['../devman_create_and_use_a_cmakelist.html#seclink',1,'']]],
  ['linux_20macos_24',['Using CGAL on Unix (Linux, macOS, ...)',['../usage.html',1,'general_intro']]],
  ['list_25',['Interval Skip List',['../packages.html#PkgIntervalSkipList',1,'']]],
  ['list_20of_20available_20tutorials_26',['List of Available Tutorials',['../tutorials.html#tuto_list',1,'']]],
  ['local_20differential_20properties_20of_20point_20sampled_20surfaces_27',['Estimation of Local Differential Properties of Point-Sampled Surfaces',['../packages.html#PkgJetFitting3',1,'']]],
  ['local_20storage_28',['Thread Local Storage',['../devman_multithreading.html#Developer_manualThreadlocal',1,'']]],
  ['locally_29',['Running a Testsuite Locally',['../devman_testing.html',1,'dev_manual']]],
  ['locally_20of_20a_20single_20package_30',['Running the Testsuite Locally of a Single Package',['../devman_testing.html#pkgTestsuite',1,'']]]
];
