var searchData=
[
  ['tbb_0',['Intel TBB',['../thirdparty.html#thirdpartyTBB',1,'']]],
  ['tbb_202020_20or_20before_1',['TBB 2020 or before',['../configurationvariables.html#installation_old_tbb',1,'']]],
  ['tbb_20library_2',['TBB Library',['../configurationvariables.html#installation_tbb',1,'']]],
  ['template_20functions_3',['Note on global template functions',['../devman_namespaces.html#Developer_manualNoteonglobaltemplatefunctions',1,'']]],
  ['template_20library_20stl_4',['Standard Template Library (STL)',['../thirdparty.html#thirdpartystl',1,'']]],
  ['templated_20handles_5',['Templated handles',['../devman_reference_counting.html#Developer_manualTemplatedhandles',1,'']]],
  ['templated_20handles_6',['Using templated handles',['../devman_reference_counting.html#Developer_manualUsingtemplatedhandles',1,'']]],
  ['terrain_20model_20dtm_7',['Digital Terrain Model (DTM)',['../tuto_gis.html#TutorialGIS_DTM',1,'']]],
  ['testsuite_20locally_8',['Running a Testsuite Locally',['../devman_testing.html',1,'dev_manual']]],
  ['testsuite_20locally_20of_20a_20single_20package_9',['Running the Testsuite Locally of a Single Package',['../devman_testing.html#pkgTestsuite',1,'']]],
  ['tetrahedral_20remeshing_10',['Tetrahedral Remeshing',['../packages.html#PkgTetrahedralRemeshing',1,'']]],
  ['the_20allocator_11',['Using the allocator',['../devman_memory_management.html#secusing_memory_allocator',1,'']]],
  ['the_20allocator_20macro_12',['The allocator macro',['../devman_memory_management.html#secallocator_macro',1,'']]],
  ['the_20boost_20graph_20library_13',['CGAL and the Boost Graph Library',['../packages.html#PkgBGL',1,'']]],
  ['the_20cmake_20command_20line_20tool_14',['Configuring CGAL with the cmake Command-Line Tool',['../installation.html#installation_configuring_cmd',1,'']]],
  ['the_20cmake_20gui_15',['Configuring CGAL with the CMake GUI',['../installation.html#installation_configuring_gui',1,'']]],
  ['the_20convex_20hull_20of_20a_20sequence_20of_20points_16',['The Convex Hull of a Sequence of Points',['../tutorial_hello_world.html#intro_convex_hull',1,'']]],
  ['the_20convex_20hull_20of_20points_20in_20a_20built_20in_20array_17',['The Convex Hull of Points in a Built-in Array',['../tutorial_hello_world.html#intro_array',1,'']]],
  ['the_20convex_20hull_20of_20points_20in_20a_20vector_18',['The Convex Hull of Points in a Vector',['../tutorial_hello_world.html#intro_vector',1,'']]],
  ['the_20heat_20method_19',['The Heat Method',['../packages.html#PkgHeatMethod',1,'']]],
  ['the_20kernel_20',['Adding Function Objects to the Kernel',['../devman_kernels.html#secAddingFunctionObject',1,'']]],
  ['the_20license_20choice_21',['Rationale of the License Choice',['../license.html#licensesRationale',1,'']]],
  ['the_20license_20of_20a_20cgal_20file_22',['Determining the license of a CGAL file',['../license.html#licensesWhere',1,'']]],
  ['the_20manual_23',['the Manual',['../manual.html',1,'Organization of the Manual'],['../manual.html#secorganization',1,'Organization of the Manual']]],
  ['the_20overall_20design_24',['The overall design',['../devman_intro.html#secoverall_design',1,'']]],
  ['the_20qt_20graphics_20view_20framework_25',['CGAL and the Qt Graphics View Framework',['../packages.html#PkgGraphicsView',1,'']]],
  ['the_20reference_20manual_26',['Organization of the Reference Manual',['../manual.html#secorganizationref',1,'']]],
  ['the_20role_20of_20predicates_20and_20constructions_27',['The role of predicates and constructions',['../devman_robustness.html#Developer_manualTheroleofpredicatesandconstructions',1,'']]],
  ['the_20source_20archive_28',['Installing from the Source Archive',['../windows.html#install-from-source',1,'']]],
  ['the_20sphere_29',['the Sphere',['../packages.html#PkgNefS2',1,'2D Boolean Operations on Nef Polygons Embedded on the Sphere'],['../packages.html#PkgTriangulationOnSphere2',1,'2D Triangulations on the Sphere']]],
  ['the_20testsuite_20locally_20of_20a_20single_20package_30',['Running the Testsuite Locally of a Single Package',['../devman_testing.html#pkgTestsuite',1,'']]],
  ['the_20values_20of_20variables_31',['Examining the values of variables',['../devman_debugging.html#secdebugging_handles_and_it',1,'']]],
  ['the_20vcpkg_20library_20manager_32',['Installing CGAL with the Vcpkg Library Manager',['../windows.html#sec-installing-with-vcpkg',1,'']]],
  ['the_20version_20number_20and_20configuration_20macros_20and_20flags_33',['Using the version-number and configuration macros and flags',['../devman_portability.html#secusing_version_macros',1,'']]],
  ['the_20version_20of_20cgal_34',['Identifying the Version of CGAL',['../preliminaries.html#seccgal_version',1,'']]],
  ['third_20party_20dependencies_35',['Compilers and Third Party Dependencies',['../thirdparty.html',1,'general_intro']]],
  ['third_20party_20libraries_36',['Third Party Libraries',['../thirdparty.html#secessential3rdpartysoftware',1,'Essential Third Party Libraries'],['../thirdparty.html#secoptional3rdpartysoftware',1,'Optional Third Party Libraries']]],
  ['thread_20local_20storage_37',['Thread Local Storage',['../devman_multithreading.html#Developer_manualThreadlocal',1,'']]],
  ['thread_20safety_38',['Thread Safety',['../preliminaries.html#Preliminaries_thread_safety',1,'']]],
  ['three_20points_20and_20one_20segment_39',['Three Points and One Segment',['../tutorial_hello_world.html#intro_Three',1,'']]],
  ['time_20flags_20to_20control_20inlining_40',['Compile-time Flags to Control Inlining',['../preliminaries.html#Preliminaries_flags',1,'']]],
  ['tin_41',['Triangulated Irregular Network (TIN)',['../tuto_gis.html#TutorialGIS_TIN',1,'']]],
  ['tin_20with_20info_42',['TIN With Info',['../tuto_gis.html#TutorialGIS_DTM_info',1,'']]],
  ['tips_43',['Debugging Tips',['../devman_debugging.html',1,'dev_manual']]],
  ['to_20cgal_20named_20function_20parameters_44',['Upgrading Code using Boost Parameters to CGAL Named Function Parameters',['../../STL_Extension/FromBoostNPtoCGALNP.html',1,'']]],
  ['to_20control_20inlining_45',['Compile-time Flags to Control Inlining',['../preliminaries.html#Preliminaries_flags',1,'']]],
  ['to_20the_20kernel_46',['Adding Function Objects to the Kernel',['../devman_kernels.html#secAddingFunctionObject',1,'']]],
  ['to_20use_20cgal_20with_20cmake_47',['How to use CGAL with CMake',['../devman_create_and_use_a_cmakelist.html',1,'general_intro']]],
  ['to_20workarounds_20compilers_48',['Macros connected to workarounds/compilers',['../devman_portability.html#secworkaround_macros',1,'']]],
  ['tool_49',['Configuring CGAL with the cmake Command-Line Tool',['../installation.html#installation_configuring_cmd',1,'']]],
  ['tools_20hash_20map_20union_20find_20modifiers_50',['Profiling tools, Hash Map, Union-find, Modifiers',['../packages.html#Miscellany',1,'']]],
  ['topology_51',['Surface Mesh Topology',['../packages.html#PkgSurfaceMeshTopology',1,'']]],
  ['traits_52',['traits',['../devman_iterators_and_circulators.html#seciterator_traits',1,'Iterator and circulator traits'],['../devman_traits_classes.html#seckernel_traits',1,'Kernel as traits'],['../devman_code_format.html#Developer_manualKerneltraits',1,'Kernel traits']]],
  ['traits_20class_20binary_20cross_20checker_53',['An example: Traits class binary cross-checker',['../devman_debugging.html#Developer_manualAnexampleTraitsclassbinary',1,'']]],
  ['traits_20class_20requirements_54',['Traits class requirements',['../devman_traits_classes.html#subsectraits_class_requirements',1,'']]],
  ['traits_20classes_55',['Traits Classes',['../tutorial_hello_world.html#intro_traits',1,'About Kernels and Traits Classes'],['../devman_traits_classes.html',1,'Traits Classes']]],
  ['traits_20classes_56',['CGAL-provided traits classes',['../devman_traits_classes.html#subseccgal_traits_classes',1,'']]],
  ['traits_20classes_20in_20cgal_57',['traits classes in CGAL',['../devman_traits_classes.html#secwhat_is_a_traits_class',1,'What are traits classes in CGAL?'],['../devman_traits_classes.html#secwhy_traits_classes',1,'Why are traits classes in CGAL?']]],
  ['transportation_20curve_20reconstruction_58',['Optimal Transportation Curve Reconstruction',['../packages.html#PkgOptimalTransportationReconstruction2',1,'']]],
  ['trees_59',['dD Range and Segment Trees',['../packages.html#PkgSearchStructures',1,'']]],
  ['triangulated_20irregular_20network_20tin_60',['Triangulated Irregular Network (TIN)',['../tuto_gis.html#TutorialGIS_TIN',1,'']]],
  ['triangulated_20surface_20mesh_20approximation_61',['Triangulated Surface Mesh Approximation',['../packages.html#PkgTSMA',1,'']]],
  ['triangulated_20surface_20mesh_20deformation_62',['Triangulated Surface Mesh Deformation',['../packages.html#PkgSurfaceMeshDeformation',1,'']]],
  ['triangulated_20surface_20mesh_20parameterization_63',['Triangulated Surface Mesh Parameterization',['../packages.html#PkgSurfaceMeshParameterization',1,'']]],
  ['triangulated_20surface_20mesh_20segmentation_64',['Triangulated Surface Mesh Segmentation',['../packages.html#PkgSurfaceMeshSegmentation',1,'']]],
  ['triangulated_20surface_20mesh_20shortest_20paths_65',['Triangulated Surface Mesh Shortest Paths',['../packages.html#PkgSurfaceMeshShortestPath',1,'']]],
  ['triangulated_20surface_20mesh_20simplification_66',['Triangulated Surface Mesh Simplification',['../packages.html#PkgSurfaceMeshSimplification',1,'']]],
  ['triangulated_20surface_20mesh_20skeletonization_67',['Triangulated Surface Mesh Skeletonization',['../packages.html#PkgSurfaceMeshSkeletonization',1,'']]],
  ['triangulated_20surface_20meshes_68',['Approximation of Ridges and Umbilics on Triangulated Surface Meshes',['../packages.html#PkgRidges3',1,'']]],
  ['triangulation_20data_20structure_69',['Triangulation Data Structure',['../packages.html#PkgTDS2',1,'2D Triangulation Data Structure'],['../packages.html#PkgTDS3',1,'3D Triangulation Data Structure']]],
  ['triangulations_70',['Triangulations',['../packages.html#PkgHyperbolicTriangulation2',1,'2D Hyperbolic Delaunay Triangulations'],['../packages.html#PkgPeriodic4HyperbolicTriangulation2',1,'2D Periodic Hyperbolic Triangulations'],['../packages.html#PkgPeriodic2Triangulation2',1,'2D Periodic Triangulations'],['../packages.html#PkgTriangulation2',1,'2D Triangulations'],['../packages.html#PkgConstrainedTriangulation3',1,'3D Constrained Triangulations'],['../packages.html#PkgPeriodic3Triangulation3',1,'3D Periodic Triangulations'],['../packages.html#PkgTriangulation3',1,'3D Triangulations'],['../packages.html#PkgConvexHullD',1,'dD Convex Hulls and Delaunay Triangulations'],['../packages.html#PkgTriangulations',1,'dD Triangulations'],['../packages.html#PartTriangulationsAndDelaunayTriangulations',1,'Triangulations and Delaunay Triangulations']]],
  ['triangulations_20and_20delaunay_20triangulations_71',['Triangulations and Delaunay Triangulations',['../packages.html#PartTriangulationsAndDelaunayTriangulations',1,'']]],
  ['triangulations_20and_20meshes_72',['2D Conforming Triangulations and Meshes',['../packages.html#PkgMesh2',1,'']]],
  ['triangulations_20on_20hyperbolic_20surfaces_73',['2D Triangulations on Hyperbolic Surfaces',['../packages.html#PkgHyperbolicSurfaceTriangulation2',1,'']]],
  ['triangulations_20on_20the_20sphere_74',['2D Triangulations on the Sphere',['../packages.html#PkgTriangulationOnSphere2',1,'']]],
  ['trying_20cgal_20algorithms_20using_20a_20precompiled_20demo_75',['Trying CGAL algorithms using a Precompiled Demo',['../windows.html#sec-win-demo',1,'']]],
  ['tutorials_76',['Tutorials',['../tutorials.html#tuto_list',1,'List of Available Tutorials'],['../tutorials.html',1,'Tutorials']]],
  ['txt_77',['CMakeLists.txt',['../devman_create_and_use_a_cmakelist.html#subcmake',1,'']]],
  ['type_20based_20predicates_78',['Number-type based predicates',['../devman_kernels.html#Developer_manualNumber',1,'']]],
  ['type_20library_79',['Multi Precision Number Type Library',['../thirdparty.html#thirdpartyMP',1,'']]],
  ['types_80',['Types',['../packages.html#PkgNumberTypes',1,'Number Types'],['../devman_polyret.html',1,'Polymorphic Return Types'],['../devman_reference_counting.html',1,'Reference Counting and Handle Types']]]
];
