var annotated =
[
    [ "AlgebraicStructureTraits_", "namespaceAlgebraicStructureTraits__.html", [
      [ "Div", "classAlgebraicStructureTraits___1_1Div.html", "classAlgebraicStructureTraits___1_1Div" ],
      [ "Divides", "classAlgebraicStructureTraits___1_1Divides.html", "classAlgebraicStructureTraits___1_1Divides" ],
      [ "DivMod", "classAlgebraicStructureTraits___1_1DivMod.html", "classAlgebraicStructureTraits___1_1DivMod" ],
      [ "Gcd", "classAlgebraicStructureTraits___1_1Gcd.html", "classAlgebraicStructureTraits___1_1Gcd" ],
      [ "IntegralDivision", "classAlgebraicStructureTraits___1_1IntegralDivision.html", "classAlgebraicStructureTraits___1_1IntegralDivision" ],
      [ "Inverse", "classAlgebraicStructureTraits___1_1Inverse.html", "classAlgebraicStructureTraits___1_1Inverse" ],
      [ "IsOne", "classAlgebraicStructureTraits___1_1IsOne.html", "classAlgebraicStructureTraits___1_1IsOne" ],
      [ "IsSquare", "classAlgebraicStructureTraits___1_1IsSquare.html", "classAlgebraicStructureTraits___1_1IsSquare" ],
      [ "IsZero", "classAlgebraicStructureTraits___1_1IsZero.html", "classAlgebraicStructureTraits___1_1IsZero" ],
      [ "KthRoot", "classAlgebraicStructureTraits___1_1KthRoot.html", "classAlgebraicStructureTraits___1_1KthRoot" ],
      [ "Mod", "classAlgebraicStructureTraits___1_1Mod.html", "classAlgebraicStructureTraits___1_1Mod" ],
      [ "RootOf", "classAlgebraicStructureTraits___1_1RootOf.html", "classAlgebraicStructureTraits___1_1RootOf" ],
      [ "Simplify", "classAlgebraicStructureTraits___1_1Simplify.html", "classAlgebraicStructureTraits___1_1Simplify" ],
      [ "Sqrt", "classAlgebraicStructureTraits___1_1Sqrt.html", "classAlgebraicStructureTraits___1_1Sqrt" ],
      [ "Square", "classAlgebraicStructureTraits___1_1Square.html", "classAlgebraicStructureTraits___1_1Square" ],
      [ "UnitPart", "classAlgebraicStructureTraits___1_1UnitPart.html", "classAlgebraicStructureTraits___1_1UnitPart" ]
    ] ],
    [ "CGAL", null, [
      [ "Algebraic_structure_traits", "classCGAL_1_1Algebraic__structure__traits.html", null ],
      [ "Coercion_traits", "structCGAL_1_1Coercion__traits.html", "structCGAL_1_1Coercion__traits" ],
      [ "Euclidean_ring_tag", "structCGAL_1_1Euclidean__ring__tag.html", null ],
      [ "Field_tag", "structCGAL_1_1Field__tag.html", null ],
      [ "Field_with_kth_root_tag", "structCGAL_1_1Field__with__kth__root__tag.html", null ],
      [ "Field_with_root_of_tag", "structCGAL_1_1Field__with__root__of__tag.html", null ],
      [ "Field_with_sqrt_tag", "structCGAL_1_1Field__with__sqrt__tag.html", null ],
      [ "Fraction_traits", "classCGAL_1_1Fraction__traits.html", null ],
      [ "Integral_domain_tag", "structCGAL_1_1Integral__domain__tag.html", null ],
      [ "Integral_domain_without_division_tag", "structCGAL_1_1Integral__domain__without__division__tag.html", null ],
      [ "Real_embeddable_traits", "classCGAL_1_1Real__embeddable__traits.html", null ],
      [ "Unique_factorization_domain_tag", "structCGAL_1_1Unique__factorization__domain__tag.html", null ]
    ] ],
    [ "FractionTraits_", "namespaceFractionTraits__.html", [
      [ "CommonFactor", "classFractionTraits___1_1CommonFactor.html", "classFractionTraits___1_1CommonFactor" ],
      [ "Compose", "classFractionTraits___1_1Compose.html", "classFractionTraits___1_1Compose" ],
      [ "Decompose", "classFractionTraits___1_1Decompose.html", "classFractionTraits___1_1Decompose" ]
    ] ],
    [ "RealEmbeddableTraits_", "namespaceRealEmbeddableTraits__.html", [
      [ "Abs", "classRealEmbeddableTraits___1_1Abs.html", "classRealEmbeddableTraits___1_1Abs" ],
      [ "Compare", "classRealEmbeddableTraits___1_1Compare.html", "classRealEmbeddableTraits___1_1Compare" ],
      [ "IsNegative", "classRealEmbeddableTraits___1_1IsNegative.html", "classRealEmbeddableTraits___1_1IsNegative" ],
      [ "IsPositive", "classRealEmbeddableTraits___1_1IsPositive.html", "classRealEmbeddableTraits___1_1IsPositive" ],
      [ "IsZero", "classRealEmbeddableTraits___1_1IsZero.html", "classRealEmbeddableTraits___1_1IsZero" ],
      [ "Sgn", "classRealEmbeddableTraits___1_1Sgn.html", "classRealEmbeddableTraits___1_1Sgn" ],
      [ "ToDouble", "classRealEmbeddableTraits___1_1ToDouble.html", "classRealEmbeddableTraits___1_1ToDouble" ],
      [ "ToInterval", "classRealEmbeddableTraits___1_1ToInterval.html", "classRealEmbeddableTraits___1_1ToInterval" ]
    ] ],
    [ "AlgebraicStructureTraits", "classAlgebraicStructureTraits.html", "classAlgebraicStructureTraits" ],
    [ "EuclideanRing", "classEuclideanRing.html", null ],
    [ "ExplicitInteroperable", "classExplicitInteroperable.html", null ],
    [ "Field", "classField.html", "classField" ],
    [ "FieldNumberType", "classFieldNumberType.html", null ],
    [ "FieldWithKthRoot", "classFieldWithKthRoot.html", null ],
    [ "FieldWithRootOf", "classFieldWithRootOf.html", null ],
    [ "FieldWithSqrt", "classFieldWithSqrt.html", null ],
    [ "Fraction", "classFraction.html", null ],
    [ "FractionTraits", "classFractionTraits.html", "classFractionTraits" ],
    [ "FromDoubleConstructible", "classFromDoubleConstructible.html", "classFromDoubleConstructible" ],
    [ "FromIntConstructible", "classFromIntConstructible.html", "classFromIntConstructible" ],
    [ "ImplicitInteroperable", "classImplicitInteroperable.html", null ],
    [ "IntegralDomain", "classIntegralDomain.html", null ],
    [ "IntegralDomainWithoutDivision", "classIntegralDomainWithoutDivision.html", "classIntegralDomainWithoutDivision" ],
    [ "RealEmbeddable", "classRealEmbeddable.html", "classRealEmbeddable" ],
    [ "RealEmbeddableTraits", "classRealEmbeddableTraits.html", "classRealEmbeddableTraits" ],
    [ "RingNumberType", "classRingNumberType.html", null ],
    [ "UniqueFactorizationDomain", "classUniqueFactorizationDomain.html", null ]
];