var searchData=
[
  ['i_2fo_0',['I/O',['../../Arrangement_on_surface_2/group__PkgArrangementOnSurface2IO.html',1,'(Global Namespace)'],['../../Surface_mesher/group__PkgSurfaceMesher3FunctionsIO.html',1,'(Global Namespace)']]],
  ['i_2fo_20enums_1',['I/O Enums',['../../Stream_support/group__PkgStreamSupportEnumRef.html',1,'']]],
  ['i_2fo_20for_20a_20triangulation_203_2',['I/O for a Triangulation 3',['../../Triangulation_3/group__PkgIOTriangulation3.html',1,'']]],
  ['i_2fo_20for_20a_20triangulation_5fdata_5fstructure_5f3_3',['I/O for a Triangulation_data_structure_3',['../../TDS_3/group__PkgIOTDS3.html',1,'']]],
  ['i_2fo_20functions_4',['I/O Functions',['../../Stream_support/group__IOstreamFunctions.html',1,'(Global Namespace)'],['../../Isosurfacing_3/group__IS__IO__functions__grp.html',1,'(Global Namespace)'],['../../BGL/group__PkgBGLIOFct.html',1,'(Global Namespace)'],['../../Mesh_2/group__PkgMesh2IO.html',1,'(Global Namespace)'],['../../Nef_3/group__PkgNef3IOFunctions.html',1,'(Global Namespace)'],['../../Point_set_processing_3/group__PkgPointSetProcessing3IO.html',1,'(Global Namespace)'],['../../Polyhedron/group__PkgPolyhedronIOFunc.html',1,'(Global Namespace)'],['../../Surface_mesh/group__PkgSurfaceMeshIOFunc.html',1,'(Global Namespace)'],['../../PMP_Mesh_repair/group__PMP__IO__grp.html',1,'(Global Namespace)']]],
  ['i_2fo_20functions_20_283mf_29_5',['I/O Functions (3MF)',['../../Surface_mesh/group__PkgSurfaceMeshIOFunc3MF.html',1,'']]],
  ['i_2fo_20functions_20_28deprecated_29_6',['I/O Functions (Deprecated)',['../../Surface_mesh/group__PkgSurfaceMeshIOFuncDeprecated.html',1,'']]],
  ['i_2fo_20functions_20_28off_29_7',['I/O Functions (OFF)',['../../Surface_mesh/group__PkgSurfaceMeshIOFuncOFF.html',1,'']]],
  ['i_2fo_20functions_20_28ply_29_8',['I/O Functions (PLY)',['../../Surface_mesh/group__PkgSurfaceMeshIOFuncPLY.html',1,'']]],
  ['input_20classes_9',['Input Classes',['../../GraphicsView/group__PkgGraphicsViewInputClasses.html',1,'']]],
  ['input_2foutput_10',['Input/Output',['../../Point_set_3/group__PkgPointSet3IO.html',1,'']]],
  ['input_2foutput_20_28las_29_11',['Input/Output (LAS)',['../../Point_set_3/group__PkgPointSet3IOLAS.html',1,'']]],
  ['input_2foutput_20_28off_29_12',['Input/Output (OFF)',['../../Point_set_3/group__PkgPointSet3IOOFF.html',1,'']]],
  ['input_2foutput_20_28ply_29_13',['Input/Output (PLY)',['../../Point_set_3/group__PkgPointSet3IOPLY.html',1,'']]],
  ['input_2foutput_20_28xyz_29_14',['Input/Output (XYZ)',['../../Point_set_3/group__PkgPointSet3IOXYZ.html',1,'']]],
  ['input_2foutput_20functions_15',['Input/Output Functions',['../../Triangulation_on_hyperbolic_surface_2/group__PkgHyperbolicSurfaceTriangulation2InputOutput.html',1,'(Global Namespace)'],['../../Mesh_3/group__PkgMesh3IOFunctions.html',1,'(Global Namespace)'],['../../Periodic_3_mesh_3/group__PkgPeriodic3Mesh3IOFunctions.html',1,'(Global Namespace)'],['../../SMDS_3/group__PkgSMDS3IOFunctions.html',1,'(Global Namespace)']]],
  ['interpolation_20functions_16',['Interpolation Functions',['../../Interpolation/group__PkgInterpolation2Interpolation.html',1,'']]],
  ['intersection_20computation_20functions_20_2d_20cgal_3a_3aintersection_28_29_17',['Intersection Computation Functions - CGAL::intersection()',['../../Kernel_23/group__intersection__grp.html',1,'']]],
  ['intersection_20functions_18',['Intersection Functions',['../../Polygon_mesh_processing/group__PMP__intersection__grp.html',1,'']]],
  ['intersection_20testing_20functions_20_2d_20cgal_3a_3ado_5fintersect_28_29_19',['Intersection Testing Functions - CGAL::do_intersect()',['../../Kernel_23/group__do__intersect__grp.html',1,'']]],
  ['inverse_20distance_20weight_20',['Inverse Distance Weight',['../../Weights/group__PkgWeightsRefInverseDistanceWeights.html',1,'']]],
  ['io_20functions_20for_20cmap_21',['IO Functions for CMap',['../../Combinatorial_map/group__PkgCombinatorialMapsRefIO.html',1,'']]],
  ['io_20functions_20for_20lcc_22',['IO Functions for LCC',['../../Linear_cell_complex/group__PkgLinearCellComplexRefIO.html',1,'']]],
  ['is_20pullout_20direction_23',['Is Pullout Direction',['../../Set_movable_separability_2/group__is__pullout__direction__grp.html',1,'']]],
  ['isosurfacing_20domain_20helpers_24',['Isosurfacing Domain Helpers',['../../Isosurfacing_3/group__IS__Domain__helpers__grp.html',1,'']]],
  ['isosurfacing_20domains_25',['Isosurfacing Domains',['../../Isosurfacing_3/group__IS__Domains__grp.html',1,'']]],
  ['isosurfacing_20methods_26',['Isosurfacing Methods',['../../Isosurfacing_3/group__IS__Methods__grp.html',1,'']]],
  ['item_20classes_27',['Item Classes',['../../HalfedgeDS/group__PkgHalfedgeDS__Items.html',1,'']]],
  ['iterators_20and_20circulators_28',['Iterators and Circulators',['../../BGL/group__PkgBGLIterators.html',1,'']]],
  ['iterators_20and_20iterator_2fcirculator_20adaptors_29',['Iterators and Iterator/Circulator Adaptors',['../../STL_Extension/group__STLIterators.html',1,'']]]
];
