var searchData=
[
  ['a_20built_20in_20array_0',['The Convex Hull of Points in a Built-in Array',['../tutorial_hello_world.html#intro_array',1,'']]],
  ['a_20cgal_20file_1',['Determining the license of a CGAL file',['../license.html#licensesWhere',1,'']]],
  ['a_20circulator_20for_20your_20container_2',['Writing a circulator for your container',['../devman_iterators_and_circulators.html#secclass_circulator',1,'']]],
  ['a_20cmake_20script_20for_20a_20program_20using_20cgal_3',['Creating a CMake Script for a Program Using CGAL',['../devman_create_cgal_CMakeLists.html',1,'dev_manual']]],
  ['a_20contour_20graph_4',['Building a Contour Graph',['../tuto_gis.html#TutorialGIS_Contour_Extraction',1,'']]],
  ['a_20finer_20granularity_5',['Controlling checks at a finer granularity',['../devman_checks.html#secchecks_controlling',1,'']]],
  ['a_20package_20manager_6',['Using a Package Manager',['../usage.html#secusingpkgman',1,'']]],
  ['a_20precompiled_20demo_7',['Trying CGAL algorithms using a Precompiled Demo',['../windows.html#sec-win-demo',1,'']]],
  ['a_20program_20using_20cgal_8',['Creating a CMake Script for a Program Using CGAL',['../devman_create_cgal_CMakeLists.html',1,'dev_manual']]],
  ['a_20program_20using_20cgal_9',['a Program using CGAL',['../installation.html#installation_buildprogram',1,'Building a Program using CGAL'],['../usage.html#usage_introduction',1,'Quick Start: Compiling a Program using CGAL']]],
  ['a_20sequence_20of_20points_10',['The Convex Hull of a Sequence of Points',['../tutorial_hello_world.html#intro_convex_hull',1,'']]],
  ['a_20single_20package_11',['Running the Testsuite Locally of a Single Package',['../devman_testing.html#pkgTestsuite',1,'']]],
  ['a_20testsuite_20locally_12',['Running a Testsuite Locally',['../devman_testing.html',1,'dev_manual']]],
  ['a_20vector_13',['The Convex Hull of Points in a Vector',['../tutorial_hello_world.html#intro_vector',1,'']]],
  ['about_203rd_20party_20libraries_14',['Variables Providing Information About 3rd-Party Libraries',['../configurationvariables.html#installation_variables_third_party',1,'']]],
  ['about_20kernels_20and_20traits_20classes_15',['About Kernels and Traits Classes',['../tutorial_hello_world.html#intro_traits',1,'']]],
  ['acknowledging_20cgal_16',['Acknowledging CGAL',['../how_to_cite_cgal.html',1,'']]],
  ['adaptor_17',['2D Voronoi Diagram Adaptor',['../packages.html#PkgVoronoiDiagram2',1,'']]],
  ['adding_20function_20objects_20to_20the_20kernel_18',['Adding Function Objects to the Kernel',['../devman_kernels.html#secAddingFunctionObject',1,'']]],
  ['additional_20compiler_20and_20linker_20flags_19',['Additional Compiler and Linker Flags',['../configurationvariables.html#installation_additional_flags',1,'']]],
  ['additional_20dependencies_20',['Additional Dependencies',['../windows.html#sssect-vcpkg-additional-dependencies',1,'Additional Dependencies'],['../windows.html#ssect-installer-additional-dependencies',1,'Additional Dependencies']]],
  ['advanced_20configuration_20options_21',['Advanced Configuration Options',['../usage.html#usage_configuring_advanced_cmake',1,'']]],
  ['advanced_20features_22',['Advanced Features',['../manual.html#advanced_features',1,'']]],
  ['advancing_20front_23',['Advancing Front',['../tuto_reconstruction.html#TutorialsReconstruction_reconstruction_advancing',1,'']]],
  ['advancing_20front_20surface_20reconstruction_24',['Advancing Front Surface Reconstruction',['../packages.html#PkgAdvancingFrontSurfaceReconstruction',1,'']]],
  ['algebra_25',['Arithmetic and Algebra',['../packages.html#PartAlgebraicFoundations',1,'']]],
  ['algebraic_20foundations_26',['Algebraic Foundations',['../packages.html#PkgAlgebraicFoundations',1,'']]],
  ['algebraic_20kernel_27',['Algebraic Kernel',['../packages.html#PkgAlgebraicKernelD',1,'']]],
  ['algorithm_20should_20i_20use_28',['Which algorithm should I use?',['../tuto_reconstruction.html#TutorialsReconstruction_algorithms',1,'']]],
  ['algorithms_29',['Algorithms',['../packages.html#PartCombinatorialAlgorithms',1,'Combinatorial Algorithms'],['../packages.html#PartConvexHullAlgorithms',1,'Convex Hull Algorithms']]],
  ['algorithms_30',['Geometric data structures and algorithms',['../devman_code_format.html#Developer_manualGeometricdatastructuresand',1,'']]],
  ['algorithms_20using_20a_20precompiled_20demo_31',['Trying CGAL algorithms using a Precompiled Demo',['../windows.html#sec-win-demo',1,'']]],
  ['allocation_32',['Allocation',['../devman_reference_counting.html#Developer_manualAllocation',1,'']]],
  ['allocator_33',['Using the allocator',['../devman_memory_management.html#secusing_memory_allocator',1,'']]],
  ['allocator_20macro_34',['The allocator macro',['../devman_memory_management.html#secallocator_macro',1,'']]],
  ['alpha_20shapes_35',['Alpha Shapes',['../packages.html#PkgAlphaShapes2',1,'2D Alpha Shapes'],['../packages.html#PkgAlphaShapes3',1,'3D Alpha Shapes']]],
  ['alpha_20wrapping_36',['Alpha Wrapping',['../packages.html#PkgAlphaWrap2',1,'2D Alpha Wrapping'],['../packages.html#PkgAlphaWrap3',1,'3D Alpha Wrapping']]],
  ['an_20example_37',['an Example',['../windows.html#sssect-vcpkg-compilation',1,'Compilation of an Example'],['../windows.html#sssect-installer-compilation',1,'Compilation of an Example'],['../windows.html#ssec-vcpkg-compile-example',1,'Compiling an Example'],['../windows.html#ssect-installer-compile-example',1,'Compiling an Example'],['../windows.html#sssec-vcpkg-configuration-example',1,'Configuring of an Example']]],
  ['an_20example_20planar_20convex_20hulls_38',['An example - planar convex hulls',['../devman_traits_classes.html#sectraits_class_example',1,'']]],
  ['an_20example_3a_20traits_20class_20binary_20cross_20checker_39',['An example: Traits class binary cross-checker',['../devman_debugging.html#Developer_manualAnexampleTraitsclassbinary',1,'']]],
  ['an_20external_20program_40',['Configuring an External Program',['../usage.html#usage_configuring_external',1,'']]],
  ['an_20iterator_20for_20your_20container_41',['Writing an iterator for your container',['../devman_iterators_and_circulators.html#secclass_iterator',1,'']]],
  ['analysis_42',['Principal Component Analysis',['../packages.html#PkgPrincipalComponentAnalysisD',1,'']]],
  ['and_203d_20fast_20intersection_20and_20distance_20computation_43',['2D and 3D Fast Intersection and Distance Computation',['../packages.html#PkgAABBTree',1,'']]],
  ['and_203d_20linear_20geometry_20kernel_44',['2D and 3D Linear Geometry Kernel',['../packages.html#PkgKernel23',1,'']]],
  ['and_20algebra_45',['Arithmetic and Algebra',['../packages.html#PartAlgebraicFoundations',1,'']]],
  ['and_20algorithms_46',['Geometric data structures and algorithms',['../devman_code_format.html#Developer_manualGeometricdatastructuresand',1,'']]],
  ['and_20architectures_47',['Identifying compilers and architectures',['../devman_portability.html#secwhich_compiler',1,'']]],
  ['and_20boost_20property_20maps_48',['CGAL and Boost Property Maps',['../packages.html#PkgPropertyMap',1,'']]],
  ['and_20circulator_20traits_49',['Iterator and circulator traits',['../devman_iterators_and_circulators.html#seciterator_traits',1,'']]],
  ['and_20circulators_50',['Writing functions for iterators AND circulators',['../devman_iterators_and_circulators.html#secit_and_circ_code',1,'']]],
  ['and_20circulators_51',['Handles and Circulators',['../packages.html#PkgHandlesAndCirculators',1,'']]],
  ['and_20compiling_20my_20code_20using_20cgal_52',['Configuring and Compiling My Code Using CGAL',['../windows.html#subsect-installer-my-code',1,'']]],
  ['and_20compiling_20your_20code_20using_20cgal_53',['Configuring and Compiling Your Code Using CGAL',['../windows.html#subsect-vpckg-my-code',1,'']]],
  ['and_20configuration_20macros_20and_20flags_54',['Using the version-number and configuration macros and flags',['../devman_portability.html#secusing_version_macros',1,'']]],
  ['and_20constructions_55',['The role of predicates and constructions',['../devman_robustness.html#Developer_manualTheroleofpredicatesandconstructions',1,'']]],
  ['and_20conventions_56',['Kernel design and conventions',['../devman_kernels.html#Developer_manualKerneldesignandconventions',1,'']]],
  ['and_20delaunay_20triangulations_57',['and Delaunay Triangulations',['../packages.html#PkgConvexHullD',1,'dD Convex Hulls and Delaunay Triangulations'],['../packages.html#PartTriangulationsAndDelaunayTriangulations',1,'Triangulations and Delaunay Triangulations']]],
  ['and_20demos_58',['and Demos',['../installation.html#ssec_installation_build_ex_demos',1,'Building Examples and Demos'],['../installation.html#installation_examples',1,'CGAL Examples and Demos']]],
  ['and_20distance_20computation_59',['2D and 3D Fast Intersection and Distance Computation',['../packages.html#PkgAABBTree',1,'']]],
  ['and_20extreme_20points_60',['2D Convex Hulls and Extreme Points',['../packages.html#PkgConvexHull2',1,'']]],
  ['and_20flags_61',['Using the version-number and configuration macros and flags',['../devman_portability.html#secusing_version_macros',1,'']]],
  ['and_20for_20iterators_20circulators_20and_20handles_62',['Writing code with and for iterators, circulators, and handles',['../devman_iterators_and_circulators.html#Developer_manualWritingcodewithandforiterators',1,'']]],
  ['and_20handle_20types_63',['Reference Counting and Handle Types',['../devman_reference_counting.html',1,'dev_manual']]],
  ['and_20handles_64',['Iterators, Circulators and Handles',['../devman_iterators_and_circulators.html',1,'dev_manual']]],
  ['and_20handles_65',['Writing code with and for iterators, circulators, and handles',['../devman_iterators_and_circulators.html#Developer_manualWritingcodewithandforiterators',1,'']]],
  ['and_20linker_20flags_66',['and Linker Flags',['../configurationvariables.html#installation_additional_flags',1,'Additional Compiler and Linker Flags'],['../configurationvariables.html#installation_flags',1,'Compiler and Linker Flags']]],
  ['and_20meshes_67',['2D Conforming Triangulations and Meshes',['../packages.html#PkgMesh2',1,'']]],
  ['and_20models_68',['and Models',['../preliminaries.html#preliminaries_secconmod',1,'Concepts and Models'],['../tutorial_hello_world.html#intro_concept',1,'Concepts and Models']]],
  ['and_20mpfr_69',['Installing GMP and MPFR',['../windows.html#ssect-installer-gmp-mpfr',1,'']]],
  ['and_20mpfr_20libraries_70',['GMP and MPFR Libraries',['../configurationvariables.html#installation_gmp',1,'']]],
  ['and_20neighbor_20search_71',['2D Range and Neighbor Search',['../packages.html#PkgPointSet2',1,'']]],
  ['and_20one_20segment_72',['Three Points and One Segment',['../tutorial_hello_world.html#intro_Three',1,'']]],
  ['and_20orientation_73',['Normal Estimation and Orientation',['../tuto_reconstruction.html#TutorialsReconstruction_preprocessing_normal',1,'']]],
  ['and_20orthtrees_74',['Quadtrees, Octrees, and Orthtrees',['../packages.html#PkgOrthtree',1,'']]],
  ['and_20output_20iterators_75',['Input and output iterators',['../devman_iterators_and_circulators.html#secinput_and_output_iterators',1,'']]],
  ['and_20polygon_20offsetting_76',['2D Straight Skeleton and Polygon Offsetting',['../packages.html#PkgStraightSkeleton2',1,'']]],
  ['and_20polyhedra_77',['Cell Complexes and Polyhedra',['../packages.html#PartPolyhedra',1,'']]],
  ['and_20postconditions_20assertions_20and_20warnings_78',['Checks: Pre- and Postconditions, Assertions, and Warnings',['../devman_checks.html',1,'dev_manual']]],
  ['and_20postprocessing_79',['Output and Postprocessing',['../tuto_reconstruction.html#TutorialsReconstruction_postprocessing',1,'']]],
  ['and_20quadratic_20programming_20solver_80',['Linear and Quadratic Programming Solver',['../packages.html#PkgQPSolver',1,'']]],
  ['and_20recommendations_81',['and recommendations',['../devman_checks.html#secchecks_req_and_rec',1,'Requirements and recommendations'],['../devman_code_format.html#seccode_format_doc_req_and_rec',1,'Requirements and recommendations'],['../devman_iterators_and_circulators.html#it_and_circit_and_circ_req_and_rec',1,'Requirements and recommendations'],['../devman_memory_management.html#secmemory_req_and_rec',1,'Requirements and recommendations'],['../devman_namespaces.html#Developer_manualRequirementsandrecommendations_1',1,'Requirements and recommendations'],['../devman_robustness.html#Developer_manualRequirementsandrecommendations',1,'Requirements and recommendations'],['../devman_traits_classes.html#sectraits_class_req_and_rec',1,'Requirements and recommendations']]],
  ['and_20remeshing_82',['Hole Filling and Remeshing',['../tuto_gis.html#Tutorial_DTM_hole_filling',1,'']]],
  ['and_20remeshing_20of_20polygon_20meshes_83',['Meshing and Remeshing of Polygon Meshes',['../packages.html#PkgPMPRemeshing',1,'']]],
  ['and_20rs3_20library_84',['RS and RS3 Library',['../configurationvariables.html#installation_rs',1,'']]],
  ['and_20segment_20trees_85',['dD Range and Segment Trees',['../packages.html#PkgSearchStructures',1,'']]],
  ['and_20solutions_86',['Various other problems and solutions',['../devman_portability.html#secvarious_problems',1,'']]],
  ['and_20solvers_87',['CGAL and Solvers',['../packages.html#PkgSolverInterface',1,'']]],
  ['and_20sorted_20matrix_20search_88',['Monotone and Sorted Matrix Search',['../packages.html#PkgMatrixSearch',1,'']]],
  ['and_20sorting_89',['Spatial Searching and Sorting',['../packages.html#PartSearchStructures',1,'']]],
  ['and_20surface_20function_20interpolation_90',['2D and Surface Function Interpolation',['../packages.html#PkgInterpolation2',1,'']]],
  ['and_20the_20boost_20graph_20library_91',['CGAL and the Boost Graph Library',['../packages.html#PkgBGL',1,'']]],
  ['and_20the_20qt_20graphics_20view_20framework_92',['CGAL and the Qt Graphics View Framework',['../packages.html#PkgGraphicsView',1,'']]],
  ['and_20third_20party_20dependencies_93',['Compilers and Third Party Dependencies',['../thirdparty.html',1,'general_intro']]],
  ['and_20traits_20classes_94',['About Kernels and Traits Classes',['../tutorial_hello_world.html#intro_traits',1,'']]],
  ['and_20umbilics_20on_20triangulated_20surface_20meshes_95',['Approximation of Ridges and Umbilics on Triangulated Surface Meshes',['../packages.html#PkgRidges3',1,'']]],
  ['and_20warnings_96',['Checks: Pre- and Postconditions, Assertions, and Warnings',['../devman_checks.html',1,'dev_manual']]],
  ['and_20workarounds_97',['Known problems and workarounds',['../devman_portability.html#secproblems_and_workarounds',1,'']]],
  ['apollonius_20graphs_20delaunay_20graphs_20of_20disks_98',['2D Apollonius Graphs (Delaunay Graphs of Disks)',['../packages.html#PkgApolloniusGraph2',1,'']]],
  ['approximation_99',['Triangulated Surface Mesh Approximation',['../packages.html#PkgTSMA',1,'']]],
  ['approximation_20of_20ridges_20and_20umbilics_20on_20triangulated_20surface_20meshes_100',['Approximation of Ridges and Umbilics on Triangulated Surface Meshes',['../packages.html#PkgRidges3',1,'']]],
  ['architectures_101',['Identifying compilers and architectures',['../devman_portability.html#secwhich_compiler',1,'']]],
  ['archive_102',['Archive',['../windows.html#install-from-source',1,'Installing from the Source Archive'],['../usage.html#secusingwebsite',1,'Using CGAL Source Archive']]],
  ['are_20traits_20classes_20in_20cgal_103',['are traits classes in CGAL',['../devman_traits_classes.html#secwhat_is_a_traits_class',1,'What are traits classes in CGAL?'],['../devman_traits_classes.html#secwhy_traits_classes',1,'Why are traits classes in CGAL?']]],
  ['areas_104',['Inscribed Areas',['../packages.html#PkgInscribedAreas',1,'']]],
  ['arithmetic_105',['Modular Arithmetic',['../packages.html#PkgModularArithmetic',1,'']]],
  ['arithmetic_20and_20algebra_106',['Arithmetic and Algebra',['../packages.html#PartAlgebraicFoundations',1,'']]],
  ['arrangements_107',['Arrangements',['../packages.html#PkgArrangementOnSurface2',1,'2D Arrangements'],['../packages.html#PartArrangements',1,'Arrangements']]],
  ['array_108',['The Convex Hull of Points in a Built-in Array',['../tutorial_hello_world.html#intro_array',1,'']]],
  ['as_20demos_20or_20examples_109',['Variables Used Only When Building Programs (Such as Demos or Examples)',['../configurationvariables.html#installation_variables_building',1,'']]],
  ['as_20traits_110',['Kernel as traits',['../devman_traits_classes.html#seckernel_traits',1,'']]],
  ['assertions_20and_20warnings_111',['Checks: Pre- and Postconditions, Assertions, and Warnings',['../devman_checks.html',1,'dev_manual']]],
  ['at_20a_20finer_20granularity_112',['Controlling checks at a finer granularity',['../devman_checks.html#secchecks_controlling',1,'']]],
  ['available_20tutorials_113',['List of Available Tutorials',['../tutorials.html#tuto_list',1,'']]]
];
