var group__PkgKernel23ConceptsGeomObject =
[
    [ "Kernel::Circle_2", "classKernel_1_1Circle__2.html", null ],
    [ "Kernel::Circle_3", "classKernel_1_1Circle__3.html", null ],
    [ "Kernel::Direction_2", "classKernel_1_1Direction__2.html", null ],
    [ "Kernel::Direction_3", "classKernel_1_1Direction__3.html", null ],
    [ "Kernel::IsoCuboid_3", "classKernel_1_1IsoCuboid__3.html", null ],
    [ "Kernel::IsoRectangle_2", "classKernel_1_1IsoRectangle__2.html", null ],
    [ "Kernel::Line_2", "classKernel_1_1Line__2.html", null ],
    [ "Kernel::Line_3", "classKernel_1_1Line__3.html", null ],
    [ "Kernel::Object_2", "classKernel_1_1Object__2.html", null ],
    [ "Kernel::Object_3", "classKernel_1_1Object__3.html", null ],
    [ "Kernel::Plane_3", "classKernel_1_1Plane__3.html", null ],
    [ "Kernel::Point_2", "classKernel_1_1Point__2.html", null ],
    [ "Kernel::Point_3", "classKernel_1_1Point__3.html", null ],
    [ "Kernel::Ray_2", "classKernel_1_1Ray__2.html", null ],
    [ "Kernel::Ray_3", "classKernel_1_1Ray__3.html", null ],
    [ "Kernel::Segment_2", "classKernel_1_1Segment__2.html", null ],
    [ "Kernel::Segment_3", "classKernel_1_1Segment__3.html", null ],
    [ "Kernel::Sphere_3", "classKernel_1_1Sphere__3.html", null ],
    [ "Kernel::Tetrahedron_3", "classKernel_1_1Tetrahedron__3.html", null ],
    [ "Kernel::Triangle_2", "classKernel_1_1Triangle__2.html", null ],
    [ "Kernel::Triangle_3", "classKernel_1_1Triangle__3.html", null ],
    [ "Kernel::Vector_2", "classKernel_1_1Vector__2.html", null ],
    [ "Kernel::Vector_3", "classKernel_1_1Vector__3.html", null ],
    [ "Kernel::WeightedPoint_2", "classKernel_1_1WeightedPoint__2.html", null ],
    [ "Kernel::WeightedPoint_3", "classKernel_1_1WeightedPoint__3.html", null ]
];