var searchData=
[
  ['range_20and_20neighbor_20search_0',['2D Range and Neighbor Search',['../packages.html#PkgPointSet2',1,'']]],
  ['range_20and_20segment_20trees_1',['dD Range and Segment Trees',['../packages.html#PkgSearchStructures',1,'']]],
  ['rastering_2',['Rastering',['../tuto_gis.html#TutorialGIS_Raster',1,'']]],
  ['rationale_20of_20the_20license_20choice_3',['Rationale of the License Choice',['../license.html#licensesRationale',1,'']]],
  ['reading_4',['Reading',['../tutorial_hello_world.html#intro_further',1,'Further Reading'],['../devman_info.html',1,'Recommended Reading']]],
  ['reading_20input_5',['Reading Input',['../tuto_reconstruction.html#TutorialsReconstruction_input',1,'']]],
  ['recommendations_6',['recommendations',['../devman_checks.html#secchecks_req_and_rec',1,'Requirements and recommendations'],['../devman_code_format.html#seccode_format_doc_req_and_rec',1,'Requirements and recommendations'],['../devman_iterators_and_circulators.html#it_and_circit_and_circ_req_and_rec',1,'Requirements and recommendations'],['../devman_memory_management.html#secmemory_req_and_rec',1,'Requirements and recommendations'],['../devman_namespaces.html#Developer_manualRequirementsandrecommendations_1',1,'Requirements and recommendations'],['../devman_robustness.html#Developer_manualRequirementsandrecommendations',1,'Requirements and recommendations'],['../devman_traits_classes.html#sectraits_class_req_and_rec',1,'Requirements and recommendations']]],
  ['recommended_20reading_7',['Recommended Reading',['../devman_info.html',1,'dev_manual']]],
  ['reconstruction_8',['Reconstruction',['../packages.html#PkgAdvancingFrontSurfaceReconstruction',1,'Advancing Front Surface Reconstruction'],['../packages.html#PkgKineticSurfaceReconstruction',1,'Kinetic Surface Reconstruction'],['../packages.html#PkgOptimalTransportationReconstruction2',1,'Optimal Transportation Curve Reconstruction'],['../packages.html#PkgPoissonSurfaceReconstruction3',1,'Poisson Surface Reconstruction'],['../packages.html#PkgPolygonalSurfaceReconstruction',1,'Polygonal Surface Reconstruction'],['../tuto_reconstruction.html#TutorialsReconstruction_reconstruction',1,'Reconstruction'],['../packages.html#PkgScaleSpaceReconstruction3',1,'Scale-Space Surface Reconstruction'],['../packages.html#PartReconstruction',1,'Shape Reconstruction']]],
  ['reconstruction_20from_20point_20clouds_9',['Surface Reconstruction from Point Clouds',['../tuto_reconstruction.html',1,'tutorials']]],
  ['reference_20counting_10',['Reference counting',['../devman_reference_counting.html#Developer_manualReferencecounting',1,'']]],
  ['reference_20counting_20and_20handle_20types_11',['Reference Counting and Handle Types',['../devman_reference_counting.html',1,'dev_manual']]],
  ['reference_20manual_12',['Organization of the Reference Manual',['../manual.html#secorganizationref',1,'']]],
  ['reference_20pages_13',['Classified Reference Pages',['../../Algebraic_foundations/AlgebraicFoundationsClassified.html',1,'']]],
  ['references_14',['References',['../tuto_gis.html#TutorialGIS_Reference',1,'']]],
  ['regularization_15',['Shape Regularization',['../packages.html#PkgShapeRegularization',1,'']]],
  ['regularized_20boolean_20set_20operations_16',['2D Regularized Boolean Set-Operations',['../packages.html#PkgBooleanSetOperations2',1,'']]],
  ['release_17',['Debug vs. Release',['../installation.html#installation_debugrelease',1,'']]],
  ['remeshing_18',['Remeshing',['../tuto_gis.html#Tutorial_DTM_hole_filling',1,'Hole Filling and Remeshing'],['../packages.html#PkgTetrahedralRemeshing',1,'Tetrahedral Remeshing']]],
  ['remeshing_20of_20polygon_20meshes_19',['Meshing and Remeshing of Polygon Meshes',['../packages.html#PkgPMPRemeshing',1,'']]],
  ['removal_20',['Outlier removal',['../tuto_reconstruction.html#TutorialsReconstruction_preprocessing_outliers',1,'']]],
  ['rep_21',['Rep',['../devman_reference_counting.html#Developer_manualHandleRep',1,'Handle &amp;amp; Rep'],['../devman_reference_counting.html#Developer_manualUsingHandleRep',1,'Using Handle &amp;amp; Rep']]],
  ['repair_22',['Repair',['../packages.html#PkgPolygonRepair',1,'2D Polygon Repair'],['../packages.html#PkgPMPMeshRepair',1,'Polygon Mesh Repair']]],
  ['requirements_23',['Traits class requirements',['../devman_traits_classes.html#subsectraits_class_requirements',1,'']]],
  ['requirements_20and_20recommendations_24',['Requirements and recommendations',['../devman_checks.html#secchecks_req_and_rec',1,'Requirements and recommendations'],['../devman_code_format.html#seccode_format_doc_req_and_rec',1,'Requirements and recommendations'],['../devman_iterators_and_circulators.html#it_and_circit_and_circ_req_and_rec',1,'Requirements and recommendations'],['../devman_memory_management.html#secmemory_req_and_rec',1,'Requirements and recommendations'],['../devman_namespaces.html#Developer_manualRequirementsandrecommendations_1',1,'Requirements and recommendations'],['../devman_robustness.html#Developer_manualRequirementsandrecommendations',1,'Requirements and recommendations'],['../devman_traits_classes.html#sectraits_class_req_and_rec',1,'Requirements and recommendations']]],
  ['return_20types_25',['Polymorphic Return Types',['../devman_polyret.html',1,'dev_manual']]],
  ['ridges_20and_20umbilics_20on_20triangulated_20surface_20meshes_26',['Approximation of Ridges and Umbilics on Triangulated Surface Meshes',['../packages.html#PkgRidges3',1,'']]],
  ['robustness_27',['Robustness',['../devman_intro.html#Developer_manualRobustness',1,'']]],
  ['robustness_20issues_28',['Robustness Issues',['../devman_robustness.html',1,'dev_manual']]],
  ['role_20of_20predicates_20and_20constructions_29',['The role of predicates and constructions',['../devman_robustness.html#Developer_manualTheroleofpredicatesandconstructions',1,'']]],
  ['rounding_30',['2D Snap Rounding',['../packages.html#PkgSnapRounding2',1,'']]],
  ['rs_20and_20rs3_20library_31',['RS and RS3 Library',['../configurationvariables.html#installation_rs',1,'']]],
  ['rs3_20library_32',['RS and RS3 Library',['../configurationvariables.html#installation_rs',1,'']]],
  ['rules_33',['General rules',['../devman_code_format.html#Developer_manualGeneralrules',1,'']]],
  ['running_20a_20testsuite_20locally_34',['Running a Testsuite Locally',['../devman_testing.html',1,'dev_manual']]],
  ['running_20the_20testsuite_20locally_20of_20a_20single_20package_35',['Running the Testsuite Locally of a Single Package',['../devman_testing.html#pkgTestsuite',1,'']]]
];
