var searchData=
[
  ['2020_20or_20before_0',['TBB 2020 or before',['../configurationvariables.html#installation_old_tbb',1,'']]],
  ['2d_20alpha_20shapes_1',['2D Alpha Shapes',['../packages.html#PkgAlphaShapes2',1,'']]],
  ['2d_20alpha_20wrapping_2',['2D Alpha Wrapping',['../packages.html#PkgAlphaWrap2',1,'']]],
  ['2d_20and_203d_20fast_20intersection_20and_20distance_20computation_3',['2D and 3D Fast Intersection and Distance Computation',['../packages.html#PkgAABBTree',1,'']]],
  ['2d_20and_203d_20linear_20geometry_20kernel_4',['2D and 3D Linear Geometry Kernel',['../packages.html#PkgKernel23',1,'']]],
  ['2d_20and_20surface_20function_20interpolation_5',['2D and Surface Function Interpolation',['../packages.html#PkgInterpolation2',1,'']]],
  ['2d_20apollonius_20graphs_20delaunay_20graphs_20of_20disks_6',['2D Apollonius Graphs (Delaunay Graphs of Disks)',['../packages.html#PkgApolloniusGraph2',1,'']]],
  ['2d_20arrangements_7',['2D Arrangements',['../packages.html#PkgArrangementOnSurface2',1,'']]],
  ['2d_20boolean_20operations_20on_20nef_20polygons_8',['2D Boolean Operations on Nef Polygons',['../packages.html#PkgNef2',1,'']]],
  ['2d_20boolean_20operations_20on_20nef_20polygons_20embedded_20on_20the_20sphere_9',['2D Boolean Operations on Nef Polygons Embedded on the Sphere',['../packages.html#PkgNefS2',1,'']]],
  ['2d_20circular_20geometry_20kernel_10',['2D Circular Geometry Kernel',['../packages.html#PkgCircularKernel2',1,'']]],
  ['2d_20conforming_20triangulations_20and_20meshes_11',['2D Conforming Triangulations and Meshes',['../packages.html#PkgMesh2',1,'']]],
  ['2d_20convex_20hulls_20and_20extreme_20points_12',['2D Convex Hulls and Extreme Points',['../packages.html#PkgConvexHull2',1,'']]],
  ['2d_20envelopes_13',['2D Envelopes',['../packages.html#PkgEnvelope2',1,'']]],
  ['2d_20generalized_20barycentric_20coordinates_14',['2D Generalized Barycentric Coordinates',['../packages.html#PkgBarycentricCoordinates2',1,'']]],
  ['2d_20hyperbolic_20delaunay_20triangulations_15',['2D Hyperbolic Delaunay Triangulations',['../packages.html#PkgHyperbolicTriangulation2',1,'']]],
  ['2d_20intersection_20of_20curves_16',['2D Intersection of Curves',['../packages.html#PkgSurfaceSweep2',1,'']]],
  ['2d_20minkowski_20sums_17',['2D Minkowski Sums',['../packages.html#PkgMinkowskiSum2',1,'']]],
  ['2d_20movable_20separability_20of_20sets_18',['2D Movable Separability of Sets',['../packages.html#PkgSetMovableSeparability2',1,'']]],
  ['2d_20periodic_20hyperbolic_20triangulations_19',['2D Periodic Hyperbolic Triangulations',['../packages.html#PkgPeriodic4HyperbolicTriangulation2',1,'']]],
  ['2d_20periodic_20triangulations_20',['2D Periodic Triangulations',['../packages.html#PkgPeriodic2Triangulation2',1,'']]],
  ['2d_20placement_20of_20streamlines_21',['2D Placement of Streamlines',['../packages.html#PkgStreamLines2',1,'']]],
  ['2d_20polygon_20partitioning_22',['2D Polygon Partitioning',['../packages.html#PkgPartition2',1,'']]],
  ['2d_20polygon_20repair_23',['2D Polygon Repair',['../packages.html#PkgPolygonRepair',1,'']]],
  ['2d_20polygons_24',['2D Polygons',['../packages.html#PkgPolygon2',1,'']]],
  ['2d_20polyline_20simplification_25',['2D Polyline Simplification',['../packages.html#PkgPolylineSimplification2',1,'']]],
  ['2d_20range_20and_20neighbor_20search_26',['2D Range and Neighbor Search',['../packages.html#PkgPointSet2',1,'']]],
  ['2d_20regularized_20boolean_20set_20operations_27',['2D Regularized Boolean Set-Operations',['../packages.html#PkgBooleanSetOperations2',1,'']]],
  ['2d_20segment_20delaunay_20graphs_28',['2D Segment Delaunay Graphs',['../packages.html#PkgSegmentDelaunayGraph2',1,'']]],
  ['2d_20snap_20rounding_29',['2D Snap Rounding',['../packages.html#PkgSnapRounding2',1,'']]],
  ['2d_20straight_20skeleton_20and_20polygon_20offsetting_30',['2D Straight Skeleton and Polygon Offsetting',['../packages.html#PkgStraightSkeleton2',1,'']]],
  ['2d_20triangulation_20data_20structure_31',['2D Triangulation Data Structure',['../packages.html#PkgTDS2',1,'']]],
  ['2d_20triangulations_32',['2D Triangulations',['../packages.html#PkgTriangulation2',1,'']]],
  ['2d_20triangulations_20on_20hyperbolic_20surfaces_33',['2D Triangulations on Hyperbolic Surfaces',['../packages.html#PkgHyperbolicSurfaceTriangulation2',1,'']]],
  ['2d_20triangulations_20on_20the_20sphere_34',['2D Triangulations on the Sphere',['../packages.html#PkgTriangulationOnSphere2',1,'']]],
  ['2d_20visibility_20computation_35',['2D Visibility Computation',['../packages.html#PkgVisibility2',1,'']]],
  ['2d_20voronoi_20diagram_20adaptor_36',['2D Voronoi Diagram Adaptor',['../packages.html#PkgVoronoiDiagram2',1,'']]]
];
