var annotated =
[
    [ "CGAL", null, [
      [ "Approximate_min_ellipsoid_d", "classCGAL_1_1Approximate__min__ellipsoid__d.html", "classCGAL_1_1Approximate__min__ellipsoid__d" ],
      [ "Approximate_min_ellipsoid_d_traits_2", "structCGAL_1_1Approximate__min__ellipsoid__d__traits__2.html", "structCGAL_1_1Approximate__min__ellipsoid__d__traits__2" ],
      [ "Approximate_min_ellipsoid_d_traits_3", "structCGAL_1_1Approximate__min__ellipsoid__d__traits__3.html", "structCGAL_1_1Approximate__min__ellipsoid__d__traits__3" ],
      [ "Approximate_min_ellipsoid_d_traits_d", "structCGAL_1_1Approximate__min__ellipsoid__d__traits__d.html", "structCGAL_1_1Approximate__min__ellipsoid__d__traits__d" ],
      [ "Min_annulus_d", "classCGAL_1_1Min__annulus__d.html", "classCGAL_1_1Min__annulus__d" ],
      [ "Min_circle_2", "classCGAL_1_1Min__circle__2.html", "classCGAL_1_1Min__circle__2" ],
      [ "Min_circle_2_traits_2", "classCGAL_1_1Min__circle__2__traits__2.html", "classCGAL_1_1Min__circle__2__traits__2" ],
      [ "Min_ellipse_2", "classCGAL_1_1Min__ellipse__2.html", "classCGAL_1_1Min__ellipse__2" ],
      [ "Min_ellipse_2_traits_2", "classCGAL_1_1Min__ellipse__2__traits__2.html", "classCGAL_1_1Min__ellipse__2__traits__2" ],
      [ "Min_quadrilateral_default_traits_2", "structCGAL_1_1Min__quadrilateral__default__traits__2.html", "structCGAL_1_1Min__quadrilateral__default__traits__2" ],
      [ "Min_sphere_annulus_d_traits_2", "classCGAL_1_1Min__sphere__annulus__d__traits__2.html", "classCGAL_1_1Min__sphere__annulus__d__traits__2" ],
      [ "Min_sphere_annulus_d_traits_3", "classCGAL_1_1Min__sphere__annulus__d__traits__3.html", "classCGAL_1_1Min__sphere__annulus__d__traits__3" ],
      [ "Min_sphere_annulus_d_traits_d", "classCGAL_1_1Min__sphere__annulus__d__traits__d.html", "classCGAL_1_1Min__sphere__annulus__d__traits__d" ],
      [ "Min_sphere_d", "classCGAL_1_1Min__sphere__d.html", "classCGAL_1_1Min__sphere__d" ],
      [ "Min_sphere_of_points_d_traits_2", "classCGAL_1_1Min__sphere__of__points__d__traits__2.html", "classCGAL_1_1Min__sphere__of__points__d__traits__2" ],
      [ "Min_sphere_of_points_d_traits_3", "classCGAL_1_1Min__sphere__of__points__d__traits__3.html", "classCGAL_1_1Min__sphere__of__points__d__traits__3" ],
      [ "Min_sphere_of_points_d_traits_d", "classCGAL_1_1Min__sphere__of__points__d__traits__d.html", "classCGAL_1_1Min__sphere__of__points__d__traits__d" ],
      [ "Min_sphere_of_spheres_d", "classCGAL_1_1Min__sphere__of__spheres__d.html", "classCGAL_1_1Min__sphere__of__spheres__d" ],
      [ "Min_sphere_of_spheres_d_traits_2", "classCGAL_1_1Min__sphere__of__spheres__d__traits__2.html", "classCGAL_1_1Min__sphere__of__spheres__d__traits__2" ],
      [ "Min_sphere_of_spheres_d_traits_3", "classCGAL_1_1Min__sphere__of__spheres__d__traits__3.html", "classCGAL_1_1Min__sphere__of__spheres__d__traits__3" ],
      [ "Min_sphere_of_spheres_d_traits_d", "classCGAL_1_1Min__sphere__of__spheres__d__traits__d.html", "classCGAL_1_1Min__sphere__of__spheres__d__traits__d" ],
      [ "Rectangular_p_center_default_traits_2", "classCGAL_1_1Rectangular__p__center__default__traits__2.html", "classCGAL_1_1Rectangular__p__center__default__traits__2" ]
    ] ],
    [ "ApproximateMinEllipsoid_d_Traits_d", "classApproximateMinEllipsoid__d__Traits__d.html", "classApproximateMinEllipsoid__d__Traits__d" ],
    [ "Circle", "classCircle.html", "classCircle" ],
    [ "Ellipse", "classEllipse.html", "classEllipse" ],
    [ "MinCircle2Traits", "classMinCircle2Traits.html", "classMinCircle2Traits" ],
    [ "MinEllipse2Traits", "classMinEllipse2Traits.html", "classMinEllipse2Traits" ],
    [ "MinQuadrilateralTraits_2", "classMinQuadrilateralTraits__2.html", "classMinQuadrilateralTraits__2" ],
    [ "MinSphereAnnulusDTraits", "classMinSphereAnnulusDTraits.html", "classMinSphereAnnulusDTraits" ],
    [ "MinSphereOfSpheresTraits", "classMinSphereOfSpheresTraits.html", "classMinSphereOfSpheresTraits" ],
    [ "RectangularPCenterTraits_2", "classRectangularPCenterTraits__2.html", "classRectangularPCenterTraits__2" ]
];