var searchData=
[
  ['i_2fo_0',['I/O',['../../Arrangement_on_surface_2/group__PkgArrangementOnSurface2IO.html',1,'(Global Namespace)'],['../../Surface_mesher/group__PkgSurfaceMesher3FunctionsIO.html',1,'(Global Namespace)']]],
  ['i_2fo_20_28las_20format_29_1',['I/O (LAS Format)',['../../Point_set_processing_3/group__PkgPointSetProcessing3IOLas.html',1,'']]],
  ['i_2fo_20_28off_20formats_29_2',['I/O (OFF Formats)',['../../Point_set_processing_3/group__PkgPointSetProcessing3IOOff.html',1,'']]],
  ['i_2fo_20_28ply_20format_29_3',['I/O (PLY Format)',['../../Point_set_processing_3/group__PkgPointSetProcessing3IOPly.html',1,'']]],
  ['i_2fo_20_28xyz_20formats_29_4',['I/O (XYZ Formats)',['../../Point_set_processing_3/group__PkgPointSetProcessing3IOXyz.html',1,'']]],
  ['i_2fo_20enums_5',['I/O Enums',['../../Stream_support/group__PkgStreamSupportEnumRef.html',1,'']]],
  ['i_2fo_20for_20a_20triangulation_203_6',['I/O for a Triangulation 3',['../../Triangulation_3/group__PkgIOTriangulation3.html',1,'']]],
  ['i_2fo_20for_20a_20triangulation_5fdata_5fstructure_5f3_7',['I/O for a Triangulation_data_structure_3',['../../TDS_3/group__PkgIOTDS3.html',1,'']]],
  ['i_2fo_20functions_8',['I/O Functions',['../../Stream_support/group__IOstreamFunctions.html',1,'(Global Namespace)'],['../../BGL/group__PkgBGLIOFct.html',1,'(Global Namespace)'],['../../Mesh_2/group__PkgMesh2IO.html',1,'(Global Namespace)'],['../../Nef_3/group__PkgNef3IOFunctions.html',1,'(Global Namespace)'],['../../Point_set_processing_3/group__PkgPointSetProcessing3IO.html',1,'(Global Namespace)'],['../../Polyhedron/group__PkgPolyhedronIOFunc.html',1,'(Global Namespace)'],['../../Surface_mesh/group__PkgSurfaceMeshIOFunc.html',1,'(Global Namespace)'],['../../Polygon_mesh_processing/group__PMP__IO__grp.html',1,'(Global Namespace)']]],
  ['i_2fo_20functions_20_283mf_29_9',['I/O Functions (3MF)',['../../Surface_mesh/group__PkgSurfaceMeshIOFunc3MF.html',1,'']]],
  ['i_2fo_20functions_20_28deprecated_29_10',['I/O Functions (Deprecated)',['../../BGL/group__PkgBGLIOFctDeprecated.html',1,'(Global Namespace)'],['../../Surface_mesh/group__PkgSurfaceMeshIOFuncDeprecated.html',1,'(Global Namespace)']]],
  ['i_2fo_20functions_20_28off_29_11',['I/O Functions (OFF)',['../../Surface_mesh/group__PkgSurfaceMeshIOFuncOFF.html',1,'']]],
  ['i_2fo_20functions_20_28ply_29_12',['I/O Functions (PLY)',['../../Surface_mesh/group__PkgSurfaceMeshIOFuncPLY.html',1,'']]],
  ['i_2fo_20streams_20reference_13',['I/O Streams Reference',['../../Stream_support/group__PkgStreamSupportRef.html',1,'']]],
  ['input_20classes_14',['Input Classes',['../../GraphicsView/group__PkgGraphicsViewInputClasses.html',1,'']]],
  ['input_2foutput_15',['Input/Output',['../../Point_set_3/group__PkgPointSet3IO.html',1,'']]],
  ['input_2foutput_20_28deprecated_29_16',['Input/Output (Deprecated)',['../../Point_set_3/group__PkgPointSet3IODeprecated.html',1,'']]],
  ['input_2foutput_20_28las_29_17',['Input/Output (LAS)',['../../Point_set_3/group__PkgPointSet3IOLAS.html',1,'']]],
  ['input_2foutput_20_28off_29_18',['Input/Output (OFF)',['../../Point_set_3/group__PkgPointSet3IOOFF.html',1,'']]],
  ['input_2foutput_20_28ply_29_19',['Input/Output (PLY)',['../../Point_set_3/group__PkgPointSet3IOPLY.html',1,'']]],
  ['input_2foutput_20_28xyz_29_20',['Input/Output (XYZ)',['../../Point_set_3/group__PkgPointSet3IOXYZ.html',1,'']]],
  ['input_2foutput_20functions_21',['Input/Output Functions',['../../Mesh_3/group__PkgMesh3IOFunctions.html',1,'(Global Namespace)'],['../../Periodic_3_mesh_3/group__PkgPeriodic3Mesh3IOFunctions.html',1,'(Global Namespace)'],['../../SMDS_3/group__PkgSMDS3IOFunctions.html',1,'(Global Namespace)']]],
  ['inscribed_20areas_20reference_22',['Inscribed Areas Reference',['../../Inscribed_areas/group__PkgInscribedAreasRef.html',1,'']]],
  ['interpolation_20functions_23',['Interpolation Functions',['../../Interpolation/group__PkgInterpolation2Interpolation.html',1,'']]],
  ['intersecting_20sequences_20of_20dd_20iso_2doriented_20boxes_20reference_24',['Intersecting Sequences of dD Iso-oriented Boxes Reference',['../../Box_intersection_d/group__PkgBoxIntersectionDRef.html',1,'']]],
  ['intersection_20computation_20functions_20_2d_20cgal_3a_3aintersection_28_29_25',['Intersection Computation Functions - CGAL::intersection()',['../../Kernel_23/group__intersection__grp.html',1,'']]],
  ['intersection_20functions_26',['Intersection Functions',['../../Polygon_mesh_processing/group__PMP__intersection__grp.html',1,'']]],
  ['intersection_20testing_20functions_20_2d_20cgal_3a_3ado_5fintersect_28_29_27',['Intersection Testing Functions - CGAL::do_intersect()',['../../Kernel_23/group__do__intersect__grp.html',1,'']]],
  ['interval_20skip_20list_20reference_28',['Interval Skip List Reference',['../../Interval_skip_list/group__PkgIntervalSkipListRef.html',1,'']]],
  ['inverse_20distance_20weight_29',['Inverse Distance Weight',['../../Weights/group__PkgWeightsRefInverseDistanceWeights.html',1,'']]],
  ['is_20pullout_20direction_30',['Is Pullout Direction',['../../Set_movable_separability_2/group__is__pullout__direction__grp.html',1,'']]],
  ['item_20classes_31',['Item Classes',['../../HalfedgeDS/group__PkgHalfedgeDS__Items.html',1,'']]],
  ['iterators_20and_20circulators_32',['Iterators and Circulators',['../../BGL/group__PkgBGLIterators.html',1,'']]],
  ['iterators_20and_20iterator_2fcirculator_20adaptors_33',['Iterators and Iterator/Circulator Adaptors',['../../STL_Extension/group__STLIterators.html',1,'']]]
];
