var searchData=
[
  ['i_20o_0',['I O',['../../Arrangement_on_surface_2/group__PkgArrangementOnSurface2IO.html',1,'I/O'],['../../Surface_mesher/group__PkgSurfaceMesher3FunctionsIO.html',1,'I/O']]],
  ['i_20o_20enums_1',['I/O Enums',['../../Stream_support/group__PkgStreamSupportEnumRef.html',1,'']]],
  ['i_20o_20for_20a_20triangulation_203_2',['I/O for a Triangulation 3',['../../Triangulation_3/group__PkgIOTriangulation3.html',1,'']]],
  ['i_20o_20for_20a_20triangulation_5fdata_5fstructure_5f3_3',['I/O for a Triangulation_data_structure_3',['../../TDS_3/group__PkgIOTDS3.html',1,'']]],
  ['i_20o_20functions_4',['I O Functions',['../../BGL/group__PkgBGLIoFuncs3MF.html',1,'3MF I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncs3MF.html',1,'3MF I/O Functions'],['../../BGL/group__PkgBGLIoFuncsGOCAD.html',1,'GOCAD I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncsGOCAD.html',1,'GOCAD I/O Functions'],['../../Polyhedron/group__PkgPolyhedronIOFunc.html',1,'I/O Functions'],['../../Surface_mesh/group__PkgSurfaceMeshIOFunc.html',1,'I/O Functions'],['../../Nef_3/group__PkgNef3IOFunctions.html',1,'I/O Functions'],['../../Mesh_2/group__PkgMesh2IO.html',1,'I/O Functions'],['../../Isosurfacing_3/group__IS__IO__functions__grp.html',1,'I/O Functions'],['../../PMP_Mesh_repair/group__PMP__IO__grp.html',1,'I/O Functions'],['../../Point_set_processing_3/group__PkgPointSetProcessing3IO.html',1,'I/O Functions'],['../../BGL/group__PkgBGLIOFct.html',1,'I/O Functions'],['../../Stream_support/group__IOstreamFunctions.html',1,'I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncsLAS.html',1,'LAS I/O Functions'],['../../BGL/group__PkgBGLIoFuncsOBJ.html',1,'OBJ I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncsOBJ.html',1,'OBJ I/O Functions'],['../../BGL/group__PkgBGLIoFuncsOFF.html',1,'OFF I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncsOFF.html',1,'OFF I/O Functions'],['../../BGL/group__PkgBGLIoFuncsOM.html',1,'OM I/O Functions'],['../../BGL/group__PkgBGLIoFuncsPLY.html',1,'PLY I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncsPLY.html',1,'PLY I/O Functions'],['../../BGL/group__PkgBGLIoFuncsSTL.html',1,'STL I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncsSTL.html',1,'STL I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncsVTK.html',1,'VTK I/O Functions'],['../../BGL/group__PkgBGLIoFuncsVTP.html',1,'VTP I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncsWKT.html',1,'WKT I/O Functions'],['../../BGL/group__PkgBGLIoFuncsWRL.html',1,'WRL I/O Functions'],['../../Stream_support/group__PkgStreamSupportIoFuncsXYZ.html',1,'XYZ I/O Functions']]],
  ['i_20o_20functions_203mf_5',['I/O Functions (3MF)',['../../Surface_mesh/group__PkgSurfaceMeshIOFunc3MF.html',1,'']]],
  ['i_20o_20functions_20deprecated_6',['I/O Functions (Deprecated)',['../../Surface_mesh/group__PkgSurfaceMeshIOFuncDeprecated.html',1,'']]],
  ['i_20o_20functions_20off_7',['I/O Functions (OFF)',['../../Surface_mesh/group__PkgSurfaceMeshIOFuncOFF.html',1,'']]],
  ['i_20o_20functions_20ply_8',['I/O Functions (PLY)',['../../Surface_mesh/group__PkgSurfaceMeshIOFuncPLY.html',1,'']]],
  ['in_20place_9',['Doubly-Connected List Managing Items in Place',['../../STL_Extension/group__inplacelist.html',1,'']]],
  ['in_20types_10',['Built-in types',['../../Number_types/group__nt__builtin.html',1,'']]],
  ['indices_11',['External Indices',['../../BGL/group__BGLGraphExternalIndices.html',1,'']]],
  ['initialization_20functors_12',['Mesh Initialization Functors',['../../Mesh_3/group__PkgMesh3Initializers.html',1,'']]],
  ['input_20classes_13',['Input Classes',['../../GraphicsView/group__PkgGraphicsViewInputClasses.html',1,'']]],
  ['input_20output_14',['Input/Output',['../../Point_set_3/group__PkgPointSet3IO.html',1,'']]],
  ['input_20output_20functions_15',['Input Output Functions',['../../Triangulation_on_hyperbolic_surface_2/group__PkgHyperbolicSurfaceTriangulation2InputOutput.html',1,'Input/Output Functions'],['../../SMDS_3/group__PkgSMDS3IOFunctions.html',1,'Input/Output Functions'],['../../Mesh_3/group__PkgMesh3IOFunctions.html',1,'Input/Output Functions'],['../../Periodic_3_mesh_3/group__PkgPeriodic3Mesh3IOFunctions.html',1,'Input/Output Functions']]],
  ['input_20output_20las_16',['Input/Output (LAS)',['../../Point_set_3/group__PkgPointSet3IOLAS.html',1,'']]],
  ['input_20output_20off_17',['Input/Output (OFF)',['../../Point_set_3/group__PkgPointSet3IOOFF.html',1,'']]],
  ['input_20output_20ply_18',['Input/Output (PLY)',['../../Point_set_3/group__PkgPointSet3IOPLY.html',1,'']]],
  ['input_20output_20xyz_19',['Input/Output (XYZ)',['../../Point_set_3/group__PkgPointSet3IOXYZ.html',1,'']]],
  ['integer_20programming_20',['Mixed Integer Programming',['../../Solver_interface/group__PkgSolverInterfaceMIP.html',1,'']]],
  ['interpolation_20functions_21',['Interpolation Functions',['../../Interpolation/group__PkgInterpolation2Interpolation.html',1,'']]],
  ['intersection_20computation_20functions_20cgal_3a_3aintersection_22',['Intersection Computation Functions - CGAL::intersection()',['../../Kernel_23/group__intersection__grp.html',1,'']]],
  ['intersection_20functions_23',['Intersection Functions',['../../Polygon_mesh_processing/group__PMP__intersection__grp.html',1,'Intersection Functions'],['../../Boolean_set_operations_2/group__boolean__intersection.html',1,'Polygon Intersection Functions']]],
  ['intersection_20test_20functions_24',['Intersection Test Functions',['../../Convex_hull_3/group__PkgConvexHull3Intersections.html',1,'']]],
  ['intersection_20testing_20functions_25',['Polygon Intersection Testing Functions',['../../Boolean_set_operations_2/group__boolean__do__intersect.html',1,'']]],
  ['intersection_20testing_20functions_20cgal_3a_3ado_5fintersect_26',['Intersection Testing Functions - CGAL::do_intersect()',['../../Kernel_23/group__do__intersect__grp.html',1,'']]],
  ['inverse_20distance_20weight_27',['Inverse Distance Weight',['../../Weights/group__PkgWeightsRefInverseDistanceWeights.html',1,'']]],
  ['io_20functions_20for_20cmap_28',['IO Functions for CMap',['../../Combinatorial_map/group__PkgCombinatorialMapsRefIO.html',1,'']]],
  ['io_20functions_20for_20lcc_29',['IO Functions for LCC',['../../Linear_cell_complex/group__PkgLinearCellComplexRefIO.html',1,'IO Functions for LCC'],['../../Linear_cell_complex/group__PkgLinearCellComplexRefIOVTK.html',1,'VTK IO Functions for LCC']]],
  ['is_20pullout_20direction_30',['Is Pullout Direction',['../../Set_movable_separability_2/group__is__pullout__direction__grp.html',1,'']]],
  ['isosurfacing_20domain_20helpers_31',['Isosurfacing Domain Helpers',['../../Isosurfacing_3/group__IS__Domain__helpers__grp.html',1,'']]],
  ['isosurfacing_20domains_32',['Isosurfacing Domains',['../../Isosurfacing_3/group__IS__Domains__grp.html',1,'']]],
  ['isosurfacing_20methods_33',['Isosurfacing Methods',['../../Isosurfacing_3/group__IS__Methods__grp.html',1,'']]],
  ['item_20classes_34',['Item Classes',['../../GraphicsView/group__PkgGraphicsViewGraphicsItemClasses.html',1,'Graphics Item Classes'],['../../HalfedgeDS/group__PkgHalfedgeDS__Items.html',1,'Item Classes'],['../../Spatial_searching/group__RangeQueryItemClasses.html',1,'Range Query Item Classes']]],
  ['items_20in_20place_35',['Doubly-Connected List Managing Items in Place',['../../STL_Extension/group__inplacelist.html',1,'']]],
  ['iterator_20circulator_20adaptors_36',['Iterators and Iterator/Circulator Adaptors',['../../STL_Extension/group__STLIterators.html',1,'']]],
  ['iterators_20and_20circulators_37',['Iterators and Circulators',['../../BGL/group__PkgBGLIterators.html',1,'']]],
  ['iterators_20and_20containers_38',['Adapters for Iterators and Containers',['../../Circulator/group__PkgHandlesAndCirculatorsAdapter.html',1,'']]],
  ['iterators_20and_20iterator_20circulator_20adaptors_39',['Iterators and Iterator/Circulator Adaptors',['../../STL_Extension/group__STLIterators.html',1,'']]]
];
