var classCGAL_1_1Surface__mesh__parameterization_1_1Circular__border__arc__length__parameterizer__3 =
[
    [ "compute_edge_length", "classCGAL_1_1Surface__mesh__parameterization_1_1Circular__border__arc__length__parameterizer__3.html#ae0b0760528ee0ff10d34de7fc0ab0ccb", null ]
];